INSERT INTO public.e_file_states (id, state_name) VALUES (-4, 'Abandon, données incohérentes');
INSERT INTO public.e_file_states (id, state_name) VALUES (-3, 'Abandon');
INSERT INTO public.e_file_states (id, state_name) VALUES (-2, 'Téléchargement');
INSERT INTO public.e_file_states (id, state_name) VALUES (-1, 'En cours');
INSERT INTO public.e_file_states (id, state_name) VALUES (0, 'Prêt');
INSERT INTO public.e_file_states (id, state_name) VALUES (1, 'Réussite');
INSERT INTO public.e_file_states (id, state_name) VALUES (2, 'Echec à reéssayer');
INSERT INTO public.e_file_states (id, state_name) VALUES (3, 'Echec permanent');
INSERT INTO public.e_file_states (id, state_name) VALUES (4, 'Ignoré');
INSERT INTO public.e_file_states (id, state_name) VALUES (5, 'Remplacé');
INSERT INTO public.e_file_states (id, state_name) VALUES (6, 'Dupliqué');
INSERT INTO public.e_file_states (id, state_name) VALUES (7, 'Réussite + Archivé');
INSERT INTO public.e_file_states (id, state_name) VALUES (8, 'Remplacé + Archivé');
INSERT INTO public.e_file_states (id, state_name) VALUES (9, 'Dupliqué + Archivé');
INSERT INTO public.e_file_states (id, state_name) VALUES (10, 'Echec permanent + Archivé');
INSERT INTO public.e_file_states (id, state_name) VALUES (11, 'Ignoré + Archivé');
INSERT INTO public.e_probe_parameter_origin (e_probe_parameter_origin_id, origin) VALUES (1, 'Valeur par défaut');
INSERT INTO public.e_probe_parameter_origin (e_probe_parameter_origin_id, origin) VALUES (2, 'Base de données');
INSERT INTO public.e_probe_parameter_origin (e_probe_parameter_origin_id, origin) VALUES (3, 'Fichier XML');
INSERT INTO public.e_probe_run_status (e_probe_run_status_id, status_name) VALUES (0, 'Jamais lancée');
INSERT INTO public.e_probe_run_status (e_probe_run_status_id, status_name) VALUES (1, 'Succes');
INSERT INTO public.e_probe_run_status (e_probe_run_status_id, status_name) VALUES (2, 'Pas de données importées');
INSERT INTO public.e_probe_run_status (e_probe_run_status_id, status_name) VALUES (3, 'Annulée');
INSERT INTO public.e_probe_run_status (e_probe_run_status_id, status_name) VALUES (4, 'Echouée');
INSERT INTO public.e_probe_run_status (e_probe_run_status_id, status_name) VALUES (5, 'Erreur');
INSERT INTO public.e_probe_run_status (e_probe_run_status_id, status_name) VALUES (6, 'En cours d''exécution');
INSERT INTO public.e_probe_run_status (e_probe_run_status_id, status_name) VALUES (7, 'Annulée avec erreur');
