INSERT INTO asset.e_asset_type (id, name) VALUES (1, 'Cluster');
INSERT INTO asset.e_asset_type (id, name) VALUES (2, 'Serveur');
INSERT INTO asset.e_asset_type (id, name) VALUES (3, 'Serveur applicatif');
INSERT INTO asset.e_asset_type (id, name) VALUES (4, 'Routeur');
INSERT INTO asset.e_asset_type (id, name) VALUES (5, 'Machine réseau');
INSERT INTO asset.e_asset_type (id, name) VALUES (6, 'Machine sécurité');
INSERT INTO asset.e_asset_type (id, name) VALUES (7, 'Périphérique d''accès');
INSERT INTO asset.e_asset_type (id, name) VALUES (8, 'Périphérique d''accès mobile');
INSERT INTO asset.e_asset_type (id, name) VALUES (9, 'Imprimante');
INSERT INTO asset.e_sc (id, name) VALUES (1, 'Critique pour l''entreprise');
INSERT INTO asset.e_sc (id, name) VALUES (2, 'Nécessaire pour l''entreprise');
INSERT INTO asset.e_sc (id, name) VALUES (3, 'Pour l''entreprise');
INSERT INTO asset.e_sc (id, name) VALUES (4, 'Support pour l''entreprise');
INSERT INTO asset.e_sc (id, name) VALUES (5, 'Infrastructure');
INSERT INTO asset.e_sc (id, name) VALUES (6, 'Non critique pour l''entreprise');
INSERT INTO asset.e_sc (id, name) VALUES (7, 'Non lié à l''entreprise');
INSERT INTO asset.e_bl (id, name) VALUES (1, 'TI');
INSERT INTO asset.e_bl (id, name) VALUES (2, 'Corporate');
INSERT INTO asset.e_bl (id, name) VALUES (3, 'Ventes');
INSERT INTO asset.e_bl (id, name) VALUES (4, 'Marketing');
INSERT INTO asset.e_bl (id, name) VALUES (5, 'R&D');
INSERT INTO asset.e_bl (id, name) VALUES (6, 'Production');
INSERT INTO asset.e_bl (id, name) VALUES (7, 'Comptabilité');
INSERT INTO asset.e_bl (id, name) VALUES (8, 'Financement');
INSERT INTO asset.e_bl (id, name) VALUES (9, 'Domaines');
INSERT INTO asset.e_bl (id, name) VALUES (10, 'Partenaires de travail');
INSERT INTO asset.e_availability (id, name) VALUES (1, 'Ininterrompu');
INSERT INTO asset.e_availability (id, name) VALUES (2, 'Haute disponibilité');
INSERT INTO asset.e_availability (id, name) VALUES (3, '99%');
INSERT INTO asset.e_availability (id, name) VALUES (4, 'Horaires de travail');
INSERT INTO asset.e_availability (id, name) VALUES (5, 'Meilleur effort');
