INSERT INTO risk.e_category (e_category_id, category_name) VALUES (1, 'Maladies');
INSERT INTO risk.e_category (e_category_id, category_name) VALUES (2, 'Economique');
INSERT INTO risk.e_category (e_category_id, category_name) VALUES (3, 'Environnemental');
INSERT INTO risk.e_category (e_category_id, category_name) VALUES (4, 'Financier');
INSERT INTO risk.e_category (e_category_id, category_name) VALUES (5, 'Humain');
INSERT INTO risk.e_category (e_category_id, category_name) VALUES (6, 'Naturel');
INSERT INTO risk.e_category (e_category_id, category_name) VALUES (7, 'Santé');
INSERT INTO risk.e_category (e_category_id, category_name) VALUES (8, 'Responsabilité produit');
INSERT INTO risk.e_category (e_category_id, category_name) VALUES (9, 'Responsabilité professionnelle');
INSERT INTO risk.e_category (e_category_id, category_name) VALUES (10, 'Dégâts matériels');
INSERT INTO risk.e_category (e_category_id, category_name) VALUES (11, 'Responsabilité publique');
INSERT INTO risk.e_category (e_category_id, category_name) VALUES (12, 'Sécurité');
INSERT INTO risk.e_category (e_category_id, category_name) VALUES (13, 'Technologique');
INSERT INTO risk.e_risk_decision (e_risk_decision_id, decision) VALUES (1, 'Réduction');
INSERT INTO risk.e_risk_decision (e_risk_decision_id, decision) VALUES (2, 'Atténuation');
INSERT INTO risk.e_risk_decision (e_risk_decision_id, decision) VALUES (3, 'Eviter');
INSERT INTO risk.e_risk_decision (e_risk_decision_id, decision) VALUES (4, 'Transfert');
INSERT INTO risk.e_risk_priority (e_risk_priority_id, priority) VALUES (1, 'Mineur');
INSERT INTO risk.e_risk_priority (e_risk_priority_id, priority) VALUES (2, 'Faible');
INSERT INTO risk.e_risk_priority (e_risk_priority_id, priority) VALUES (3, 'Normal');
INSERT INTO risk.e_risk_priority (e_risk_priority_id, priority) VALUES (4, 'Important');
INSERT INTO risk.e_risk_priority (e_risk_priority_id, priority) VALUES (5, 'Urgent');
INSERT INTO risk.e_risk_priority (e_risk_priority_id, priority) VALUES (6, 'Critique');
INSERT INTO risk.e_risk_level (e_risk_level_id, level) VALUES (1, 'Faible');
INSERT INTO risk.e_risk_level (e_risk_level_id, level) VALUES (2, 'Moyen');
INSERT INTO risk.e_risk_level (e_risk_level_id, level) VALUES (3, 'Significatif');
INSERT INTO risk.e_risk_level (e_risk_level_id, level) VALUES (4, 'Elevé');
INSERT INTO risk.e_action_status (e_action_status_id, action_status) VALUES (1, 'Planifié');
INSERT INTO risk.e_action_status (e_action_status_id, action_status) VALUES (2, 'En cours');
INSERT INTO risk.e_action_status (e_action_status_id, action_status) VALUES (3, 'Finalisé');
INSERT INTO risk.e_action_status (e_action_status_id, action_status) VALUES (4, 'Annulé');
INSERT INTO risk.e_action_status (e_action_status_id, action_status) VALUES (5, 'En pause');
