INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.rootDir', 'Répertoire principal.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.errorsDir', 'Répertoire des erreurs concernant les fichiers incorrects.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.errorsSize', 'Taille maximale du répertoire des erreurs.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.reportsDir', 'Répertoire de stockage des rapports.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.defaultCompany', 'Nom d''entreprise par défaut.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.poweredByLogo', 'Chemin vers le logo poweredBy.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.web.localServerPort', 'Port de Tomcat.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.web.localServerAddress', 'Adresse locale du serveur.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.web.remoteServerProtocol', 'Protocole.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.mail.MailHelper.hostName', 'Nom d''hôte du serveur SMTP.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.mail.MailHelper.hostPort', 'Port du serveur SMTP.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.mail.MailHelper.useTls', 'Usage d''une sécurisation (TLS, SSL) sur le serveur SMTP.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.mail.MailHelper.useAuth', 'Usage d''une authentification sur le serveur SMTP.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.mail.MailHelper.smtpUser', 'Utilisateur SMTP.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.feature.attachCalendarFile', 'Attacher un fichier iCal aux emails générés.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.mail.MailHelper.smtpPassword', 'Mot de passe SMTP.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.mail.MailHelper.maxTries', 'Nombre d''essais avant l''échec de l''envoi d''un email.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.mail.MailHelper.maxEmailSentAtOnce', 'Nombre d''emails maximum à envoyer par lot.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.mail.MailHelper.iconLocation', 'Chemin vers le logo de l''entreprise.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.soap.SessionHandler.timeoutMinutes', 'Durée de la session en minutes.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.soap.soapBase.authMethod', 'Méthode d''authentification.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.maxReturnedRows', 'Nombre maximum d''élements retournés par une grille de données par défaut.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.soap.auth.LDAP.base', 'Base pour l''authetification LDAP.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.soap.auth.LDAP.baseFilterString', 'Filtre de base pour l''authetification LDAP.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.soap.auth.LDAP.userNameField', 'Nom d''utilisateur pour l''authentification LDAP.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.soap.auth.LDAP.url', 'URL pour l''authentification LDAP.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.soap.auth.LDAP.searchUserName', 'Search user name pour l''authentification LDAP.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.soap.auth.LDAP.searchPassword', 'Mot de passe pour l''authentification LDAP.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpHelper.userAgent', 'Agent utilisateur pour le protocol HTTP.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpHelper.useProxy', 'Utilisation d''un proxy pour la connexion HTTP.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpHelper.proxyHost', 'Nom d''hôte du proxy HTTP.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpHelper.proxyPort', 'Port du proxy HTTP.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpHelper.useProxyAuth', 'Utilisation d''une authentification pour le proxy HTTP.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpHelper.proxyRealm', 'Realm authentification pour le proxy HTTP.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpHelper.proxyScheme', 'Scheme authentification pour le proxy HTTP.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpHelper.proxyUserName', 'Nom d''utilisateur pour le proxy HTTP.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpHelper.proxyPassword', 'Mot de passe pour le proxy HTTP.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpSslHelper.userAgent', 'Agent utilisateur pour le protocol HTTPS.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpSslHelper.useProxy', 'Utilisation d''un proxy pour la connexion HTTPS.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpSslHelper.proxyHost', 'Nom d''hôte du proxy HTTPS.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpSslHelper.proxyPort', 'Port du proxy HTTPS.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpSslHelper.useProxyAuth', 'Utilisation d''une authentification pour le proxy HTTPS.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpSslHelper.proxyRealm', 'Realm authentification pour le proxy HTTPS.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpSslHelper.proxyScheme', 'Scheme authentification pour le proxy HTTPS.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpSslHelper.proxyUserName', 'Nom d''utilisateur du proxy HTTPS.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpSslHelper.proxyPassword', 'Mot de passe du proxy HTTPS.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpSslHelper.keyStore', 'Fichier de certificats (keystore) pour HTTPS.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpSslHelper.keyStorePassword', 'Mot de passe pour le fichier de certificats (keystore) pour HTTPS.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.license.LicenseHelper.publicStore', 'Répertoire public pour l''authentification des licences.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.raci.strict_RACI', 'RACI mode strict.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.cnilLevel', 'Niveau CNIL.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.logDirectory', 'Chemin du répertoir contenant les fichiers log.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.probeXmlFile', 'Chemin vers le XML de définition des sondes.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.probes.showProbeSnailOnLastNDays', 'Période maximale par défaut pour vérifier l''exécution des sondes.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.module.Admin.can_edit_its_own_expertises', 'Les utilisateurs peuvent éditer leurs expertises propres.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.feature.notifyMail', 'Activation de la notification par email.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.feature.notifySelfMail', 'Activation de la notification par email pour sa propre adresse email.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.feature.attachHtmlMail', 'Générer des emails HTML.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.feature.sendEmailOnExpertiseChange', 'Envoyer un email lors du changement d''une expertise.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.feature.sendEmailOnRACIChange', 'Envoyer un email lors du changement d''une matrice RACI.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.feature.sendEmailOnObjectModification', 'Envoyer un email lorsque un objet, un élément est modifié.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.feature.sendEmailOnObjectCreation', 'Envoyer un email lors de la création d''un objet, d''un élément.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.mail.MailHelper.receiveEmailOnChange', 'Niveau de la matrice RACI nécessaire pour recevoir les emails.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.raci.delayRaciChangeOnModule', 'Retarder les changements de matrice RACI pour vérification.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.SupportNotifier.supportEmail', 'Email du support.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.feature.SupportNotifier', 'Activer la notification au support.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.mail.MailHelper.defaultFromAddress', 'Adresse DE par défaut dans les emails.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.security.minPasswordLength', 'Taille minimale du mot de passe.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.security.passwordComplexity', 'Utiliser les règles de complexité sur les mots de passe.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.security.passwordAge', 'Durée de vie maximum d''un mot de passe en jours.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.security.passwordHistory', 'Nombre de mot de passe stockés dans l''historique pour chaque utilisateur.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.security.loginHistoryAge', 'Durée maximale en jours de la dernière connexion utilisateur.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.security.numberOfFailedLoginLimit', 'Nombre d''échec de connexion utilisateur avant blocage du compte.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.security.failedLoginTimeLimit', 'Durée limite en minutes entre échecs de connexion utilisateur.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.security.automatedLostPassword', 'Active le bouton Mot de passe perdu qui permet de recevoir un nouveau mot de passe par email ou si l''utilisateur n''a pas d''email de générer un incident de l''application.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.provider.calendar.DbCalendar.redefineFirstDayOfWeek', 'Redefinir le premier jour de la semain (ou utiliser le jour par défaut du système).');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.provider.calendar.DbCalendar.firstDayOfWeek', 'Premier jour de la semaine (1=Dimanche,7=Samedi).');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.module.Admin.language', 'Langue de l''application.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.module.Audit.user_see_my_only', 'Les utilisateurs ne peuvent voir un élément que s''ils sont dans la matrice RACI liée.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.module.Audit.escaladeActionAfterNDelays', 'Nombre de reports avant de noter une action comme trop repoussée.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.module.Audit.escaladeRecommendationAfterNDelays', 'Nombre de reports avant de noter une recommandation comme trop repoussée.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.feature.hideNewProduct', 'Masquer les nouveaux produits importés par les sondes.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.feature.hideNewVendor', 'Masquer les nouveaux fournisseurs, vendeurs importés par les sondes.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.soap.soapIdentityManagement.IMReportClassName', 'Classe de rapport chargée pour obtenir les métriques.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.im.snail_colors.percent_low', 'Pourcentage entre métrique et cible sous lequel le métrique est considéré comme bon.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.im.snail_colors.percent_medium', 'Pourcentage entre métrique et cible sous lequel le métrique est considéré comme assez bon.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.im.snail_colors.percent_high', 'Pourcentage entre métrique et cible sous lequel le métrique est considéré comme moyen.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.im.snail_colors.percent_bad', 'Pourcentage entre métrique et cible sous lequel le métrique est considéré comme mauvais.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.http.average_hits_per_page', 'Nombre moyen de requêtes (hits) par page.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.http.average_time_spent_per_page', 'Temps moyen passé sur une page en secondes.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.module.Portal.numberOfGridsInChart', 'Nombre de données sur l''axe Y pour les graphiques en lignes.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.module.Portal.gridFrom0', 'Afficher les valeurs à partir de 0 dans les graphiques en lignes.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.module.Portal.ignoredCategories', 'Afficher les catégories Internet ignorées dans les listes.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.module.Portal.show_others_in_pie', 'Afficher la partie Autres données dans les graphiques camemberts.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.module.RiskAssessment.user_see_my_only', 'Les utilisateurs ne peuvent voir un élément que s''ils sont dans la matrice RACI liée.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.module.RiskModelisation.user_see_my_only', 'Les utilisateurs ne peuvent voir un élément que s''ils sont dans la matrice RACI liée.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.vrt.actions.actions_fixed_before_vuln_fixed', 'Une vulnérabilité peut être corrigée (ou non-corrigée) que si toutes ses actions sont dans un statut corrigé (ou non-corrigé).');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.vrt.closed_vrt_vuln_can_change_decision', 'La décision appliquée à une vulnérabilité peut être modifiée même dans un regroupement de vulnérabilité fermé.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.vrt.user_see_my_only', 'Les utilisateurs ne peuvent voir un élément que s''ils sont dans la matrice RACI liée.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.vrt.user_see_my_new_only', 'Spécifique à l''écran des nouvelles vulnérabilités: les utilisateurs ne peuvent voir un élément que s''ils sont dans la matrice RACI liée.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.vrt.vote_ignore_decision_ceiling', 'Seulement actif en mode Vote quand tous les experts doivent voter. C''est le nombre minimal de vote nécessaire pour activer la décision sur une vulnérabilité.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.vrt.vote_instead_of_decision', 'Activation du mode Vote pour trier les vulnérabilités et les regrouper.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.vrt.simplifiedVRTProcess', 'Activation du mode Vote Simplifié: dès le premier vote la vulnérabilité est placée dans un regroupement existant et peut recevoir des votes jusqu''à son analyse. Note: une action est générée pour chaque vote sur une vulnérabilité. La vulnérabilité peut être analysée même si son regroupement n''a pas été démarré. La décision appliquée à la vulnérabilité est automatiquement mise en réparation ou ignorée en fonction du type de vote.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.vrt.votesBasedDecision', 'La décision des vulnérabilités votées peut être modifiée.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.vrt.votesBasedDecision.IgnoredDecision', 'Décision par défaut utilisée pour une vulnérabilité recevant ignoré en vote (table vuln.e_vulnerability_status).');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.vrt.votesBasedDecision.AddDecision', 'Décision par défaut utilisée pour une vulnérabilité ajoutée à un regroupement suite à un vote (table vuln.e_vulnerability_status).');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.vrt.only_experts_can_vote', 'Seulement actif en mode Vote. Seuls les experts pour cette vulnérabilité peuvent voter.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.vrt.can_vote_until_analysis', 'Seulement actif en mode Vote. Une vulnérabilité peut recevoir des votes jusqu''à son analyse.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.vrt.oneVotePerExpertDepartment', 'Le membre d''un département de l''entreprise expert pour un type de vulnérabilité evite aux autres membres de voter.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.vrt.createActionOnTriage', 'Création d''une action lors d''un vote (ou d''un tri) sur une vulnérabilité.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.vrt.commentRequiredOnIgnore', 'Lorsqu''une vulnérabilité est ignorée, l''utilisateur doit commenter son action.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.vrt.triageOnRenewedVulnOutdoHigherDecision', 'Le tri d''une vulnerabilité réouverte change sa décision.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.provider.vrt.url.securityfocus', 'Modèle d''URL pour accéder à la version web des données de vulnérabilités SecurityFocus.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.provider.vrt.url.microsoft', 'Modèle d''URL pour accéder à la version web des données de vulnérabilités Microsoft.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.provider.vrt.url.nist', 'Modèle d''URL pour accéder à la version web des données de vulnérabilités NVD.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.provider.vrt.url.certist', 'Modèle d''URL pour accéder à la version web des données de vulnérabilités Cert-IST.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.feature.notifyNewVulnsForExperts', 'Emails envoyés aux experts concernés par des nouvelles vulnérabiltés.');
