UPDATE asset.e_asset_type SET name = 'Cluster' WHERE id = 1;
UPDATE asset.e_asset_type SET name = 'Serveur' WHERE id = 2;
UPDATE asset.e_asset_type SET name = 'Serveur applicatif' WHERE id = 3;
UPDATE asset.e_asset_type SET name = 'Routeur' WHERE id = 4;
UPDATE asset.e_asset_type SET name = 'Machine réseau' WHERE id = 5;
UPDATE asset.e_asset_type SET name = 'Machine sécurité' WHERE id = 6;
UPDATE asset.e_asset_type SET name = 'Périphérique d''accès' WHERE id = 7;
UPDATE asset.e_asset_type SET name = 'Périphérique d''accès mobile' WHERE id = 8;
UPDATE asset.e_asset_type SET name = 'Imprimante' WHERE id = 9;
UPDATE asset.e_sc SET name = 'Critique pour l''entreprise' WHERE id = 1;
UPDATE asset.e_sc SET name = 'Nécessaire pour l''entreprise' WHERE id = 2;
UPDATE asset.e_sc SET name = 'Pour l''entreprise' WHERE id = 3;
UPDATE asset.e_sc SET name = 'Support pour l''entreprise' WHERE id = 4;
UPDATE asset.e_sc SET name = 'Infrastructure' WHERE id = 5;
UPDATE asset.e_sc SET name = 'Non critique pour l''entreprise' WHERE id = 6;
UPDATE asset.e_sc SET name = 'Non lié à l''entreprise' WHERE id = 7;
UPDATE asset.e_bl SET name = 'TI' WHERE id = 1;
UPDATE asset.e_bl SET name = 'Corporate' WHERE id = 2;
UPDATE asset.e_bl SET name = 'Ventes' WHERE id = 3;
UPDATE asset.e_bl SET name = 'Marketing' WHERE id = 4;
UPDATE asset.e_bl SET name = 'R&D' WHERE id = 5;
UPDATE asset.e_bl SET name = 'Production' WHERE id = 6;
UPDATE asset.e_bl SET name = 'Comptabilité' WHERE id = 7;
UPDATE asset.e_bl SET name = 'Financement' WHERE id = 8;
UPDATE asset.e_bl SET name = 'Domaines' WHERE id = 9;
UPDATE asset.e_bl SET name = 'Partenaires de travail' WHERE id = 10;
UPDATE asset.e_availability SET name = 'Ininterrompu' WHERE id = 1;
UPDATE asset.e_availability SET name = 'Haute disponibilité' WHERE id = 2;
UPDATE asset.e_availability SET name = '99%' WHERE id = 3;
UPDATE asset.e_availability SET name = 'Horaires de travail' WHERE id = 4;
UPDATE asset.e_availability SET name = 'Meilleur effort' WHERE id = 5;
