UPDATE mim.t_user_anomaly SET description = 'None' WHERE t_user_anomaly_id = 1;
UPDATE mim.t_user_anomaly SET description = 'Fudge : mainframe data missing' WHERE t_user_anomaly_id = 2;
UPDATE mim.t_user_anomaly SET description = 'Fudge : mainframe date security admin missing' WHERE t_user_anomaly_id = 3;
UPDATE mim.t_user_anomaly SET description = 'Fudge : mainframe datecontractvalidity abnormal' WHERE t_user_anomaly_id = 4;
UPDATE mim.t_user_anomaly SET description = 'Fudge : mainframe date1sthire bad' WHERE t_user_anomaly_id = 5;
UPDATE mim.t_user_anomaly SET description = 'Fudge : mainframe ou bad' WHERE t_user_anomaly_id = 6;
UPDATE mim.t_user_anomaly SET description = 'Fudge : mainframe l bad' WHERE t_user_anomaly_id = 7;
UPDATE mim.t_user_anomaly SET description = 'Fudge : ad data missing' WHERE t_user_anomaly_id = 8;
UPDATE mim.t_user_anomaly SET description = 'Fudge : ad date is 0' WHERE t_user_anomaly_id = 9;
UPDATE mim.t_user_anomaly SET description = 'Fudge : hr data missing' WHERE t_user_anomaly_id = 10;
UPDATE mim.t_user_anomaly SET description = 'Fudge : hr logoncount missing' WHERE t_user_anomaly_id = 11;
UPDATE mim.t_user_anomaly SET description = 'Fudge : hr still has 19000000 as dates' WHERE t_user_anomaly_id = 12;
UPDATE mim.t_user_anomaly SET description = 'Fudge : hr still has 19800101 as dates' WHERE t_user_anomaly_id = 13;
