UPDATE public.e_file_states SET state_name = 'Abandon, données incohérentes' WHERE id = -4;
UPDATE public.e_file_states SET state_name = 'Abandon' WHERE id = -3;
UPDATE public.e_file_states SET state_name = 'Téléchargement' WHERE id = -2;
UPDATE public.e_file_states SET state_name = 'En cours' WHERE id = -1;
UPDATE public.e_file_states SET state_name = 'Prêt' WHERE id = 0;
UPDATE public.e_file_states SET state_name = 'Réussite' WHERE id = 1;
UPDATE public.e_file_states SET state_name = 'Echec à reéssayer' WHERE id = 2;
UPDATE public.e_file_states SET state_name = 'Echec permanent' WHERE id = 3;
UPDATE public.e_file_states SET state_name = 'Ignoré' WHERE id = 4;
UPDATE public.e_file_states SET state_name = 'Remplacé' WHERE id = 5;
UPDATE public.e_file_states SET state_name = 'Dupliqué' WHERE id = 6;
UPDATE public.e_file_states SET state_name = 'Réussite + Archivé' WHERE id = 7;
UPDATE public.e_file_states SET state_name = 'Remplacé + Archivé' WHERE id = 8;
UPDATE public.e_file_states SET state_name = 'Dupliqué + Archivé' WHERE id = 9;
UPDATE public.e_file_states SET state_name = 'Echec permanent + Archivé' WHERE id = 10;
UPDATE public.e_file_states SET state_name = 'Ignoré + Archivé' WHERE id = 11;
UPDATE public.e_probe_parameter_origin SET origin = 'Valeur par défaut' WHERE e_probe_parameter_origin_id = 1;
UPDATE public.e_probe_parameter_origin SET origin = 'Base de données' WHERE e_probe_parameter_origin_id = 2;
UPDATE public.e_probe_parameter_origin SET origin = 'Fichier XML' WHERE e_probe_parameter_origin_id = 3;
UPDATE public.e_probe_run_status SET status_name = 'Jamais lancée' WHERE e_probe_run_status_id = 0;
UPDATE public.e_probe_run_status SET status_name = 'Succes' WHERE e_probe_run_status_id = 1;
UPDATE public.e_probe_run_status SET status_name = 'Pas de données importées' WHERE e_probe_run_status_id = 2;
UPDATE public.e_probe_run_status SET status_name = 'Annulée' WHERE e_probe_run_status_id = 3;
UPDATE public.e_probe_run_status SET status_name = 'Echouée' WHERE e_probe_run_status_id = 4;
UPDATE public.e_probe_run_status SET status_name = 'Erreur' WHERE e_probe_run_status_id = 5;
UPDATE public.e_probe_run_status SET status_name = 'En cours d''exécution' WHERE e_probe_run_status_id = 6;
UPDATE public.e_probe_run_status SET status_name = 'Annulée avec erreur' WHERE e_probe_run_status_id = 7;
