UPDATE itsm.t_status SET status_name = 'Nouveau' WHERE t_status_id = 1;
UPDATE itsm.t_status SET status_name = 'En cours' WHERE t_status_id = 2;
UPDATE itsm.t_status SET status_name = 'Annulé' WHERE t_status_id = 3;
UPDATE itsm.t_status SET status_name = 'Corrigé' WHERE t_status_id = 4;
UPDATE itsm.t_status SET status_name = 'Non corrigé' WHERE t_status_id = 5;
UPDATE itsm.t_status SET status_name = 'Clos' WHERE t_status_id = 6;
UPDATE itsm.t_ipsu SET ipsu_name = 'Non bloquant' WHERE t_ipsu_id = 1;
UPDATE itsm.t_ipsu SET ipsu_name = 'Individuel' WHERE t_ipsu_id = 2;
UPDATE itsm.t_ipsu SET ipsu_name = 'Groupe' WHERE t_ipsu_id = 3;
UPDATE itsm.t_ipsu SET ipsu_name = 'Basse' WHERE t_ipsu_id = 11;
UPDATE itsm.t_ipsu SET ipsu_name = 'Moyenne' WHERE t_ipsu_id = 12;
UPDATE itsm.t_ipsu SET ipsu_name = 'Haute' WHERE t_ipsu_id = 13;
UPDATE itsm.t_ipsu SET ipsu_name = 'Basse' WHERE t_ipsu_id = 21;
UPDATE itsm.t_ipsu SET ipsu_name = 'Moyenne' WHERE t_ipsu_id = 22;
UPDATE itsm.t_ipsu SET ipsu_name = 'Haute' WHERE t_ipsu_id = 23;
UPDATE itsm.t_ipsu SET ipsu_name = 'Normal' WHERE t_ipsu_id = 31;
UPDATE itsm.t_ipsu SET ipsu_name = 'Urgent' WHERE t_ipsu_id = 32;
UPDATE itsm.t_ipsu SET ipsu_name = 'Immédiat' WHERE t_ipsu_id = 33;
UPDATE itsm.t_satisfaction_level SET satisfaction_level = 'Très élevé' WHERE t_satisfaction_level_id = 1;
UPDATE itsm.t_satisfaction_level SET satisfaction_level = 'Elevé' WHERE t_satisfaction_level_id = 2;
UPDATE itsm.t_satisfaction_level SET satisfaction_level = 'Moyen' WHERE t_satisfaction_level_id = 3;
UPDATE itsm.t_satisfaction_level SET satisfaction_level = 'Bas' WHERE t_satisfaction_level_id = 4;
