UPDATE risk.e_likelihood SET name = 'Rare' WHERE e_likelihood_id = 1;
UPDATE risk.e_likelihood SET name = 'Improbable' WHERE e_likelihood_id = 2;
UPDATE risk.e_likelihood SET name = 'Modéré' WHERE e_likelihood_id = 3;
UPDATE risk.e_likelihood SET name = 'Probable' WHERE e_likelihood_id = 4;
UPDATE risk.e_likelihood SET name = 'Certain' WHERE e_likelihood_id = 5;
UPDATE risk.e_likelihood SET description = 'L''évènement ne peut se produire qu''en des cisconstances exceptionnelles' WHERE e_likelihood_id = 1;
UPDATE risk.e_likelihood SET description = 'L''évènement peut se produire à l''occasion' WHERE e_likelihood_id = 2;
UPDATE risk.e_likelihood SET description = 'L''évènement se produira probablement de temps en temps' WHERE e_likelihood_id = 3;
UPDATE risk.e_likelihood SET description = 'L''évènement se produira probablement la plupart du temps' WHERE e_likelihood_id = 4;
UPDATE risk.e_likelihood SET description = 'L''évènement se produira probablement lors de la majorité des cas' WHERE e_likelihood_id = 5;
UPDATE risk.e_consequence_level SET label = 'Négligeable' WHERE e_consequence_level_id = 1;
UPDATE risk.e_consequence_level SET label = 'Mineur' WHERE e_consequence_level_id = 2;
UPDATE risk.e_consequence_level SET label = 'Modéré' WHERE e_consequence_level_id = 3;
UPDATE risk.e_consequence_level SET label = 'Majeur' WHERE e_consequence_level_id = 4;
UPDATE risk.e_consequence_level SET label = 'Catastrophique' WHERE e_consequence_level_id = 5;
UPDATE risk.e_consequence_level SET label = 'Négligeable' WHERE e_consequence_level_id = 11;
UPDATE risk.e_consequence_level SET label = 'Mineur' WHERE e_consequence_level_id = 12;
UPDATE risk.e_consequence_level SET label = 'Modéré' WHERE e_consequence_level_id = 13;
UPDATE risk.e_consequence_level SET label = 'Majeur' WHERE e_consequence_level_id = 14;
UPDATE risk.e_consequence_level SET label = 'Exceptionnnel' WHERE e_consequence_level_id = 15;
UPDATE risk.e_consequence_level SET description = 'Pas de dommages, déficit faible' WHERE e_consequence_level_id = 1;
UPDATE risk.e_consequence_level SET description = 'Premiers secours, déficit moyen' WHERE e_consequence_level_id = 2;
UPDATE risk.e_consequence_level SET description = 'Traitement requis, déficit élevé' WHERE e_consequence_level_id = 3;
UPDATE risk.e_consequence_level SET description = 'Dommages étendus, déficit majeur' WHERE e_consequence_level_id = 4;
UPDATE risk.e_consequence_level SET description = 'Mort, déficit immense' WHERE e_consequence_level_id = 5;
UPDATE risk.e_consequence_level SET description = 'Peu de bénéfices, profits faibles' WHERE e_consequence_level_id = 11;
UPDATE risk.e_consequence_level SET description = 'Améliorations mineures, quelques profits' WHERE e_consequence_level_id = 12;
UPDATE risk.e_consequence_level SET description = 'Quelques améliorations, profits importants' WHERE e_consequence_level_id = 13;
UPDATE risk.e_consequence_level SET description = 'Nombreuses améliorations, profit majeur' WHERE e_consequence_level_id = 14;
UPDATE risk.e_consequence_level SET description = 'Réputation significativement améliorée, très grands profits' WHERE e_consequence_level_id = 15;
