UPDATE public.e_preference_descriptions SET description = 'Répertoire principal.' WHERE parameter = 'com.entelience.esis.rootDir';
UPDATE public.e_preference_descriptions SET description = 'Répertoire des erreurs concernant les fichiers incorrects.' WHERE parameter = 'com.entelience.esis.errorsDir';
UPDATE public.e_preference_descriptions SET description = 'Taille maximale du répertoire des erreurs.' WHERE parameter = 'com.entelience.esis.errorsSize';
UPDATE public.e_preference_descriptions SET description = 'Répertoire de stockage des rapports.' WHERE parameter = 'com.entelience.esis.reportsDir';
UPDATE public.e_preference_descriptions SET description = 'Nom d''entreprise par défaut.' WHERE parameter = 'com.entelience.esis.defaultCompany';
UPDATE public.e_preference_descriptions SET description = 'Chemin vers le logo poweredBy.' WHERE parameter = 'com.entelience.esis.poweredByLogo';
UPDATE public.e_preference_descriptions SET description = 'Port de Tomcat.' WHERE parameter = 'com.entelience.esis.web.localServerPort';
UPDATE public.e_preference_descriptions SET description = 'Adresse locale du serveur.' WHERE parameter = 'com.entelience.esis.web.localServerAddress';
UPDATE public.e_preference_descriptions SET description = 'Protocole.' WHERE parameter = 'com.entelience.esis.web.remoteServerProtocol';
UPDATE public.e_preference_descriptions SET description = 'Nom d''hôte du serveur SMTP.' WHERE parameter = 'com.entelience.mail.MailHelper.hostName';
UPDATE public.e_preference_descriptions SET description = 'Port du serveur SMTP.' WHERE parameter = 'com.entelience.mail.MailHelper.hostPort';
UPDATE public.e_preference_descriptions SET description = 'Usage d''une sécurisation (TLS, SSL) sur le serveur SMTP.' WHERE parameter = 'com.entelience.mail.MailHelper.useTls';
UPDATE public.e_preference_descriptions SET description = 'Usage d''une authentification sur le serveur SMTP.' WHERE parameter = 'com.entelience.mail.MailHelper.useAuth';
UPDATE public.e_preference_descriptions SET description = 'Utilisateur SMTP.' WHERE parameter = 'com.entelience.mail.MailHelper.smtpUser';
UPDATE public.e_preference_descriptions SET description = 'Attacher un fichier iCal aux emails générés.' WHERE parameter = 'com.entelience.esis.feature.attachCalendarFile';
UPDATE public.e_preference_descriptions SET description = 'Mot de passe SMTP.' WHERE parameter = 'com.entelience.mail.MailHelper.smtpPassword';
UPDATE public.e_preference_descriptions SET description = 'Nombre d''essais avant l''échec de l''envoi d''un email.' WHERE parameter = 'com.entelience.mail.MailHelper.maxTries';
UPDATE public.e_preference_descriptions SET description = 'Nombre d''emails maximum à envoyer par lot.' WHERE parameter = 'com.entelience.mail.MailHelper.maxEmailSentAtOnce';
UPDATE public.e_preference_descriptions SET description = 'Chemin vers le logo de l''entreprise.' WHERE parameter = 'com.entelience.mail.MailHelper.iconLocation';
UPDATE public.e_preference_descriptions SET description = 'Durée de la session en minutes.' WHERE parameter = 'com.entelience.soap.SessionHandler.timeoutMinutes';
UPDATE public.e_preference_descriptions SET description = 'Méthode d''authentification.' WHERE parameter = 'com.entelience.soap.soapBase.authMethod';
UPDATE public.e_preference_descriptions SET description = 'Nombre maximum d''élements retournés par une grille de données par défaut.' WHERE parameter = 'com.entelience.esis.maxReturnedRows';
UPDATE public.e_preference_descriptions SET description = 'Base pour l''authetification LDAP.' WHERE parameter = 'com.entelience.soap.auth.LDAP.base';
UPDATE public.e_preference_descriptions SET description = 'Filtre de base pour l''authetification LDAP.' WHERE parameter = 'com.entelience.soap.auth.LDAP.baseFilterString';
UPDATE public.e_preference_descriptions SET description = 'Nom d''utilisateur pour l''authentification LDAP.' WHERE parameter = 'com.entelience.soap.auth.LDAP.userNameField';
UPDATE public.e_preference_descriptions SET description = 'URL pour l''authentification LDAP.' WHERE parameter = 'com.entelience.soap.auth.LDAP.url';
UPDATE public.e_preference_descriptions SET description = 'Search user name pour l''authentification LDAP.' WHERE parameter = 'com.entelience.soap.auth.LDAP.searchUserName';
UPDATE public.e_preference_descriptions SET description = 'Mot de passe pour l''authentification LDAP.' WHERE parameter = 'com.entelience.soap.auth.LDAP.searchPassword';
UPDATE public.e_preference_descriptions SET description = 'Agent utilisateur pour le protocol HTTP.' WHERE parameter = 'com.entelience.util.HttpHelper.userAgent';
UPDATE public.e_preference_descriptions SET description = 'Utilisation d''un proxy pour la connexion HTTP.' WHERE parameter = 'com.entelience.util.HttpHelper.useProxy';
UPDATE public.e_preference_descriptions SET description = 'Nom d''hôte du proxy HTTP.' WHERE parameter = 'com.entelience.util.HttpHelper.proxyHost';
UPDATE public.e_preference_descriptions SET description = 'Port du proxy HTTP.' WHERE parameter = 'com.entelience.util.HttpHelper.proxyPort';
UPDATE public.e_preference_descriptions SET description = 'Utilisation d''une authentification pour le proxy HTTP.' WHERE parameter = 'com.entelience.util.HttpHelper.useProxyAuth';
UPDATE public.e_preference_descriptions SET description = 'Realm authentification pour le proxy HTTP.' WHERE parameter = 'com.entelience.util.HttpHelper.proxyRealm';
UPDATE public.e_preference_descriptions SET description = 'Scheme authentification pour le proxy HTTP.' WHERE parameter = 'com.entelience.util.HttpHelper.proxyScheme';
UPDATE public.e_preference_descriptions SET description = 'Nom d''utilisateur pour le proxy HTTP.' WHERE parameter = 'com.entelience.util.HttpHelper.proxyUserName';
UPDATE public.e_preference_descriptions SET description = 'Mot de passe pour le proxy HTTP.' WHERE parameter = 'com.entelience.util.HttpHelper.proxyPassword';
UPDATE public.e_preference_descriptions SET description = 'Agent utilisateur pour le protocol HTTPS.' WHERE parameter = 'com.entelience.util.HttpSslHelper.userAgent';
UPDATE public.e_preference_descriptions SET description = 'Utilisation d''un proxy pour la connexion HTTPS.' WHERE parameter = 'com.entelience.util.HttpSslHelper.useProxy';
UPDATE public.e_preference_descriptions SET description = 'Nom d''hôte du proxy HTTPS.' WHERE parameter = 'com.entelience.util.HttpSslHelper.proxyHost';
UPDATE public.e_preference_descriptions SET description = 'Port du proxy HTTPS.' WHERE parameter = 'com.entelience.util.HttpSslHelper.proxyPort';
UPDATE public.e_preference_descriptions SET description = 'Utilisation d''une authentification pour le proxy HTTPS.' WHERE parameter = 'com.entelience.util.HttpSslHelper.useProxyAuth';
UPDATE public.e_preference_descriptions SET description = 'Realm authentification pour le proxy HTTPS.' WHERE parameter = 'com.entelience.util.HttpSslHelper.proxyRealm';
UPDATE public.e_preference_descriptions SET description = 'Scheme authentification pour le proxy HTTPS.' WHERE parameter = 'com.entelience.util.HttpSslHelper.proxyScheme';
UPDATE public.e_preference_descriptions SET description = 'Nom d''utilisateur du proxy HTTPS.' WHERE parameter = 'com.entelience.util.HttpSslHelper.proxyUserName';
UPDATE public.e_preference_descriptions SET description = 'Mot de passe du proxy HTTPS.' WHERE parameter = 'com.entelience.util.HttpSslHelper.proxyPassword';
UPDATE public.e_preference_descriptions SET description = 'Fichier de certificats (keystore) pour HTTPS.' WHERE parameter = 'com.entelience.util.HttpSslHelper.keyStore';
UPDATE public.e_preference_descriptions SET description = 'Mot de passe pour le fichier de certificats (keystore) pour HTTPS.' WHERE parameter = 'com.entelience.util.HttpSslHelper.keyStorePassword';
UPDATE public.e_preference_descriptions SET description = 'Répertoire public pour l''authentification des licences.' WHERE parameter = 'com.entelience.license.LicenseHelper.publicStore';
UPDATE public.e_preference_descriptions SET description = 'RACI mode strict.' WHERE parameter = 'com.entelience.raci.strict_RACI';
UPDATE public.e_preference_descriptions SET description = 'Niveau CNIL.' WHERE parameter = 'com.entelience.esis.cnilLevel';
UPDATE public.e_preference_descriptions SET description = 'Chemin du répertoir contenant les fichiers log.' WHERE parameter = 'com.entelience.esis.logDirectory';
UPDATE public.e_preference_descriptions SET description = 'Chemin vers le XML de définition des sondes.' WHERE parameter = 'com.entelience.esis.probeXmlFile';
UPDATE public.e_preference_descriptions SET description = 'Période maximale par défaut pour vérifier l''exécution des sondes.' WHERE parameter = 'com.entelience.probes.showProbeSnailOnLastNDays';
UPDATE public.e_preference_descriptions SET description = 'Les utilisateurs peuvent éditer leurs expertises propres.' WHERE parameter = 'com.entelience.module.Admin.can_edit_its_own_expertises';
UPDATE public.e_preference_descriptions SET description = 'Activation de la notification par email.' WHERE parameter = 'com.entelience.esis.feature.notifyMail';
UPDATE public.e_preference_descriptions SET description = 'Activation de la notification par email pour sa propre adresse email.' WHERE parameter = 'com.entelience.esis.feature.notifySelfMail';
UPDATE public.e_preference_descriptions SET description = 'Générer des emails HTML.' WHERE parameter = 'com.entelience.esis.feature.attachHtmlMail';
UPDATE public.e_preference_descriptions SET description = 'Envoyer un email lors du changement d''une expertise.' WHERE parameter = 'com.entelience.esis.feature.sendEmailOnExpertiseChange';
UPDATE public.e_preference_descriptions SET description = 'Envoyer un email lors du changement d''une matrice RACI.' WHERE parameter = 'com.entelience.esis.feature.sendEmailOnRACIChange';
UPDATE public.e_preference_descriptions SET description = 'Envoyer un email lorsque un objet, un élément est modifié.' WHERE parameter = 'com.entelience.esis.feature.sendEmailOnObjectModification';
UPDATE public.e_preference_descriptions SET description = 'Envoyer un email lors de la création d''un objet, d''un élément.' WHERE parameter = 'com.entelience.esis.feature.sendEmailOnObjectCreation';
UPDATE public.e_preference_descriptions SET description = 'Niveau de la matrice RACI nécessaire pour recevoir les emails.' WHERE parameter = 'com.entelience.mail.MailHelper.receiveEmailOnChange';
UPDATE public.e_preference_descriptions SET description = 'Retarder les changements de matrice RACI pour vérification.' WHERE parameter = 'com.entelience.raci.delayRaciChangeOnModule';
UPDATE public.e_preference_descriptions SET description = 'Email du support.' WHERE parameter = 'com.entelience.esis.SupportNotifier.supportEmail';
UPDATE public.e_preference_descriptions SET description = 'Activer la notification au support.' WHERE parameter = 'com.entelience.esis.feature.SupportNotifier';
UPDATE public.e_preference_descriptions SET description = 'Adresse DE par défaut dans les emails.' WHERE parameter = 'com.entelience.mail.MailHelper.defaultFromAddress';
UPDATE public.e_preference_descriptions SET description = 'Taille minimale du mot de passe.' WHERE parameter = 'com.entelience.esis.security.minPasswordLength';
UPDATE public.e_preference_descriptions SET description = 'Utiliser les règles de complexité sur les mots de passe.' WHERE parameter = 'com.entelience.esis.security.passwordComplexity';
UPDATE public.e_preference_descriptions SET description = 'Durée de vie maximum d''un mot de passe en jours.' WHERE parameter = 'com.entelience.esis.security.passwordAge';
UPDATE public.e_preference_descriptions SET description = 'Nombre de mot de passe stockés dans l''historique pour chaque utilisateur.' WHERE parameter = 'com.entelience.esis.security.passwordHistory';
UPDATE public.e_preference_descriptions SET description = 'Durée maximale en jours de la dernière connexion utilisateur.' WHERE parameter = 'com.entelience.esis.security.loginHistoryAge';
UPDATE public.e_preference_descriptions SET description = 'Nombre d''échec de connexion utilisateur avant blocage du compte.' WHERE parameter = 'com.entelience.esis.security.numberOfFailedLoginLimit';
UPDATE public.e_preference_descriptions SET description = 'Durée limite en minutes entre échecs de connexion utilisateur.' WHERE parameter = 'com.entelience.esis.security.failedLoginTimeLimit';
UPDATE public.e_preference_descriptions SET description = 'Active le bouton Mot de passe perdu qui permet de recevoir un nouveau mot de passe par email ou si l''utilisateur n''a pas d''email de générer un incident de l''application.' WHERE parameter = 'com.entelience.esis.security.automatedLostPassword';
UPDATE public.e_preference_descriptions SET description = 'Redefinir le premier jour de la semain (ou utiliser le jour par défaut du système).' WHERE parameter = 'com.entelience.provider.calendar.DbCalendar.redefineFirstDayOfWeek';
UPDATE public.e_preference_descriptions SET description = 'Premier jour de la semaine (1=Dimanche,7=Samedi).' WHERE parameter = 'com.entelience.provider.calendar.DbCalendar.firstDayOfWeek';
UPDATE public.e_preference_descriptions SET description = 'Langue de l''application.' WHERE parameter = 'com.entelience.module.Admin.language';
UPDATE public.e_preference_descriptions SET description = 'Les utilisateurs ne peuvent voir un élément que s''ils sont dans la matrice RACI liée.' WHERE parameter = 'com.entelience.module.Audit.user_see_my_only';
UPDATE public.e_preference_descriptions SET description = 'Nombre de reports avant de noter une action comme trop repoussée.' WHERE parameter = 'com.entelience.module.Audit.escaladeActionAfterNDelays';
UPDATE public.e_preference_descriptions SET description = 'Nombre de reports avant de noter une recommandation comme trop repoussée.' WHERE parameter = 'com.entelience.module.Audit.escaladeRecommendationAfterNDelays';
UPDATE public.e_preference_descriptions SET description = 'Masquer les nouveaux produits importés par les sondes.' WHERE parameter = 'com.entelience.esis.feature.hideNewProduct';
UPDATE public.e_preference_descriptions SET description = 'Masquer les nouveaux fournisseurs, vendeurs importés par les sondes.' WHERE parameter = 'com.entelience.esis.feature.hideNewVendor';
UPDATE public.e_preference_descriptions SET description = 'Classe de rapport chargée pour obtenir les métriques.' WHERE parameter = 'com.entelience.soap.soapIdentityManagement.IMReportClassName';
UPDATE public.e_preference_descriptions SET description = 'Pourcentage entre métrique et cible sous lequel le métrique est considéré comme bon.' WHERE parameter = 'com.entelience.esis.im.snail_colors.percent_low';
UPDATE public.e_preference_descriptions SET description = 'Pourcentage entre métrique et cible sous lequel le métrique est considéré comme assez bon.' WHERE parameter = 'com.entelience.esis.im.snail_colors.percent_medium';
UPDATE public.e_preference_descriptions SET description = 'Pourcentage entre métrique et cible sous lequel le métrique est considéré comme moyen.' WHERE parameter = 'com.entelience.esis.im.snail_colors.percent_high';
UPDATE public.e_preference_descriptions SET description = 'Pourcentage entre métrique et cible sous lequel le métrique est considéré comme mauvais.' WHERE parameter = 'com.entelience.esis.im.snail_colors.percent_bad';
UPDATE public.e_preference_descriptions SET description = 'Nombre moyen de requêtes (hits) par page.' WHERE parameter = 'com.entelience.http.average_hits_per_page';
UPDATE public.e_preference_descriptions SET description = 'Temps moyen passé sur une page en secondes.' WHERE parameter = 'com.entelience.http.average_time_spent_per_page';
UPDATE public.e_preference_descriptions SET description = 'Nombre de données sur l''axe Y pour les graphiques en lignes.' WHERE parameter = 'com.entelience.module.Portal.numberOfGridsInChart';
UPDATE public.e_preference_descriptions SET description = 'Afficher les valeurs à partir de 0 dans les graphiques en lignes.' WHERE parameter = 'com.entelience.module.Portal.gridFrom0';
UPDATE public.e_preference_descriptions SET description = 'Afficher les catégories Internet ignorées dans les listes.' WHERE parameter = 'com.entelience.module.Portal.ignoredCategories';
UPDATE public.e_preference_descriptions SET description = 'Afficher la partie Autres données dans les graphiques camemberts.' WHERE parameter = 'com.entelience.module.Portal.show_others_in_pie';
UPDATE public.e_preference_descriptions SET description = 'Les utilisateurs ne peuvent voir un élément que s''ils sont dans la matrice RACI liée.' WHERE parameter = 'com.entelience.module.RiskAssessment.user_see_my_only';
UPDATE public.e_preference_descriptions SET description = 'Les utilisateurs ne peuvent voir un élément que s''ils sont dans la matrice RACI liée.' WHERE parameter = 'com.entelience.module.RiskModelisation.user_see_my_only';
UPDATE public.e_preference_descriptions SET description = 'Une vulnérabilité peut être corrigée (ou non-corrigée) que si toutes ses actions sont dans un statut corrigé (ou non-corrigé).' WHERE parameter = 'com.entelience.esis.vrt.actions.actions_fixed_before_vuln_fixed';
UPDATE public.e_preference_descriptions SET description = 'La décision appliquée à une vulnérabilité peut être modifiée même dans un regroupement de vulnérabilité fermé.' WHERE parameter = 'com.entelience.esis.vrt.closed_vrt_vuln_can_change_decision';
UPDATE public.e_preference_descriptions SET description = 'Les utilisateurs ne peuvent voir un élément que s''ils sont dans la matrice RACI liée.' WHERE parameter = 'com.entelience.esis.vrt.user_see_my_only';
UPDATE public.e_preference_descriptions SET description = 'Spécifique à l''écran des nouvelles vulnérabilités: les utilisateurs ne peuvent voir un élément que s''ils sont dans la matrice RACI liée.' WHERE parameter = 'com.entelience.esis.vrt.user_see_my_new_only';
UPDATE public.e_preference_descriptions SET description = 'Seulement actif en mode Vote quand tous les experts doivent voter. C''est le nombre minimal de vote nécessaire pour activer la décision sur une vulnérabilité.' WHERE parameter = 'com.entelience.esis.vrt.vote_ignore_decision_ceiling';
UPDATE public.e_preference_descriptions SET description = 'Activation du mode Vote pour trier les vulnérabilités et les regrouper.' WHERE parameter = 'com.entelience.esis.vrt.vote_instead_of_decision';
UPDATE public.e_preference_descriptions SET description = 'Activation du mode Vote Simplifié: dès le premier vote la vulnérabilité est placée dans un regroupement existant et peut recevoir des votes jusqu''à son analyse. Note: une action est générée pour chaque vote sur une vulnérabilité. La vulnérabilité peut être analysée même si son regroupement n''a pas été démarré. La décision appliquée à la vulnérabilité est automatiquement mise en réparation ou ignorée en fonction du type de vote.' WHERE parameter = 'com.entelience.esis.vrt.simplifiedVRTProcess';
UPDATE public.e_preference_descriptions SET description = 'La décision des vulnérabilités votées peut être modifiée.' WHERE parameter = 'com.entelience.esis.vrt.votesBasedDecision';
UPDATE public.e_preference_descriptions SET description = 'Décision par défaut utilisée pour une vulnérabilité recevant ignoré en vote (table vuln.e_vulnerability_status).' WHERE parameter = 'com.entelience.esis.vrt.votesBasedDecision.IgnoredDecision';
UPDATE public.e_preference_descriptions SET description = 'Décision par défaut utilisée pour une vulnérabilité ajoutée à un regroupement suite à un vote (table vuln.e_vulnerability_status).' WHERE parameter = 'com.entelience.esis.vrt.votesBasedDecision.AddDecision';
UPDATE public.e_preference_descriptions SET description = 'Seulement actif en mode Vote. Seuls les experts pour cette vulnérabilité peuvent voter.' WHERE parameter = 'com.entelience.esis.vrt.only_experts_can_vote';
UPDATE public.e_preference_descriptions SET description = 'Seulement actif en mode Vote. Une vulnérabilité peut recevoir des votes jusqu''à son analyse.' WHERE parameter = 'com.entelience.esis.vrt.can_vote_until_analysis';
UPDATE public.e_preference_descriptions SET description = 'Le membre d''un département de l''entreprise expert pour un type de vulnérabilité evite aux autres membres de voter.' WHERE parameter = 'com.entelience.esis.vrt.oneVotePerExpertDepartment';
UPDATE public.e_preference_descriptions SET description = 'Création d''une action lors d''un vote (ou d''un tri) sur une vulnérabilité.' WHERE parameter = 'com.entelience.esis.vrt.createActionOnTriage';
UPDATE public.e_preference_descriptions SET description = 'Lorsqu''une vulnérabilité est ignorée, l''utilisateur doit commenter son action.' WHERE parameter = 'com.entelience.esis.vrt.commentRequiredOnIgnore';
UPDATE public.e_preference_descriptions SET description = 'Le tri d''une vulnerabilité réouverte change sa décision.' WHERE parameter = 'com.entelience.esis.vrt.triageOnRenewedVulnOutdoHigherDecision';
UPDATE public.e_preference_descriptions SET description = 'Modèle d''URL pour accéder à la version web des données de vulnérabilités SecurityFocus.' WHERE parameter = 'com.entelience.provider.vrt.url.securityfocus';
UPDATE public.e_preference_descriptions SET description = 'Modèle d''URL pour accéder à la version web des données de vulnérabilités Microsoft.' WHERE parameter = 'com.entelience.provider.vrt.url.microsoft';
UPDATE public.e_preference_descriptions SET description = 'Modèle d''URL pour accéder à la version web des données de vulnérabilités NVD.' WHERE parameter = 'com.entelience.provider.vrt.url.nist';
UPDATE public.e_preference_descriptions SET description = 'Modèle d''URL pour accéder à la version web des données de vulnérabilités Cert-IST.' WHERE parameter = 'com.entelience.provider.vrt.url.certist';
UPDATE public.e_preference_descriptions SET description = 'Emails envoyés aux experts concernés par des nouvelles vulnérabiltés.' WHERE parameter = 'com.entelience.esis.feature.notifyNewVulnsForExperts';
