UPDATE public.e_probe_category SET name = 'Applications' WHERE e_probe_category_id = 1;
UPDATE public.e_probe_category SET name = 'Outils informatiques' WHERE e_probe_category_id = 2;
UPDATE public.e_probe_category SET name = 'Audits' WHERE e_probe_category_id = 3;
UPDATE public.e_probe_category SET name = 'Conformité' WHERE e_probe_category_id = 4;
UPDATE public.e_probe_category SET name = 'Web' WHERE e_probe_category_id = 5;
UPDATE public.e_probe_category SET name = 'Opérations TI' WHERE e_probe_category_id = 6;
UPDATE public.e_probe_category SET name = 'TI de gestion de service' WHERE e_probe_category_id = 7;
UPDATE public.e_probe_category SET name = 'Spam et e-mail' WHERE e_probe_category_id = 8;
UPDATE public.e_probe_category SET name = 'Identités' WHERE e_probe_category_id = 9;
UPDATE public.e_probe_category SET name = 'Evènements réseau' WHERE e_probe_category_id = 10;
UPDATE public.e_probe_category SET name = 'Vulnérabilités' WHERE e_probe_category_id = 11;
UPDATE public.e_probe_category SET name = 'Outils utilisateurs' WHERE e_probe_category_id = 12;
UPDATE public.e_probe_category SET name = 'Logiciels malveillants' WHERE e_probe_category_id = 13;
UPDATE public.e_probe_category SET name = 'Messagerie instantannée' WHERE e_probe_category_id = 14;
