UPDATE asset.e_asset_type SET name = 'Cluster' WHERE id = 1;
UPDATE asset.e_asset_type SET name = 'Serveur' WHERE id = 2;
UPDATE asset.e_asset_type SET name = 'Serveur applicatif' WHERE id = 3;
UPDATE asset.e_asset_type SET name = 'Routeur' WHERE id = 4;
UPDATE asset.e_asset_type SET name = 'Machine réseau' WHERE id = 5;
UPDATE asset.e_asset_type SET name = 'Machine sécurité' WHERE id = 6;
UPDATE asset.e_asset_type SET name = 'Périphérique d''accès' WHERE id = 7;
UPDATE asset.e_asset_type SET name = 'Périphérique d''accès mobile' WHERE id = 8;
UPDATE asset.e_asset_type SET name = 'Imprimante' WHERE id = 9;
UPDATE asset.e_sc SET name = 'Critique pour l''entreprise' WHERE id = 1;
UPDATE asset.e_sc SET name = 'Nécessaire pour l''entreprise' WHERE id = 2;
UPDATE asset.e_sc SET name = 'Pour l''entreprise' WHERE id = 3;
UPDATE asset.e_sc SET name = 'Support pour l''entreprise' WHERE id = 4;
UPDATE asset.e_sc SET name = 'Infrastructure' WHERE id = 5;
UPDATE asset.e_sc SET name = 'Non critique pour l''entreprise' WHERE id = 6;
UPDATE asset.e_sc SET name = 'Non lié à l''entreprise' WHERE id = 7;
UPDATE asset.e_bl SET name = 'TI' WHERE id = 1;
UPDATE asset.e_bl SET name = 'Corporate' WHERE id = 2;
UPDATE asset.e_bl SET name = 'Ventes' WHERE id = 3;
UPDATE asset.e_bl SET name = 'Marketing' WHERE id = 4;
UPDATE asset.e_bl SET name = 'R&D' WHERE id = 5;
UPDATE asset.e_bl SET name = 'Production' WHERE id = 6;
UPDATE asset.e_bl SET name = 'Comptabilité' WHERE id = 7;
UPDATE asset.e_bl SET name = 'Financement' WHERE id = 8;
UPDATE asset.e_bl SET name = 'Domaines' WHERE id = 9;
UPDATE asset.e_bl SET name = 'Partenaires de travail' WHERE id = 10;
UPDATE asset.e_availability SET name = 'Ininterrompu' WHERE id = 1;
UPDATE asset.e_availability SET name = 'Haute disponibilité' WHERE id = 2;
UPDATE asset.e_availability SET name = '99%' WHERE id = 3;
UPDATE asset.e_availability SET name = 'Horaires de travail' WHERE id = 4;
UPDATE asset.e_availability SET name = 'Meilleur effort' WHERE id = 5;

UPDATE audit.e_audit_rec_status SET rec_status = 'Ouvert' WHERE e_audit_rec_status_id = 1;
UPDATE audit.e_audit_rec_status SET rec_status = 'Fermé' WHERE e_audit_rec_status_id = 2;
UPDATE audit.e_audit_rec_status SET rec_status = 'Risque accepté' WHERE e_audit_rec_status_id = 3;
UPDATE audit.e_audit_rec_status SET rec_status = 'Dupliqué' WHERE e_audit_rec_status_id = 4;
UPDATE audit.e_audit_severity SET severity = 'Faible' WHERE e_audit_severity_id = 1;
UPDATE audit.e_audit_severity SET severity = 'Moyenne' WHERE e_audit_severity_id = 2;
UPDATE audit.e_audit_severity SET severity = 'Elevée' WHERE e_audit_severity_id = 3;
UPDATE audit.e_audit_topic SET topic = 'Sécurité réseau' WHERE e_audit_topic_id = 1;
UPDATE audit.e_audit_topic SET topic = 'Sûrété physique' WHERE e_audit_topic_id = 2;
UPDATE audit.e_audit_topic SET topic = 'Sécurité système' WHERE e_audit_topic_id = 3;
UPDATE audit.e_audit_topic SET topic = 'Accès' WHERE e_audit_topic_id = 4;
UPDATE audit.e_audit_topic SET topic = 'Applications' WHERE e_audit_topic_id = 5;
UPDATE audit.e_audit_topic SET topic = 'Business' WHERE e_audit_topic_id = 6;
UPDATE audit.e_audit_topic SET topic = 'Autres' WHERE e_audit_topic_id = 7;
UPDATE audit.e_audit_origin SET origin = 'Audit interne' WHERE e_audit_origin_id = 1;
UPDATE audit.e_audit_origin SET origin = 'Audit externe' WHERE e_audit_origin_id = 2;
UPDATE audit.e_audit_origin SET origin = 'Régulateurs' WHERE e_audit_origin_id = 3;
UPDATE audit.e_audit_origin SET origin = 'Auto-audit' WHERE e_audit_origin_id = 4;
UPDATE audit.e_audit_action_status SET action_status = 'Planifié' WHERE e_audit_action_status_id = 1;
UPDATE audit.e_audit_action_status SET action_status = 'En cours' WHERE e_audit_action_status_id = 2;
UPDATE audit.e_audit_action_status SET action_status = 'Finalisé' WHERE e_audit_action_status_id = 3;
UPDATE audit.e_audit_action_status SET action_status = 'Annulé' WHERE e_audit_action_status_id = 4;
UPDATE audit.e_audit_action_status SET action_status = 'En pause' WHERE e_audit_action_status_id = 5;
UPDATE audit.e_audit_priority SET priority = 'Faible' WHERE e_audit_priority_id = 1;
UPDATE audit.e_audit_priority SET priority = 'Moyenne' WHERE e_audit_priority_id = 2;
UPDATE audit.e_audit_priority SET priority = 'Elevée' WHERE e_audit_priority_id = 3;
UPDATE audit.e_audit_rec_topic SET topic = 'Accès' WHERE e_audit_rec_topic_id = 1;
UPDATE audit.e_audit_rec_topic SET topic = 'Réseau' WHERE e_audit_rec_topic_id = 2;
UPDATE audit.e_audit_rec_topic SET topic = 'Locaux' WHERE e_audit_rec_topic_id = 3;
UPDATE audit.e_audit_rec_topic SET topic = 'Gestion' WHERE e_audit_rec_topic_id = 4;
UPDATE audit.e_audit_rec_topic SET topic = 'Globale' WHERE e_audit_rec_topic_id = 5;
UPDATE audit.e_audit_rec_topic SET topic = 'Veille' WHERE e_audit_rec_topic_id = 6;
UPDATE audit.e_audit_rec_topic SET topic = 'Connaissances' WHERE e_audit_rec_topic_id = 7;
UPDATE audit.e_audit_confidentiality SET confidentiality = 'Interne' WHERE e_audit_confidentiality_id = 1;
UPDATE audit.e_audit_confidentiality SET confidentiality = 'Confidentiel' WHERE e_audit_confidentiality_id = 2;
UPDATE audit.e_audit_confidentiality SET confidentiality = 'Responsable seul' WHERE e_audit_confidentiality_id = 3;
UPDATE audit.e_audit_confidentiality SET confidentiality = 'Secret d''entreprise' WHERE e_audit_confidentiality_id = 4;
UPDATE audit.e_audit_status SET status = 'Planifié' WHERE e_audit_status_id = 1;
UPDATE audit.e_audit_status SET status = 'Prestations' WHERE e_audit_status_id = 2;
UPDATE audit.e_audit_status SET status = 'Entretiens' WHERE e_audit_status_id = 3;
UPDATE audit.e_audit_status SET status = 'Réunion d''ouverture' WHERE e_audit_status_id = 4;
UPDATE audit.e_audit_status SET status = 'Premier rapport' WHERE e_audit_status_id = 5;
UPDATE audit.e_audit_status SET status = 'Rapport final' WHERE e_audit_status_id = 6;
UPDATE audit.e_audit_status SET status = 'Réunion de clôture' WHERE e_audit_status_id = 7;
UPDATE audit.e_audit_status SET status = 'Remédiation' WHERE e_audit_status_id = 8;
UPDATE audit.e_audit_status SET status = 'Fermé' WHERE e_audit_status_id = 9;
UPDATE audit.e_audit_report_status SET report_status = 'Ebauche' WHERE e_audit_report_status_id = 1;
UPDATE audit.e_audit_report_status SET report_status = 'Finalisé' WHERE e_audit_report_status_id = 2;
UPDATE audit.e_audit_report_status SET report_status = 'Approuvé' WHERE e_audit_report_status_id = 3;
UPDATE audit.e_audit_report_status SET report_status = 'Publié' WHERE e_audit_report_status_id = 4;
UPDATE audit.e_audit_document_type SET document_type = 'Preuve' WHERE e_audit_document_type_id = 1;
UPDATE audit.e_audit_document_type SET document_type = 'Information' WHERE e_audit_document_type_id = 2;
UPDATE audit.e_audit_document_type SET document_type = 'Email' WHERE e_audit_document_type_id = 3;
UPDATE audit.e_audit_document_type SET document_type = 'Document' WHERE e_audit_document_type_id = 4;

UPDATE compliance.e_standard_category SET standard_category = 'Technologies de l''information' WHERE e_standard_category_id = 1;
UPDATE compliance.e_standard_category SET standard_category = 'Gestion globale' WHERE e_standard_category_id = 2;
UPDATE compliance.e_topic_category SET topic_category = 'Gestion de la sécurité' WHERE e_topic_category_id = 1;
UPDATE compliance.e_topic_category SET topic_category = 'Contrôle des accès' WHERE e_topic_category_id = 2;
UPDATE compliance.e_compliance_kind SET kind = 'Remarque d''application' WHERE e_compliance_kind_id = 1;
UPDATE compliance.e_compliance_kind SET kind = 'Remarque documentaire' WHERE e_compliance_kind_id = 2;
UPDATE compliance.e_compliance_type SET compliance_type = 'Non conformité mineure d''une application' WHERE e_compliance_type_id = 1;
UPDATE compliance.e_compliance_type SET compliance_type = 'Non conformité mineure documentaire' WHERE e_compliance_type_id = 2;
UPDATE compliance.e_compliance_type SET compliance_type = 'Non conformité majeure d''une application' WHERE e_compliance_type_id = 3;
UPDATE compliance.e_compliance_type SET compliance_type = 'Non conformité majeure documentaire' WHERE e_compliance_type_id = 4;

UPDATE mim.t_user_anomaly SET description = 'None' WHERE t_user_anomaly_id = 1;
UPDATE mim.t_user_anomaly SET description = 'Fudge : mainframe data missing' WHERE t_user_anomaly_id = 2;
UPDATE mim.t_user_anomaly SET description = 'Fudge : mainframe date security admin missing' WHERE t_user_anomaly_id = 3;
UPDATE mim.t_user_anomaly SET description = 'Fudge : mainframe datecontractvalidity abnormal' WHERE t_user_anomaly_id = 4;
UPDATE mim.t_user_anomaly SET description = 'Fudge : mainframe date1sthire bad' WHERE t_user_anomaly_id = 5;
UPDATE mim.t_user_anomaly SET description = 'Fudge : mainframe ou bad' WHERE t_user_anomaly_id = 6;
UPDATE mim.t_user_anomaly SET description = 'Fudge : mainframe l bad' WHERE t_user_anomaly_id = 7;
UPDATE mim.t_user_anomaly SET description = 'Fudge : ad data missing' WHERE t_user_anomaly_id = 8;
UPDATE mim.t_user_anomaly SET description = 'Fudge : ad date is 0' WHERE t_user_anomaly_id = 9;
UPDATE mim.t_user_anomaly SET description = 'Fudge : hr data missing' WHERE t_user_anomaly_id = 10;
UPDATE mim.t_user_anomaly SET description = 'Fudge : hr logoncount missing' WHERE t_user_anomaly_id = 11;
UPDATE mim.t_user_anomaly SET description = 'Fudge : hr still has 19000000 as dates' WHERE t_user_anomaly_id = 12;
UPDATE mim.t_user_anomaly SET description = 'Fudge : hr still has 19800101 as dates' WHERE t_user_anomaly_id = 13;

UPDATE itops.t_alert_severity SET severity_name = 'Information' WHERE t_alert_severity_id = 1;
UPDATE itops.t_alert_severity SET severity_name = 'Avertissement' WHERE t_alert_severity_id = 2;
UPDATE itops.t_alert_severity SET severity_name = 'Critique' WHERE t_alert_severity_id = 3;
UPDATE itops.t_alert_priority SET priority_name = 'Bas' WHERE t_alert_priority_id = 1;
UPDATE itops.t_alert_priority SET priority_name = 'Moyen' WHERE t_alert_priority_id = 2;
UPDATE itops.t_alert_priority SET priority_name = 'Haut' WHERE t_alert_priority_id = 3;
UPDATE itops.t_event_level SET event_level = 'Succès' WHERE t_event_level_id = 1;
UPDATE itops.t_event_level SET event_level = 'Erreur' WHERE t_event_level_id = 2;
UPDATE itops.t_event_level SET event_level = 'Avertissement' WHERE t_event_level_id = 3;
UPDATE itops.t_event_level SET event_level = 'Information' WHERE t_event_level_id = 4;
UPDATE itops.t_event_level SET event_level = 'Succès de l''audit' WHERE t_event_level_id = 5;
UPDATE itops.t_event_level SET event_level = 'Echec de l''audit' WHERE t_event_level_id = 6;

UPDATE itsm.t_status SET status_name = 'Nouveau' WHERE t_status_id = 1;
UPDATE itsm.t_status SET status_name = 'En cours' WHERE t_status_id = 2;
UPDATE itsm.t_status SET status_name = 'Annulé' WHERE t_status_id = 3;
UPDATE itsm.t_status SET status_name = 'Corrigé' WHERE t_status_id = 4;
UPDATE itsm.t_status SET status_name = 'Non corrigé' WHERE t_status_id = 5;
UPDATE itsm.t_status SET status_name = 'Clos' WHERE t_status_id = 6;
UPDATE itsm.t_ipsu SET ipsu_name = 'Non bloquant' WHERE t_ipsu_id = 1;
UPDATE itsm.t_ipsu SET ipsu_name = 'Individuel' WHERE t_ipsu_id = 2;
UPDATE itsm.t_ipsu SET ipsu_name = 'Groupe' WHERE t_ipsu_id = 3;
UPDATE itsm.t_ipsu SET ipsu_name = 'Basse' WHERE t_ipsu_id = 11;
UPDATE itsm.t_ipsu SET ipsu_name = 'Moyenne' WHERE t_ipsu_id = 12;
UPDATE itsm.t_ipsu SET ipsu_name = 'Haute' WHERE t_ipsu_id = 13;
UPDATE itsm.t_ipsu SET ipsu_name = 'Basse' WHERE t_ipsu_id = 21;
UPDATE itsm.t_ipsu SET ipsu_name = 'Moyenne' WHERE t_ipsu_id = 22;
UPDATE itsm.t_ipsu SET ipsu_name = 'Haute' WHERE t_ipsu_id = 23;
UPDATE itsm.t_ipsu SET ipsu_name = 'Normal' WHERE t_ipsu_id = 31;
UPDATE itsm.t_ipsu SET ipsu_name = 'Urgent' WHERE t_ipsu_id = 32;
UPDATE itsm.t_ipsu SET ipsu_name = 'Immédiat' WHERE t_ipsu_id = 33;
UPDATE itsm.t_satisfaction_level SET satisfaction_level = 'Très élevé' WHERE t_satisfaction_level_id = 1;
UPDATE itsm.t_satisfaction_level SET satisfaction_level = 'Elevé' WHERE t_satisfaction_level_id = 2;
UPDATE itsm.t_satisfaction_level SET satisfaction_level = 'Moyen' WHERE t_satisfaction_level_id = 3;
UPDATE itsm.t_satisfaction_level SET satisfaction_level = 'Bas' WHERE t_satisfaction_level_id = 4;

UPDATE public.e_file_states SET state_name = 'Abandon, données incohérentes' WHERE id = -4;
UPDATE public.e_file_states SET state_name = 'Abandon' WHERE id = -3;
UPDATE public.e_file_states SET state_name = 'Téléchargement' WHERE id = -2;
UPDATE public.e_file_states SET state_name = 'En cours' WHERE id = -1;
UPDATE public.e_file_states SET state_name = 'Prêt' WHERE id = 0;
UPDATE public.e_file_states SET state_name = 'Réussite' WHERE id = 1;
UPDATE public.e_file_states SET state_name = 'Echec à reéssayer' WHERE id = 2;
UPDATE public.e_file_states SET state_name = 'Echec permanent' WHERE id = 3;
UPDATE public.e_file_states SET state_name = 'Ignoré' WHERE id = 4;
UPDATE public.e_file_states SET state_name = 'Remplacé' WHERE id = 5;
UPDATE public.e_file_states SET state_name = 'Dupliqué' WHERE id = 6;
UPDATE public.e_file_states SET state_name = 'Réussite + Archivé' WHERE id = 7;
UPDATE public.e_file_states SET state_name = 'Remplacé + Archivé' WHERE id = 8;
UPDATE public.e_file_states SET state_name = 'Dupliqué + Archivé' WHERE id = 9;
UPDATE public.e_file_states SET state_name = 'Echec permanent + Archivé' WHERE id = 10;
UPDATE public.e_file_states SET state_name = 'Ignoré + Archivé' WHERE id = 11;
UPDATE public.e_probe_parameter_origin SET origin = 'Valeur par défaut' WHERE e_probe_parameter_origin_id = 1;
UPDATE public.e_probe_parameter_origin SET origin = 'Base de données' WHERE e_probe_parameter_origin_id = 2;
UPDATE public.e_probe_parameter_origin SET origin = 'Fichier XML' WHERE e_probe_parameter_origin_id = 3;
UPDATE public.e_probe_run_status SET status_name = 'Jamais lancée' WHERE e_probe_run_status_id = 0;
UPDATE public.e_probe_run_status SET status_name = 'Succes' WHERE e_probe_run_status_id = 1;
UPDATE public.e_probe_run_status SET status_name = 'Pas de données importées' WHERE e_probe_run_status_id = 2;
UPDATE public.e_probe_run_status SET status_name = 'Annulée' WHERE e_probe_run_status_id = 3;
UPDATE public.e_probe_run_status SET status_name = 'Echouée' WHERE e_probe_run_status_id = 4;
UPDATE public.e_probe_run_status SET status_name = 'Erreur' WHERE e_probe_run_status_id = 5;
UPDATE public.e_probe_run_status SET status_name = 'En cours d''exécution' WHERE e_probe_run_status_id = 6;
UPDATE public.e_probe_run_status SET status_name = 'Annulée avec erreur' WHERE e_probe_run_status_id = 7;

UPDATE public.e_probe_category SET name = 'Applications' WHERE e_probe_category_id = 1;
UPDATE public.e_probe_category SET name = 'Outils informatiques' WHERE e_probe_category_id = 2;
UPDATE public.e_probe_category SET name = 'Audits' WHERE e_probe_category_id = 3;
UPDATE public.e_probe_category SET name = 'Conformité' WHERE e_probe_category_id = 4;
UPDATE public.e_probe_category SET name = 'Web' WHERE e_probe_category_id = 5;
UPDATE public.e_probe_category SET name = 'Opérations TI' WHERE e_probe_category_id = 6;
UPDATE public.e_probe_category SET name = 'TI de gestion de service' WHERE e_probe_category_id = 7;
UPDATE public.e_probe_category SET name = 'Spam et e-mail' WHERE e_probe_category_id = 8;
UPDATE public.e_probe_category SET name = 'Identités' WHERE e_probe_category_id = 9;
UPDATE public.e_probe_category SET name = 'Evènements réseau' WHERE e_probe_category_id = 10;
UPDATE public.e_probe_category SET name = 'Vulnérabilités' WHERE e_probe_category_id = 11;
UPDATE public.e_probe_category SET name = 'Outils utilisateurs' WHERE e_probe_category_id = 12;
UPDATE public.e_probe_category SET name = 'Logiciels malveillants' WHERE e_probe_category_id = 13;
UPDATE public.e_probe_category SET name = 'Messagerie instantannée' WHERE e_probe_category_id = 14;

UPDATE asset.e_product_type SET name = 'Logiciel' WHERE id = 1;
UPDATE asset.e_product_type SET name = 'Matériel' WHERE id = 2;
UPDATE asset.e_product_type SET name = 'Appareil' WHERE id = 3;
UPDATE asset.e_preferred_relationship SET name = 'Associé stratégique' WHERE id = 1;
UPDATE asset.e_preferred_relationship SET name = 'Associé' WHERE id = 2;
UPDATE asset.e_preferred_relationship SET name = 'Fournisseur' WHERE id = 3;
UPDATE asset.e_preferred_relationship SET name = 'Pas de relation' WHERE id = 4;

UPDATE public.e_preference_descriptions SET description = 'Répertoire principal.' WHERE parameter = 'com.entelience.esis.rootDir';
UPDATE public.e_preference_descriptions SET description = 'Répertoire des erreurs concernant les fichiers incorrects.' WHERE parameter = 'com.entelience.esis.errorsDir';
UPDATE public.e_preference_descriptions SET description = 'Taille maximale du répertoire des erreurs.' WHERE parameter = 'com.entelience.esis.errorsSize';
UPDATE public.e_preference_descriptions SET description = 'Répertoire de stockage des rapports.' WHERE parameter = 'com.entelience.esis.reportsDir';
UPDATE public.e_preference_descriptions SET description = 'Nom d''entreprise par défaut.' WHERE parameter = 'com.entelience.esis.defaultCompany';
UPDATE public.e_preference_descriptions SET description = 'Chemin vers le logo poweredBy.' WHERE parameter = 'com.entelience.esis.poweredByLogo';
UPDATE public.e_preference_descriptions SET description = 'Port de Tomcat.' WHERE parameter = 'com.entelience.esis.web.localServerPort';
UPDATE public.e_preference_descriptions SET description = 'Adresse locale du serveur.' WHERE parameter = 'com.entelience.esis.web.localServerAddress';
UPDATE public.e_preference_descriptions SET description = 'Protocole.' WHERE parameter = 'com.entelience.esis.web.remoteServerProtocol';
UPDATE public.e_preference_descriptions SET description = 'Nom d''hôte du serveur SMTP.' WHERE parameter = 'com.entelience.mail.MailHelper.hostName';
UPDATE public.e_preference_descriptions SET description = 'Port du serveur SMTP.' WHERE parameter = 'com.entelience.mail.MailHelper.hostPort';
UPDATE public.e_preference_descriptions SET description = 'Usage d''une sécurisation (TLS, SSL) sur le serveur SMTP.' WHERE parameter = 'com.entelience.mail.MailHelper.useTls';
UPDATE public.e_preference_descriptions SET description = 'Usage d''une authentification sur le serveur SMTP.' WHERE parameter = 'com.entelience.mail.MailHelper.useAuth';
UPDATE public.e_preference_descriptions SET description = 'Utilisateur SMTP.' WHERE parameter = 'com.entelience.mail.MailHelper.smtpUser';
UPDATE public.e_preference_descriptions SET description = 'Attacher un fichier iCal aux emails générés.' WHERE parameter = 'com.entelience.esis.feature.attachCalendarFile';
UPDATE public.e_preference_descriptions SET description = 'Mot de passe SMTP.' WHERE parameter = 'com.entelience.mail.MailHelper.smtpPassword';
UPDATE public.e_preference_descriptions SET description = 'Nombre d''essais avant l''échec de l''envoi d''un email.' WHERE parameter = 'com.entelience.mail.MailHelper.maxTries';
UPDATE public.e_preference_descriptions SET description = 'Nombre d''emails maximum à envoyer par lot.' WHERE parameter = 'com.entelience.mail.MailHelper.maxEmailSentAtOnce';
UPDATE public.e_preference_descriptions SET description = 'Chemin vers le logo de l''entreprise.' WHERE parameter = 'com.entelience.mail.MailHelper.iconLocation';
UPDATE public.e_preference_descriptions SET description = 'Durée de la session en minutes.' WHERE parameter = 'com.entelience.soap.SessionHandler.timeoutMinutes';
UPDATE public.e_preference_descriptions SET description = 'Méthode d''authentification.' WHERE parameter = 'com.entelience.soap.soapBase.authMethod';
UPDATE public.e_preference_descriptions SET description = 'Nombre maximum d''élements retournés par une grille de données par défaut.' WHERE parameter = 'com.entelience.esis.maxReturnedRows';
UPDATE public.e_preference_descriptions SET description = 'Base pour l''authetification LDAP.' WHERE parameter = 'com.entelience.soap.auth.LDAP.base';
UPDATE public.e_preference_descriptions SET description = 'Filtre de base pour l''authetification LDAP.' WHERE parameter = 'com.entelience.soap.auth.LDAP.baseFilterString';
UPDATE public.e_preference_descriptions SET description = 'Nom d''utilisateur pour l''authentification LDAP.' WHERE parameter = 'com.entelience.soap.auth.LDAP.userNameField';
UPDATE public.e_preference_descriptions SET description = 'URL pour l''authentification LDAP.' WHERE parameter = 'com.entelience.soap.auth.LDAP.url';
UPDATE public.e_preference_descriptions SET description = 'Search user name pour l''authentification LDAP.' WHERE parameter = 'com.entelience.soap.auth.LDAP.searchUserName';
UPDATE public.e_preference_descriptions SET description = 'Mot de passe pour l''authentification LDAP.' WHERE parameter = 'com.entelience.soap.auth.LDAP.searchPassword';
UPDATE public.e_preference_descriptions SET description = 'Agent utilisateur pour le protocol HTTP.' WHERE parameter = 'com.entelience.util.HttpHelper.userAgent';
UPDATE public.e_preference_descriptions SET description = 'Utilisation d''un proxy pour la connexion HTTP.' WHERE parameter = 'com.entelience.util.HttpHelper.useProxy';
UPDATE public.e_preference_descriptions SET description = 'Nom d''hôte du proxy HTTP.' WHERE parameter = 'com.entelience.util.HttpHelper.proxyHost';
UPDATE public.e_preference_descriptions SET description = 'Port du proxy HTTP.' WHERE parameter = 'com.entelience.util.HttpHelper.proxyPort';
UPDATE public.e_preference_descriptions SET description = 'Utilisation d''une authentification pour le proxy HTTP.' WHERE parameter = 'com.entelience.util.HttpHelper.useProxyAuth';
UPDATE public.e_preference_descriptions SET description = 'Realm authentification pour le proxy HTTP.' WHERE parameter = 'com.entelience.util.HttpHelper.proxyRealm';
UPDATE public.e_preference_descriptions SET description = 'Scheme authentification pour le proxy HTTP.' WHERE parameter = 'com.entelience.util.HttpHelper.proxyScheme';
UPDATE public.e_preference_descriptions SET description = 'Nom d''utilisateur pour le proxy HTTP.' WHERE parameter = 'com.entelience.util.HttpHelper.proxyUserName';
UPDATE public.e_preference_descriptions SET description = 'Mot de passe pour le proxy HTTP.' WHERE parameter = 'com.entelience.util.HttpHelper.proxyPassword';
UPDATE public.e_preference_descriptions SET description = 'Agent utilisateur pour le protocol HTTPS.' WHERE parameter = 'com.entelience.util.HttpSslHelper.userAgent';
UPDATE public.e_preference_descriptions SET description = 'Utilisation d''un proxy pour la connexion HTTPS.' WHERE parameter = 'com.entelience.util.HttpSslHelper.useProxy';
UPDATE public.e_preference_descriptions SET description = 'Nom d''hôte du proxy HTTPS.' WHERE parameter = 'com.entelience.util.HttpSslHelper.proxyHost';
UPDATE public.e_preference_descriptions SET description = 'Port du proxy HTTPS.' WHERE parameter = 'com.entelience.util.HttpSslHelper.proxyPort';
UPDATE public.e_preference_descriptions SET description = 'Utilisation d''une authentification pour le proxy HTTPS.' WHERE parameter = 'com.entelience.util.HttpSslHelper.useProxyAuth';
UPDATE public.e_preference_descriptions SET description = 'Realm authentification pour le proxy HTTPS.' WHERE parameter = 'com.entelience.util.HttpSslHelper.proxyRealm';
UPDATE public.e_preference_descriptions SET description = 'Scheme authentification pour le proxy HTTPS.' WHERE parameter = 'com.entelience.util.HttpSslHelper.proxyScheme';
UPDATE public.e_preference_descriptions SET description = 'Nom d''utilisateur du proxy HTTPS.' WHERE parameter = 'com.entelience.util.HttpSslHelper.proxyUserName';
UPDATE public.e_preference_descriptions SET description = 'Mot de passe du proxy HTTPS.' WHERE parameter = 'com.entelience.util.HttpSslHelper.proxyPassword';
UPDATE public.e_preference_descriptions SET description = 'Fichier de certificats (keystore) pour HTTPS.' WHERE parameter = 'com.entelience.util.HttpSslHelper.keyStore';
UPDATE public.e_preference_descriptions SET description = 'Mot de passe pour le fichier de certificats (keystore) pour HTTPS.' WHERE parameter = 'com.entelience.util.HttpSslHelper.keyStorePassword';
UPDATE public.e_preference_descriptions SET description = 'Répertoire public pour l''authentification des licences.' WHERE parameter = 'com.entelience.license.LicenseHelper.publicStore';
UPDATE public.e_preference_descriptions SET description = 'RACI mode strict.' WHERE parameter = 'com.entelience.raci.strict_RACI';
UPDATE public.e_preference_descriptions SET description = 'Niveau CNIL.' WHERE parameter = 'com.entelience.esis.cnilLevel';
UPDATE public.e_preference_descriptions SET description = 'Chemin du répertoir contenant les fichiers log.' WHERE parameter = 'com.entelience.esis.logDirectory';
UPDATE public.e_preference_descriptions SET description = 'Chemin vers le XML de définition des sondes.' WHERE parameter = 'com.entelience.esis.probeXmlFile';
UPDATE public.e_preference_descriptions SET description = 'Période maximale par défaut pour vérifier l''exécution des sondes.' WHERE parameter = 'com.entelience.probes.showProbeSnailOnLastNDays';
UPDATE public.e_preference_descriptions SET description = 'Les utilisateurs peuvent éditer leurs expertises propres.' WHERE parameter = 'com.entelience.module.Admin.can_edit_its_own_expertises';
UPDATE public.e_preference_descriptions SET description = 'Activation de la notification par email.' WHERE parameter = 'com.entelience.esis.feature.notifyMail';
UPDATE public.e_preference_descriptions SET description = 'Activation de la notification par email pour sa propre adresse email.' WHERE parameter = 'com.entelience.esis.feature.notifySelfMail';
UPDATE public.e_preference_descriptions SET description = 'Générer des emails HTML.' WHERE parameter = 'com.entelience.esis.feature.attachHtmlMail';
UPDATE public.e_preference_descriptions SET description = 'Envoyer un email lors du changement d''une expertise.' WHERE parameter = 'com.entelience.esis.feature.sendEmailOnExpertiseChange';
UPDATE public.e_preference_descriptions SET description = 'Envoyer un email lors du changement d''une matrice RACI.' WHERE parameter = 'com.entelience.esis.feature.sendEmailOnRACIChange';
UPDATE public.e_preference_descriptions SET description = 'Envoyer un email lorsque un objet, un élément est modifié.' WHERE parameter = 'com.entelience.esis.feature.sendEmailOnObjectModification';
UPDATE public.e_preference_descriptions SET description = 'Envoyer un email lors de la création d''un objet, d''un élément.' WHERE parameter = 'com.entelience.esis.feature.sendEmailOnObjectCreation';
UPDATE public.e_preference_descriptions SET description = 'Niveau de la matrice RACI nécessaire pour recevoir les emails.' WHERE parameter = 'com.entelience.mail.MailHelper.receiveEmailOnChange';
UPDATE public.e_preference_descriptions SET description = 'Retarder les changements de matrice RACI pour vérification.' WHERE parameter = 'com.entelience.raci.delayRaciChangeOnModule';
UPDATE public.e_preference_descriptions SET description = 'Email du support.' WHERE parameter = 'com.entelience.esis.SupportNotifier.supportEmail';
UPDATE public.e_preference_descriptions SET description = 'Activer la notification au support.' WHERE parameter = 'com.entelience.esis.feature.SupportNotifier';
UPDATE public.e_preference_descriptions SET description = 'Adresse DE par défaut dans les emails.' WHERE parameter = 'com.entelience.mail.MailHelper.defaultFromAddress';
UPDATE public.e_preference_descriptions SET description = 'Taille minimale du mot de passe.' WHERE parameter = 'com.entelience.esis.security.minPasswordLength';
UPDATE public.e_preference_descriptions SET description = 'Utiliser les règles de complexité sur les mots de passe.' WHERE parameter = 'com.entelience.esis.security.passwordComplexity';
UPDATE public.e_preference_descriptions SET description = 'Durée de vie maximum d''un mot de passe en jours.' WHERE parameter = 'com.entelience.esis.security.passwordAge';
UPDATE public.e_preference_descriptions SET description = 'Nombre de mot de passe stockés dans l''historique pour chaque utilisateur.' WHERE parameter = 'com.entelience.esis.security.passwordHistory';
UPDATE public.e_preference_descriptions SET description = 'Durée maximale en jours de la dernière connexion utilisateur.' WHERE parameter = 'com.entelience.esis.security.loginHistoryAge';
UPDATE public.e_preference_descriptions SET description = 'Nombre d''échec de connexion utilisateur avant blocage du compte.' WHERE parameter = 'com.entelience.esis.security.numberOfFailedLoginLimit';
UPDATE public.e_preference_descriptions SET description = 'Durée limite en minutes entre échecs de connexion utilisateur.' WHERE parameter = 'com.entelience.esis.security.failedLoginTimeLimit';
UPDATE public.e_preference_descriptions SET description = 'Active le bouton Mot de passe perdu qui permet de recevoir un nouveau mot de passe par email ou si l''utilisateur n''a pas d''email de générer un incident de l''application.' WHERE parameter = 'com.entelience.esis.security.automatedLostPassword';
UPDATE public.e_preference_descriptions SET description = 'Redefinir le premier jour de la semain (ou utiliser le jour par défaut du système).' WHERE parameter = 'com.entelience.provider.calendar.DbCalendar.redefineFirstDayOfWeek';
UPDATE public.e_preference_descriptions SET description = 'Premier jour de la semaine (1=Dimanche,7=Samedi).' WHERE parameter = 'com.entelience.provider.calendar.DbCalendar.firstDayOfWeek';
UPDATE public.e_preference_descriptions SET description = 'Langue de l''application.' WHERE parameter = 'com.entelience.module.Admin.language';
UPDATE public.e_preference_descriptions SET description = 'Les utilisateurs ne peuvent voir un élément que s''ils sont dans la matrice RACI liée.' WHERE parameter = 'com.entelience.module.Audit.user_see_my_only';
UPDATE public.e_preference_descriptions SET description = 'Nombre de reports avant de noter une action comme trop repoussée.' WHERE parameter = 'com.entelience.module.Audit.escaladeActionAfterNDelays';
UPDATE public.e_preference_descriptions SET description = 'Nombre de reports avant de noter une recommandation comme trop repoussée.' WHERE parameter = 'com.entelience.module.Audit.escaladeRecommendationAfterNDelays';
UPDATE public.e_preference_descriptions SET description = 'Masquer les nouveaux produits importés par les sondes.' WHERE parameter = 'com.entelience.esis.feature.hideNewProduct';
UPDATE public.e_preference_descriptions SET description = 'Masquer les nouveaux fournisseurs, vendeurs importés par les sondes.' WHERE parameter = 'com.entelience.esis.feature.hideNewVendor';
UPDATE public.e_preference_descriptions SET description = 'Classe de rapport chargée pour obtenir les métriques.' WHERE parameter = 'com.entelience.soap.soapIdentityManagement.IMReportClassName';
UPDATE public.e_preference_descriptions SET description = 'Pourcentage entre métrique et cible sous lequel le métrique est considéré comme bon.' WHERE parameter = 'com.entelience.esis.im.snail_colors.percent_low';
UPDATE public.e_preference_descriptions SET description = 'Pourcentage entre métrique et cible sous lequel le métrique est considéré comme assez bon.' WHERE parameter = 'com.entelience.esis.im.snail_colors.percent_medium';
UPDATE public.e_preference_descriptions SET description = 'Pourcentage entre métrique et cible sous lequel le métrique est considéré comme moyen.' WHERE parameter = 'com.entelience.esis.im.snail_colors.percent_high';
UPDATE public.e_preference_descriptions SET description = 'Pourcentage entre métrique et cible sous lequel le métrique est considéré comme mauvais.' WHERE parameter = 'com.entelience.esis.im.snail_colors.percent_bad';
UPDATE public.e_preference_descriptions SET description = 'Nombre moyen de requêtes (hits) par page.' WHERE parameter = 'com.entelience.http.average_hits_per_page';
UPDATE public.e_preference_descriptions SET description = 'Temps moyen passé sur une page en secondes.' WHERE parameter = 'com.entelience.http.average_time_spent_per_page';
UPDATE public.e_preference_descriptions SET description = 'Nombre de données sur l''axe Y pour les graphiques en lignes.' WHERE parameter = 'com.entelience.module.Portal.numberOfGridsInChart';
UPDATE public.e_preference_descriptions SET description = 'Afficher les valeurs à partir de 0 dans les graphiques en lignes.' WHERE parameter = 'com.entelience.module.Portal.gridFrom0';
UPDATE public.e_preference_descriptions SET description = 'Afficher les catégories Internet ignorées dans les listes.' WHERE parameter = 'com.entelience.module.Portal.ignoredCategories';
UPDATE public.e_preference_descriptions SET description = 'Afficher la partie Autres données dans les graphiques camemberts.' WHERE parameter = 'com.entelience.module.Portal.show_others_in_pie';
UPDATE public.e_preference_descriptions SET description = 'Les utilisateurs ne peuvent voir un élément que s''ils sont dans la matrice RACI liée.' WHERE parameter = 'com.entelience.module.RiskAssessment.user_see_my_only';
UPDATE public.e_preference_descriptions SET description = 'Les utilisateurs ne peuvent voir un élément que s''ils sont dans la matrice RACI liée.' WHERE parameter = 'com.entelience.module.RiskModelisation.user_see_my_only';
UPDATE public.e_preference_descriptions SET description = 'Une vulnérabilité peut être corrigée (ou non-corrigée) que si toutes ses actions sont dans un statut corrigé (ou non-corrigé).' WHERE parameter = 'com.entelience.esis.vrt.actions.actions_fixed_before_vuln_fixed';
UPDATE public.e_preference_descriptions SET description = 'La décision appliquée à une vulnérabilité peut être modifiée même dans un regroupement de vulnérabilité fermé.' WHERE parameter = 'com.entelience.esis.vrt.closed_vrt_vuln_can_change_decision';
UPDATE public.e_preference_descriptions SET description = 'Les utilisateurs ne peuvent voir un élément que s''ils sont dans la matrice RACI liée.' WHERE parameter = 'com.entelience.esis.vrt.user_see_my_only';
UPDATE public.e_preference_descriptions SET description = 'Spécifique à l''écran des nouvelles vulnérabilités: les utilisateurs ne peuvent voir un élément que s''ils sont dans la matrice RACI liée.' WHERE parameter = 'com.entelience.esis.vrt.user_see_my_new_only';
UPDATE public.e_preference_descriptions SET description = 'Seulement actif en mode Vote quand tous les experts doivent voter. C''est le nombre minimal de vote nécessaire pour activer la décision sur une vulnérabilité.' WHERE parameter = 'com.entelience.esis.vrt.vote_ignore_decision_ceiling';
UPDATE public.e_preference_descriptions SET description = 'Activation du mode Vote pour trier les vulnérabilités et les regrouper.' WHERE parameter = 'com.entelience.esis.vrt.vote_instead_of_decision';
UPDATE public.e_preference_descriptions SET description = 'Activation du mode Vote Simplifié: dès le premier vote la vulnérabilité est placée dans un regroupement existant et peut recevoir des votes jusqu''à son analyse. Note: une action est générée pour chaque vote sur une vulnérabilité. La vulnérabilité peut être analysée même si son regroupement n''a pas été démarré. La décision appliquée à la vulnérabilité est automatiquement mise en réparation ou ignorée en fonction du type de vote.' WHERE parameter = 'com.entelience.esis.vrt.simplifiedVRTProcess';
UPDATE public.e_preference_descriptions SET description = 'La décision des vulnérabilités votées peut être modifiée.' WHERE parameter = 'com.entelience.esis.vrt.votesBasedDecision';
UPDATE public.e_preference_descriptions SET description = 'Décision par défaut utilisée pour une vulnérabilité recevant ignoré en vote (table vuln.e_vulnerability_status).' WHERE parameter = 'com.entelience.esis.vrt.votesBasedDecision.IgnoredDecision';
UPDATE public.e_preference_descriptions SET description = 'Décision par défaut utilisée pour une vulnérabilité ajoutée à un regroupement suite à un vote (table vuln.e_vulnerability_status).' WHERE parameter = 'com.entelience.esis.vrt.votesBasedDecision.AddDecision';
UPDATE public.e_preference_descriptions SET description = 'Seulement actif en mode Vote. Seuls les experts pour cette vulnérabilité peuvent voter.' WHERE parameter = 'com.entelience.esis.vrt.only_experts_can_vote';
UPDATE public.e_preference_descriptions SET description = 'Seulement actif en mode Vote. Une vulnérabilité peut recevoir des votes jusqu''à son analyse.' WHERE parameter = 'com.entelience.esis.vrt.can_vote_until_analysis';
UPDATE public.e_preference_descriptions SET description = 'Le membre d''un département de l''entreprise expert pour un type de vulnérabilité evite aux autres membres de voter.' WHERE parameter = 'com.entelience.esis.vrt.oneVotePerExpertDepartment';
UPDATE public.e_preference_descriptions SET description = 'Création d''une action lors d''un vote (ou d''un tri) sur une vulnérabilité.' WHERE parameter = 'com.entelience.esis.vrt.createActionOnTriage';
UPDATE public.e_preference_descriptions SET description = 'Lorsqu''une vulnérabilité est ignorée, l''utilisateur doit commenter son action.' WHERE parameter = 'com.entelience.esis.vrt.commentRequiredOnIgnore';
UPDATE public.e_preference_descriptions SET description = 'Le tri d''une vulnerabilité réouverte change sa décision.' WHERE parameter = 'com.entelience.esis.vrt.triageOnRenewedVulnOutdoHigherDecision';
UPDATE public.e_preference_descriptions SET description = 'Modèle d''URL pour accéder à la version web des données de vulnérabilités SecurityFocus.' WHERE parameter = 'com.entelience.provider.vrt.url.securityfocus';
UPDATE public.e_preference_descriptions SET description = 'Modèle d''URL pour accéder à la version web des données de vulnérabilités Microsoft.' WHERE parameter = 'com.entelience.provider.vrt.url.microsoft';
UPDATE public.e_preference_descriptions SET description = 'Modèle d''URL pour accéder à la version web des données de vulnérabilités NVD.' WHERE parameter = 'com.entelience.provider.vrt.url.nist';
UPDATE public.e_preference_descriptions SET description = 'Modèle d''URL pour accéder à la version web des données de vulnérabilités Cert-IST.' WHERE parameter = 'com.entelience.provider.vrt.url.certist';
UPDATE public.e_preference_descriptions SET description = 'Emails envoyés aux experts concernés par des nouvelles vulnérabiltés.' WHERE parameter = 'com.entelience.esis.feature.notifyNewVulnsForExperts';

UPDATE public.e_raci_object_type SET description = 'Avis de vulnérabilité' WHERE e_raci_object_type_id = 1;
UPDATE public.e_raci_object_type SET description = 'Action pour avis de vulnérabilité' WHERE e_raci_object_type_id = 2;
UPDATE public.e_raci_object_type SET description = 'Réunion VRT' WHERE e_raci_object_type_id = 3;
UPDATE public.e_raci_object_type SET description = 'Module' WHERE e_raci_object_type_id = 4;
UPDATE public.e_raci_object_type SET description = 'Audit' WHERE e_raci_object_type_id = 5;
UPDATE public.e_raci_object_type SET description = 'Interview d''audit' WHERE e_raci_object_type_id = 6;
UPDATE public.e_raci_object_type SET description = 'Document d''audit' WHERE e_raci_object_type_id = 7;
UPDATE public.e_raci_object_type SET description = 'Recommandation d''audit (auditeur)' WHERE e_raci_object_type_id = 8;
UPDATE public.e_raci_object_type SET description = 'Recommandation d''audit (audité)' WHERE e_raci_object_type_id = 9;
UPDATE public.e_raci_object_type SET description = 'Action d''audit' WHERE e_raci_object_type_id = 10;
UPDATE public.e_raci_object_type SET description = 'Rapport d''audit' WHERE e_raci_object_type_id = 11;
UPDATE public.e_raci_object_type SET description = 'Produit composé' WHERE e_raci_object_type_id = 12;
UPDATE public.e_raci_object_type SET description = 'Risque' WHERE e_raci_object_type_id = 13;
UPDATE public.e_raci_object_type SET description = 'Revue de risque' WHERE e_raci_object_type_id = 14;
UPDATE public.e_raci_object_type SET description = 'Contrôle sur un risque' WHERE e_raci_object_type_id = 15;
UPDATE public.e_raci_object_type SET description = 'Action sur un risque' WHERE e_raci_object_type_id = 16;

UPDATE risk.e_category SET category_name = 'Maladies' WHERE e_category_id = 1;
UPDATE risk.e_category SET category_name = 'Economique' WHERE e_category_id = 2;
UPDATE risk.e_category SET category_name = 'Environnemental' WHERE e_category_id = 3;
UPDATE risk.e_category SET category_name = 'Financier' WHERE e_category_id = 4;
UPDATE risk.e_category SET category_name = 'Humain' WHERE e_category_id = 5;
UPDATE risk.e_category SET category_name = 'Naturel' WHERE e_category_id = 6;
UPDATE risk.e_category SET category_name = 'Santé' WHERE e_category_id = 7;
UPDATE risk.e_category SET category_name = 'Responsabilité produit' WHERE e_category_id = 8;
UPDATE risk.e_category SET category_name = 'Responsabilité professionnelle' WHERE e_category_id = 9;
UPDATE risk.e_category SET category_name = 'Dégâts matériels' WHERE e_category_id = 10;
UPDATE risk.e_category SET category_name = 'Responsabilité publique' WHERE e_category_id = 11;
UPDATE risk.e_category SET category_name = 'Sécurité' WHERE e_category_id = 12;
UPDATE risk.e_category SET category_name = 'Technologique' WHERE e_category_id = 13;
UPDATE risk.e_risk_decision SET decision = 'Réduction' WHERE e_risk_decision_id = 1;
UPDATE risk.e_risk_decision SET decision = 'Atténuation' WHERE e_risk_decision_id = 2;
UPDATE risk.e_risk_decision SET decision = 'Eviter' WHERE e_risk_decision_id = 3;
UPDATE risk.e_risk_decision SET decision = 'Transfert' WHERE e_risk_decision_id = 4;
UPDATE risk.e_risk_priority SET priority = 'Mineur' WHERE e_risk_priority_id = 1;
UPDATE risk.e_risk_priority SET priority = 'Faible' WHERE e_risk_priority_id = 2;
UPDATE risk.e_risk_priority SET priority = 'Normal' WHERE e_risk_priority_id = 3;
UPDATE risk.e_risk_priority SET priority = 'Important' WHERE e_risk_priority_id = 4;
UPDATE risk.e_risk_priority SET priority = 'Urgent' WHERE e_risk_priority_id = 5;
UPDATE risk.e_risk_priority SET priority = 'Critique' WHERE e_risk_priority_id = 6;
UPDATE risk.e_risk_level SET level = 'Faible' WHERE e_risk_level_id = 1;
UPDATE risk.e_risk_level SET level = 'Moyen' WHERE e_risk_level_id = 2;
UPDATE risk.e_risk_level SET level = 'Significatif' WHERE e_risk_level_id = 3;
UPDATE risk.e_risk_level SET level = 'Elevé' WHERE e_risk_level_id = 4;
UPDATE risk.e_action_status SET action_status = 'Planifié' WHERE e_action_status_id = 1;
UPDATE risk.e_action_status SET action_status = 'En cours' WHERE e_action_status_id = 2;
UPDATE risk.e_action_status SET action_status = 'Finalisé' WHERE e_action_status_id = 3;
UPDATE risk.e_action_status SET action_status = 'Annulé' WHERE e_action_status_id = 4;
UPDATE risk.e_action_status SET action_status = 'En pause' WHERE e_action_status_id = 5;

UPDATE risk.e_likelihood SET name = 'Rare' WHERE e_likelihood_id = 1;
UPDATE risk.e_likelihood SET name = 'Improbable' WHERE e_likelihood_id = 2;
UPDATE risk.e_likelihood SET name = 'Modéré' WHERE e_likelihood_id = 3;
UPDATE risk.e_likelihood SET name = 'Probable' WHERE e_likelihood_id = 4;
UPDATE risk.e_likelihood SET name = 'Certain' WHERE e_likelihood_id = 5;
UPDATE risk.e_likelihood SET description = 'L''évènement ne peut se produire qu''en des cisconstances exceptionnelles' WHERE e_likelihood_id = 1;
UPDATE risk.e_likelihood SET description = 'L''évènement peut se produire à l''occasion' WHERE e_likelihood_id = 2;
UPDATE risk.e_likelihood SET description = 'L''évènement se produira probablement de temps en temps' WHERE e_likelihood_id = 3;
UPDATE risk.e_likelihood SET description = 'L''évènement se produira probablement la plupart du temps' WHERE e_likelihood_id = 4;
UPDATE risk.e_likelihood SET description = 'L''évènement se produira probablement lors de la majorité des cas' WHERE e_likelihood_id = 5;
UPDATE risk.e_consequence_level SET label = 'Négligeable' WHERE e_consequence_level_id = 1;
UPDATE risk.e_consequence_level SET label = 'Mineur' WHERE e_consequence_level_id = 2;
UPDATE risk.e_consequence_level SET label = 'Modéré' WHERE e_consequence_level_id = 3;
UPDATE risk.e_consequence_level SET label = 'Majeur' WHERE e_consequence_level_id = 4;
UPDATE risk.e_consequence_level SET label = 'Catastrophique' WHERE e_consequence_level_id = 5;
UPDATE risk.e_consequence_level SET label = 'Négligeable' WHERE e_consequence_level_id = 11;
UPDATE risk.e_consequence_level SET label = 'Mineur' WHERE e_consequence_level_id = 12;
UPDATE risk.e_consequence_level SET label = 'Modéré' WHERE e_consequence_level_id = 13;
UPDATE risk.e_consequence_level SET label = 'Majeur' WHERE e_consequence_level_id = 14;
UPDATE risk.e_consequence_level SET label = 'Exceptionnnel' WHERE e_consequence_level_id = 15;
UPDATE risk.e_consequence_level SET description = 'Pas de dommages, déficit faible' WHERE e_consequence_level_id = 1;
UPDATE risk.e_consequence_level SET description = 'Premiers secours, déficit moyen' WHERE e_consequence_level_id = 2;
UPDATE risk.e_consequence_level SET description = 'Traitement requis, déficit élevé' WHERE e_consequence_level_id = 3;
UPDATE risk.e_consequence_level SET description = 'Dommages étendus, déficit majeur' WHERE e_consequence_level_id = 4;
UPDATE risk.e_consequence_level SET description = 'Mort, déficit immense' WHERE e_consequence_level_id = 5;
UPDATE risk.e_consequence_level SET description = 'Peu de bénéfices, profits faibles' WHERE e_consequence_level_id = 11;
UPDATE risk.e_consequence_level SET description = 'Améliorations mineures, quelques profits' WHERE e_consequence_level_id = 12;
UPDATE risk.e_consequence_level SET description = 'Quelques améliorations, profits importants' WHERE e_consequence_level_id = 13;
UPDATE risk.e_consequence_level SET description = 'Nombreuses améliorations, profit majeur' WHERE e_consequence_level_id = 14;
UPDATE risk.e_consequence_level SET description = 'Réputation significativement améliorée, très grands profits' WHERE e_consequence_level_id = 15;

UPDATE sdw.e_operation_state SET state_descr = 'Prêt' WHERE e_state_id = 0;
UPDATE sdw.e_operation_state SET state_descr = 'Démarré' WHERE e_state_id = 1;
UPDATE sdw.e_operation_state SET state_descr = 'Fini' WHERE e_state_id = 2;
UPDATE sdw.e_operation_state SET state_descr = 'Besion d''annulation' WHERE e_state_id = 3;
UPDATE sdw.e_operation_state SET state_descr = 'Annulation démarrée' WHERE e_state_id = 4;
UPDATE sdw.e_operation_state SET state_descr = 'Annulé' WHERE e_state_id = 5;

UPDATE virus.e_alert_level SET alert_name = 'Normal' WHERE e_alert_level_id = 1;
UPDATE virus.e_alert_level SET alert_name = 'Elevé' WHERE e_alert_level_id = 2;
UPDATE virus.e_alert_level SET alert_name = 'Très élevé' WHERE e_alert_level_id = 3;
UPDATE virus.e_alert_level SET alert_name = 'Extrême' WHERE e_alert_level_id = 4;
UPDATE virus.t_virus_origin SET origin = 'Fichier' WHERE t_virus_origin_id = 1;
UPDATE virus.t_virus_origin SET origin = 'Email' WHERE t_virus_origin_id = 2;
UPDATE virus.t_virus_origin SET origin = 'Web' WHERE t_virus_origin_id = 3;
UPDATE virus.t_virus_origin_detail SET detail = 'Lecteur local' WHERE t_virus_origin_detail_id = 1;
UPDATE virus.t_virus_origin_detail SET detail = 'Lecteur mobile' WHERE t_virus_origin_detail_id = 2;
UPDATE virus.t_virus_origin_detail SET detail = 'Lecteur reseau' WHERE t_virus_origin_detail_id = 3;
UPDATE virus.t_virus_origin_detail SET detail = 'Email interne' WHERE t_virus_origin_detail_id = 4;
UPDATE virus.t_virus_origin_detail SET detail = 'Email entrant' WHERE t_virus_origin_detail_id = 5;
UPDATE virus.t_virus_origin_detail SET detail = 'Email sortant' WHERE t_virus_origin_detail_id = 6;
UPDATE virus.t_virus_origin_detail SET detail = 'Web' WHERE t_virus_origin_detail_id = 7;

UPDATE vuln.e_vulnerability_severity SET severity_name = 'Non évaluée' WHERE e_severity_id = 0;
UPDATE vuln.e_vulnerability_severity SET severity_name = 'Faible' WHERE e_severity_id = 1;
UPDATE vuln.e_vulnerability_severity SET severity_name = 'Moyenne' WHERE e_severity_id = 2;
UPDATE vuln.e_vulnerability_severity SET severity_name = 'Elevée' WHERE e_severity_id = 3;
UPDATE vuln.e_vulnerability_severity SET severity_name = 'Très élevée' WHERE e_severity_id = 4;
UPDATE vuln.e_vulnerability_status SET status_name = 'Nouveauté' WHERE e_status_id = 0;
UPDATE vuln.e_vulnerability_status SET status_name = 'A corriger' WHERE e_status_id = 1;
UPDATE vuln.e_vulnerability_status SET status_name = 'A étudier' WHERE e_status_id = 2;
UPDATE vuln.e_vulnerability_status SET status_name = 'Risque accepté' WHERE e_status_id = 3;
UPDATE vuln.e_vulnerability_status SET status_name = 'Non impacté' WHERE e_status_id = 4;
UPDATE vuln.e_vulnerability_priority SET priority_name = 'Non évaluée' WHERE e_priority_id = 0;
UPDATE vuln.e_vulnerability_priority SET priority_name = 'Faible' WHERE e_priority_id = 1;
UPDATE vuln.e_vulnerability_priority SET priority_name = 'Moyenne' WHERE e_priority_id = 2;
UPDATE vuln.e_vulnerability_priority SET priority_name = 'Elevée' WHERE e_priority_id = 3;
UPDATE vuln.e_vulnerability_priority SET priority_name = 'Très élevée' WHERE e_priority_id = 4;
UPDATE vuln.e_vulnerability_mav_status SET mav_status_name = 'Non défini' WHERE e_mav_status_id = 0;
UPDATE vuln.e_vulnerability_mav_status SET mav_status_name = 'Corrigé' WHERE e_mav_status_id = 1;
UPDATE vuln.e_vulnerability_mav_status SET mav_status_name = 'Planifié' WHERE e_mav_status_id = 2;
UPDATE vuln.e_vulnerability_mav_status SET mav_status_name = 'En cours d''intégration' WHERE e_mav_status_id = 3;
UPDATE vuln.e_vulnerability_mav_status SET mav_status_name = 'Non corrigé' WHERE e_mav_status_id = 4;
UPDATE vuln.e_vulnerability_vote_decision SET vote_decision = 'Impacté' WHERE e_vulnerability_vote_decision_id = 0;
UPDATE vuln.e_vulnerability_vote_decision SET vote_decision = 'Non impacté' WHERE e_vulnerability_vote_decision_id = 4;

