UPDATE asset.e_asset_type SET name = 'Cluster' WHERE id = 1;
UPDATE asset.e_asset_type SET name = 'Server' WHERE id = 2;
UPDATE asset.e_asset_type SET name = 'Server Appliance' WHERE id = 3;
UPDATE asset.e_asset_type SET name = 'Router' WHERE id = 4;
UPDATE asset.e_asset_type SET name = 'Network Appliance' WHERE id = 5;
UPDATE asset.e_asset_type SET name = 'Security Appliance' WHERE id = 6;
UPDATE asset.e_asset_type SET name = 'Access Device' WHERE id = 7;
UPDATE asset.e_asset_type SET name = 'Mobile Access Device' WHERE id = 8;
UPDATE asset.e_asset_type SET name = 'Printing Device' WHERE id = 9;
UPDATE asset.e_sc SET name = 'Business Critical' WHERE id = 1;
UPDATE asset.e_sc SET name = 'Business Needed' WHERE id = 2;
UPDATE asset.e_sc SET name = 'Business' WHERE id = 3;
UPDATE asset.e_sc SET name = 'Business Support' WHERE id = 4;
UPDATE asset.e_sc SET name = 'Infrastructure' WHERE id = 5;
UPDATE asset.e_sc SET name = 'Non-Business Critical' WHERE id = 6;
UPDATE asset.e_sc SET name = 'Non-Business' WHERE id = 7;
UPDATE asset.e_bl SET name = 'IT' WHERE id = 1;
UPDATE asset.e_bl SET name = 'Corporate' WHERE id = 2;
UPDATE asset.e_bl SET name = 'Sales' WHERE id = 3;
UPDATE asset.e_bl SET name = 'Marketing' WHERE id = 4;
UPDATE asset.e_bl SET name = 'R&D' WHERE id = 5;
UPDATE asset.e_bl SET name = 'Production' WHERE id = 6;
UPDATE asset.e_bl SET name = 'Accounting' WHERE id = 7;
UPDATE asset.e_bl SET name = 'Finance' WHERE id = 8;
UPDATE asset.e_bl SET name = 'Fields' WHERE id = 9;
UPDATE asset.e_bl SET name = 'Business Partners' WHERE id = 10;
UPDATE asset.e_availability SET name = 'Non-Stop' WHERE id = 1;
UPDATE asset.e_availability SET name = 'High Availability' WHERE id = 2;
UPDATE asset.e_availability SET name = '99%' WHERE id = 3;
UPDATE asset.e_availability SET name = 'Business Hours' WHERE id = 4;
UPDATE asset.e_availability SET name = 'Best effort' WHERE id = 5;

UPDATE audit.e_audit_rec_status SET rec_status = 'Open' WHERE e_audit_rec_status_id = 1;
UPDATE audit.e_audit_rec_status SET rec_status = 'Closed' WHERE e_audit_rec_status_id = 2;
UPDATE audit.e_audit_rec_status SET rec_status = 'Risk Accepted' WHERE e_audit_rec_status_id = 3;
UPDATE audit.e_audit_rec_status SET rec_status = 'Closed Duplicate' WHERE e_audit_rec_status_id = 4;
UPDATE audit.e_audit_severity SET severity = 'Low' WHERE e_audit_severity_id = 1;
UPDATE audit.e_audit_severity SET severity = 'Medium' WHERE e_audit_severity_id = 2;
UPDATE audit.e_audit_severity SET severity = 'High' WHERE e_audit_severity_id = 3;
UPDATE audit.e_audit_topic SET topic = 'Network Security' WHERE e_audit_topic_id = 1;
UPDATE audit.e_audit_topic SET topic = 'Physical Security' WHERE e_audit_topic_id = 2;
UPDATE audit.e_audit_topic SET topic = 'System Security' WHERE e_audit_topic_id = 3;
UPDATE audit.e_audit_topic SET topic = 'Access' WHERE e_audit_topic_id = 4;
UPDATE audit.e_audit_topic SET topic = 'Applications' WHERE e_audit_topic_id = 5;
UPDATE audit.e_audit_topic SET topic = 'Business' WHERE e_audit_topic_id = 6;
UPDATE audit.e_audit_topic SET topic = 'Other' WHERE e_audit_topic_id = 7;
UPDATE audit.e_audit_origin SET origin = 'Internal audit' WHERE e_audit_origin_id = 1;
UPDATE audit.e_audit_origin SET origin = 'External audit' WHERE e_audit_origin_id = 2;
UPDATE audit.e_audit_origin SET origin = 'Regulators' WHERE e_audit_origin_id = 3;
UPDATE audit.e_audit_origin SET origin = 'Self audit' WHERE e_audit_origin_id = 4;
UPDATE audit.e_audit_action_status SET action_status = 'Planning' WHERE e_audit_action_status_id = 1;
UPDATE audit.e_audit_action_status SET action_status = 'In Progress' WHERE e_audit_action_status_id = 2;
UPDATE audit.e_audit_action_status SET action_status = 'Completed' WHERE e_audit_action_status_id = 3;
UPDATE audit.e_audit_action_status SET action_status = 'Cancelled' WHERE e_audit_action_status_id = 4;
UPDATE audit.e_audit_action_status SET action_status = 'Halted' WHERE e_audit_action_status_id = 5;
UPDATE audit.e_audit_priority SET priority = 'Low' WHERE e_audit_priority_id = 1;
UPDATE audit.e_audit_priority SET priority = 'Medium' WHERE e_audit_priority_id = 2;
UPDATE audit.e_audit_priority SET priority = 'High' WHERE e_audit_priority_id = 3;
UPDATE audit.e_audit_rec_topic SET topic = 'Access' WHERE e_audit_rec_topic_id = 1;
UPDATE audit.e_audit_rec_topic SET topic = 'Network' WHERE e_audit_rec_topic_id = 2;
UPDATE audit.e_audit_rec_topic SET topic = 'Premises' WHERE e_audit_rec_topic_id = 3;
UPDATE audit.e_audit_rec_topic SET topic = 'Management' WHERE e_audit_rec_topic_id = 4;
UPDATE audit.e_audit_rec_topic SET topic = 'Global' WHERE e_audit_rec_topic_id = 5;
UPDATE audit.e_audit_rec_topic SET topic = 'Monitoring' WHERE e_audit_rec_topic_id = 6;
UPDATE audit.e_audit_rec_topic SET topic = 'Awareness' WHERE e_audit_rec_topic_id = 7;
UPDATE audit.e_audit_confidentiality SET confidentiality = 'Internal' WHERE e_audit_confidentiality_id = 1;
UPDATE audit.e_audit_confidentiality SET confidentiality = 'Confidential' WHERE e_audit_confidentiality_id = 2;
UPDATE audit.e_audit_confidentiality SET confidentiality = 'Sponsor Only' WHERE e_audit_confidentiality_id = 3;
UPDATE audit.e_audit_confidentiality SET confidentiality = 'Company Private' WHERE e_audit_confidentiality_id = 4;
UPDATE audit.e_audit_status SET status = 'Planning' WHERE e_audit_status_id = 1;
UPDATE audit.e_audit_status SET status = 'Contracting' WHERE e_audit_status_id = 2;
UPDATE audit.e_audit_status SET status = 'Interviews' WHERE e_audit_status_id = 3;
UPDATE audit.e_audit_status SET status = 'Opening meeting' WHERE e_audit_status_id = 4;
UPDATE audit.e_audit_status SET status = 'Draft Report' WHERE e_audit_status_id = 5;
UPDATE audit.e_audit_status SET status = 'Final Report' WHERE e_audit_status_id = 6;
UPDATE audit.e_audit_status SET status = 'Closing meeting' WHERE e_audit_status_id = 7;
UPDATE audit.e_audit_status SET status = 'Remediating' WHERE e_audit_status_id = 8;
UPDATE audit.e_audit_status SET status = 'Closed' WHERE e_audit_status_id = 9;
UPDATE audit.e_audit_report_status SET report_status = 'Draft' WHERE e_audit_report_status_id = 1;
UPDATE audit.e_audit_report_status SET report_status = 'Final' WHERE e_audit_report_status_id = 2;
UPDATE audit.e_audit_report_status SET report_status = 'Approved' WHERE e_audit_report_status_id = 3;
UPDATE audit.e_audit_report_status SET report_status = 'Published' WHERE e_audit_report_status_id = 4;
UPDATE audit.e_audit_document_type SET document_type = 'Evidence' WHERE e_audit_document_type_id = 1;
UPDATE audit.e_audit_document_type SET document_type = 'Information' WHERE e_audit_document_type_id = 2;
UPDATE audit.e_audit_document_type SET document_type = 'Email' WHERE e_audit_document_type_id = 3;
UPDATE audit.e_audit_document_type SET document_type = 'Document' WHERE e_audit_document_type_id = 4;

UPDATE compliance.e_standard_category SET standard_category = 'Information Technology' WHERE e_standard_category_id = 1;
UPDATE compliance.e_standard_category SET standard_category = 'General Management' WHERE e_standard_category_id = 2;
UPDATE compliance.e_topic_category SET topic_category = 'Security Management' WHERE e_topic_category_id = 1;
UPDATE compliance.e_topic_category SET topic_category = 'Access Control' WHERE e_topic_category_id = 2;
UPDATE compliance.e_compliance_kind SET kind = 'Application comment' WHERE e_compliance_kind_id = 1;
UPDATE compliance.e_compliance_kind SET kind = 'Documentation comment' WHERE e_compliance_kind_id = 2;
UPDATE compliance.e_compliance_type SET compliance_type = 'Non compliance of minor application' WHERE e_compliance_type_id = 1;
UPDATE compliance.e_compliance_type SET compliance_type = 'Non compliance of minor documentation' WHERE e_compliance_type_id = 2;
UPDATE compliance.e_compliance_type SET compliance_type = 'Non compliance of major application' WHERE e_compliance_type_id = 3;
UPDATE compliance.e_compliance_type SET compliance_type = 'Non compliance of major documentation' WHERE e_compliance_type_id = 4;

UPDATE mim.t_user_anomaly SET description = 'None' WHERE t_user_anomaly_id = 1;
UPDATE mim.t_user_anomaly SET description = 'Fudge : mainframe data missing' WHERE t_user_anomaly_id = 2;
UPDATE mim.t_user_anomaly SET description = 'Fudge : mainframe date security admin missing' WHERE t_user_anomaly_id = 3;
UPDATE mim.t_user_anomaly SET description = 'Fudge : mainframe datecontractvalidity abnormal' WHERE t_user_anomaly_id = 4;
UPDATE mim.t_user_anomaly SET description = 'Fudge : mainframe date1sthire bad' WHERE t_user_anomaly_id = 5;
UPDATE mim.t_user_anomaly SET description = 'Fudge : mainframe ou bad' WHERE t_user_anomaly_id = 6;
UPDATE mim.t_user_anomaly SET description = 'Fudge : mainframe l bad' WHERE t_user_anomaly_id = 7;
UPDATE mim.t_user_anomaly SET description = 'Fudge : ad data missing' WHERE t_user_anomaly_id = 8;
UPDATE mim.t_user_anomaly SET description = 'Fudge : ad date is 0' WHERE t_user_anomaly_id = 9;
UPDATE mim.t_user_anomaly SET description = 'Fudge : hr data missing' WHERE t_user_anomaly_id = 10;
UPDATE mim.t_user_anomaly SET description = 'Fudge : hr logoncount missing' WHERE t_user_anomaly_id = 11;
UPDATE mim.t_user_anomaly SET description = 'Fudge : hr still has 19000000 as dates' WHERE t_user_anomaly_id = 12;
UPDATE mim.t_user_anomaly SET description = 'Fudge : hr still has 19800101 as dates' WHERE t_user_anomaly_id = 13;

UPDATE itops.t_alert_severity SET severity_name = 'Information' WHERE t_alert_severity_id = 1;
UPDATE itops.t_alert_severity SET severity_name = 'Warning' WHERE t_alert_severity_id = 2;
UPDATE itops.t_alert_severity SET severity_name = 'Critical' WHERE t_alert_severity_id = 3;
UPDATE itops.t_alert_priority SET priority_name = 'Low' WHERE t_alert_priority_id = 1;
UPDATE itops.t_alert_priority SET priority_name = 'Medium' WHERE t_alert_priority_id = 2;
UPDATE itops.t_alert_priority SET priority_name = 'High' WHERE t_alert_priority_id = 3;
UPDATE itops.t_event_level SET event_level = 'Success' WHERE t_event_level_id = 1;
UPDATE itops.t_event_level SET event_level = 'Error' WHERE t_event_level_id = 2;
UPDATE itops.t_event_level SET event_level = 'Warning' WHERE t_event_level_id = 3;
UPDATE itops.t_event_level SET event_level = 'Information' WHERE t_event_level_id = 4;
UPDATE itops.t_event_level SET event_level = 'Audit Success' WHERE t_event_level_id = 5;
UPDATE itops.t_event_level SET event_level = 'Audit Failure' WHERE t_event_level_id = 6;

UPDATE itsm.t_status SET status_name = 'New' WHERE t_status_id = 1;
UPDATE itsm.t_status SET status_name = 'Pending' WHERE t_status_id = 2;
UPDATE itsm.t_status SET status_name = 'Cancelled' WHERE t_status_id = 3;
UPDATE itsm.t_status SET status_name = 'Fixed' WHERE t_status_id = 4;
UPDATE itsm.t_status SET status_name = 'Won''t fix' WHERE t_status_id = 5;
UPDATE itsm.t_status SET status_name = 'Closed' WHERE t_status_id = 6;
UPDATE itsm.t_ipsu SET ipsu_name = 'Non blocking' WHERE t_ipsu_id = 1;
UPDATE itsm.t_ipsu SET ipsu_name = 'Individual' WHERE t_ipsu_id = 2;
UPDATE itsm.t_ipsu SET ipsu_name = 'Group' WHERE t_ipsu_id = 3;
UPDATE itsm.t_ipsu SET ipsu_name = 'Low' WHERE t_ipsu_id = 11;
UPDATE itsm.t_ipsu SET ipsu_name = 'Medium' WHERE t_ipsu_id = 12;
UPDATE itsm.t_ipsu SET ipsu_name = 'High' WHERE t_ipsu_id = 13;
UPDATE itsm.t_ipsu SET ipsu_name = 'Low' WHERE t_ipsu_id = 21;
UPDATE itsm.t_ipsu SET ipsu_name = 'Medium' WHERE t_ipsu_id = 22;
UPDATE itsm.t_ipsu SET ipsu_name = 'High' WHERE t_ipsu_id = 23;
UPDATE itsm.t_ipsu SET ipsu_name = 'Normal' WHERE t_ipsu_id = 31;
UPDATE itsm.t_ipsu SET ipsu_name = 'Urgent' WHERE t_ipsu_id = 32;
UPDATE itsm.t_ipsu SET ipsu_name = 'Immediate' WHERE t_ipsu_id = 33;
UPDATE itsm.t_satisfaction_level SET satisfaction_level = 'Very high' WHERE t_satisfaction_level_id = 1;
UPDATE itsm.t_satisfaction_level SET satisfaction_level = 'High' WHERE t_satisfaction_level_id = 2;
UPDATE itsm.t_satisfaction_level SET satisfaction_level = 'Medium' WHERE t_satisfaction_level_id = 3;
UPDATE itsm.t_satisfaction_level SET satisfaction_level = 'Low' WHERE t_satisfaction_level_id = 4;

UPDATE public.e_file_states SET state_name = 'Aborted, inconsistent data' WHERE id = -4;
UPDATE public.e_file_states SET state_name = 'Aborted' WHERE id = -3;
UPDATE public.e_file_states SET state_name = 'Downloading' WHERE id = -2;
UPDATE public.e_file_states SET state_name = 'Running' WHERE id = -1;
UPDATE public.e_file_states SET state_name = 'Ready' WHERE id = 0;
UPDATE public.e_file_states SET state_name = 'Success' WHERE id = 1;
UPDATE public.e_file_states SET state_name = 'Error - retry' WHERE id = 2;
UPDATE public.e_file_states SET state_name = 'Failure' WHERE id = 3;
UPDATE public.e_file_states SET state_name = 'Ignored' WHERE id = 4;
UPDATE public.e_file_states SET state_name = 'Superceded' WHERE id = 5;
UPDATE public.e_file_states SET state_name = 'Duplicate' WHERE id = 6;
UPDATE public.e_file_states SET state_name = 'Success + Archived' WHERE id = 7;
UPDATE public.e_file_states SET state_name = 'Superceded + Archived' WHERE id = 8;
UPDATE public.e_file_states SET state_name = 'Duplicate + Archived' WHERE id = 9;
UPDATE public.e_file_states SET state_name = 'Failure + Archived' WHERE id = 10;
UPDATE public.e_file_states SET state_name = 'Ignore + Archived' WHERE id = 11;
UPDATE public.e_probe_parameter_origin SET origin = 'Default value' WHERE e_probe_parameter_origin_id = 1;
UPDATE public.e_probe_parameter_origin SET origin = 'Database value' WHERE e_probe_parameter_origin_id = 2;
UPDATE public.e_probe_parameter_origin SET origin = 'XML file' WHERE e_probe_parameter_origin_id = 3;
UPDATE public.e_probe_run_status SET status_name = 'Never run' WHERE e_probe_run_status_id = 0;
UPDATE public.e_probe_run_status SET status_name = 'Success' WHERE e_probe_run_status_id = 1;
UPDATE public.e_probe_run_status SET status_name = 'No data' WHERE e_probe_run_status_id = 2;
UPDATE public.e_probe_run_status SET status_name = 'Aborted' WHERE e_probe_run_status_id = 3;
UPDATE public.e_probe_run_status SET status_name = 'Failure' WHERE e_probe_run_status_id = 4;
UPDATE public.e_probe_run_status SET status_name = 'Error' WHERE e_probe_run_status_id = 5;
UPDATE public.e_probe_run_status SET status_name = 'Still running' WHERE e_probe_run_status_id = 6;
UPDATE public.e_probe_run_status SET status_name = 'Aborted with error' WHERE e_probe_run_status_id = 7;

UPDATE public.e_probe_category SET name = 'Applications' WHERE e_probe_category_id = 1;
UPDATE public.e_probe_category SET name = 'Assets' WHERE e_probe_category_id = 2;
UPDATE public.e_probe_category SET name = 'Audit' WHERE e_probe_category_id = 3;
UPDATE public.e_probe_category SET name = 'Compliance' WHERE e_probe_category_id = 4;
UPDATE public.e_probe_category SET name = 'Web' WHERE e_probe_category_id = 5;
UPDATE public.e_probe_category SET name = 'IT Operations' WHERE e_probe_category_id = 6;
UPDATE public.e_probe_category SET name = 'IT System management' WHERE e_probe_category_id = 7;
UPDATE public.e_probe_category SET name = 'Spam and mail' WHERE e_probe_category_id = 8;
UPDATE public.e_probe_category SET name = 'Identity management' WHERE e_probe_category_id = 9;
UPDATE public.e_probe_category SET name = 'Network events' WHERE e_probe_category_id = 10;
UPDATE public.e_probe_category SET name = 'Vulnerabilities' WHERE e_probe_category_id = 11;
UPDATE public.e_probe_category SET name = 'User tools' WHERE e_probe_category_id = 12;
UPDATE public.e_probe_category SET name = 'Malwares' WHERE e_probe_category_id = 13;
UPDATE public.e_probe_category SET name = 'Instant messaging' WHERE e_probe_category_id = 14;

UPDATE asset.e_product_type SET name = 'Software' WHERE id = 1;
UPDATE asset.e_product_type SET name = 'Hardware' WHERE id = 2;
UPDATE asset.e_product_type SET name = 'Appliance' WHERE id = 3;
UPDATE asset.e_preferred_relationship SET name = 'Strategic partner' WHERE id = 1;
UPDATE asset.e_preferred_relationship SET name = 'Partner' WHERE id = 2;
UPDATE asset.e_preferred_relationship SET name = 'Supplier' WHERE id = 3;
UPDATE asset.e_preferred_relationship SET name = 'No relationship' WHERE id = 4;

UPDATE public.e_preference_descriptions SET description = 'Root directory.' WHERE parameter = 'com.entelience.esis.rootDir';
UPDATE public.e_preference_descriptions SET description = 'Error directory for incorrect files.' WHERE parameter = 'com.entelience.esis.errorsDir';
UPDATE public.e_preference_descriptions SET description = 'Max size for the error directory.' WHERE parameter = 'com.entelience.esis.errorsSize';
UPDATE public.e_preference_descriptions SET description = 'Directory where generated reports are put.' WHERE parameter = 'com.entelience.esis.reportsDir';
UPDATE public.e_preference_descriptions SET description = 'Default company name.' WHERE parameter = 'com.entelience.esis.defaultCompany';
UPDATE public.e_preference_descriptions SET description = 'poweredBy logo file path.' WHERE parameter = 'com.entelience.esis.poweredByLogo';
UPDATE public.e_preference_descriptions SET description = 'Tomcat port.' WHERE parameter = 'com.entelience.esis.web.localServerPort';
UPDATE public.e_preference_descriptions SET description = 'Local server address.' WHERE parameter = 'com.entelience.esis.web.localServerAddress';
UPDATE public.e_preference_descriptions SET description = 'Protocol.' WHERE parameter = 'com.entelience.esis.web.remoteServerProtocol';
UPDATE public.e_preference_descriptions SET description = 'SMTP server host name.' WHERE parameter = 'com.entelience.mail.MailHelper.hostName';
UPDATE public.e_preference_descriptions SET description = 'SMTP server port.' WHERE parameter = 'com.entelience.mail.MailHelper.hostPort';
UPDATE public.e_preference_descriptions SET description = 'SMTP server useTls.' WHERE parameter = 'com.entelience.mail.MailHelper.useTls';
UPDATE public.e_preference_descriptions SET description = 'SMTP server useAuth.' WHERE parameter = 'com.entelience.mail.MailHelper.useAuth';
UPDATE public.e_preference_descriptions SET description = 'SMTP user.' WHERE parameter = 'com.entelience.mail.MailHelper.smtpUser';
UPDATE public.e_preference_descriptions SET description = 'Attach a ical file for generated emails.' WHERE parameter = 'com.entelience.esis.feature.attachCalendarFile';
UPDATE public.e_preference_descriptions SET description = 'SMTP password.' WHERE parameter = 'com.entelience.mail.MailHelper.smtpPassword';
UPDATE public.e_preference_descriptions SET description = 'Number of tries to send an email before failure.' WHERE parameter = 'com.entelience.mail.MailHelper.maxTries';
UPDATE public.e_preference_descriptions SET description = 'Max number of emails sent at once.' WHERE parameter = 'com.entelience.mail.MailHelper.maxEmailSentAtOnce';
UPDATE public.e_preference_descriptions SET description = 'Logo file path.' WHERE parameter = 'com.entelience.mail.MailHelper.iconLocation';
UPDATE public.e_preference_descriptions SET description = 'Timeout in minutes.' WHERE parameter = 'com.entelience.soap.SessionHandler.timeoutMinutes';
UPDATE public.e_preference_descriptions SET description = 'Authentication method.' WHERE parameter = 'com.entelience.soap.soapBase.authMethod';
UPDATE public.e_preference_descriptions SET description = 'Maximum number of returned rows in datagrid.' WHERE parameter = 'com.entelience.esis.maxReturnedRows';
UPDATE public.e_preference_descriptions SET description = 'Base for LDAP authentication.' WHERE parameter = 'com.entelience.soap.auth.LDAP.base';
UPDATE public.e_preference_descriptions SET description = 'Base filter for LDAP authentication.' WHERE parameter = 'com.entelience.soap.auth.LDAP.baseFilterString';
UPDATE public.e_preference_descriptions SET description = 'Username field for LDAP authentication.' WHERE parameter = 'com.entelience.soap.auth.LDAP.userNameField';
UPDATE public.e_preference_descriptions SET description = 'URL for LDAP authentication.' WHERE parameter = 'com.entelience.soap.auth.LDAP.url';
UPDATE public.e_preference_descriptions SET description = 'Search user name for LDAP authentication.' WHERE parameter = 'com.entelience.soap.auth.LDAP.searchUserName';
UPDATE public.e_preference_descriptions SET description = 'Password for LDAP authentication.' WHERE parameter = 'com.entelience.soap.auth.LDAP.searchPassword';
UPDATE public.e_preference_descriptions SET description = 'User agent for HTTP.' WHERE parameter = 'com.entelience.util.HttpHelper.userAgent';
UPDATE public.e_preference_descriptions SET description = 'HTTP connexion use proxy.' WHERE parameter = 'com.entelience.util.HttpHelper.useProxy';
UPDATE public.e_preference_descriptions SET description = 'HTTP proxy host name.' WHERE parameter = 'com.entelience.util.HttpHelper.proxyHost';
UPDATE public.e_preference_descriptions SET description = 'HTTP proxy port name.' WHERE parameter = 'com.entelience.util.HttpHelper.proxyPort';
UPDATE public.e_preference_descriptions SET description = 'HTTP proxy use authentication.' WHERE parameter = 'com.entelience.util.HttpHelper.useProxyAuth';
UPDATE public.e_preference_descriptions SET description = 'HTTP proxy realm.' WHERE parameter = 'com.entelience.util.HttpHelper.proxyRealm';
UPDATE public.e_preference_descriptions SET description = 'HTTP proxy scheme.' WHERE parameter = 'com.entelience.util.HttpHelper.proxyScheme';
UPDATE public.e_preference_descriptions SET description = 'HTTP proxy user name.' WHERE parameter = 'com.entelience.util.HttpHelper.proxyUserName';
UPDATE public.e_preference_descriptions SET description = 'HTTP proxy password.' WHERE parameter = 'com.entelience.util.HttpHelper.proxyPassword';
UPDATE public.e_preference_descriptions SET description = 'User agent for HTTPS.' WHERE parameter = 'com.entelience.util.HttpSslHelper.userAgent';
UPDATE public.e_preference_descriptions SET description = 'HTTPS connexion use proxy.' WHERE parameter = 'com.entelience.util.HttpSslHelper.useProxy';
UPDATE public.e_preference_descriptions SET description = 'HTTPS proxy host name.' WHERE parameter = 'com.entelience.util.HttpSslHelper.proxyHost';
UPDATE public.e_preference_descriptions SET description = 'HTTPS proxy port name.' WHERE parameter = 'com.entelience.util.HttpSslHelper.proxyPort';
UPDATE public.e_preference_descriptions SET description = 'HTTPS proxy use authentication.' WHERE parameter = 'com.entelience.util.HttpSslHelper.useProxyAuth';
UPDATE public.e_preference_descriptions SET description = 'HTTPS proxy realm.' WHERE parameter = 'com.entelience.util.HttpSslHelper.proxyRealm';
UPDATE public.e_preference_descriptions SET description = 'HTTPS proxy scheme.' WHERE parameter = 'com.entelience.util.HttpSslHelper.proxyScheme';
UPDATE public.e_preference_descriptions SET description = 'HTTPS proxy user name.' WHERE parameter = 'com.entelience.util.HttpSslHelper.proxyUserName';
UPDATE public.e_preference_descriptions SET description = 'HTTPS proxy password.' WHERE parameter = 'com.entelience.util.HttpSslHelper.proxyPassword';
UPDATE public.e_preference_descriptions SET description = 'Keystore for HTTPS.' WHERE parameter = 'com.entelience.util.HttpSslHelper.keyStore';
UPDATE public.e_preference_descriptions SET description = 'Keystore password for HTTPS.' WHERE parameter = 'com.entelience.util.HttpSslHelper.keyStorePassword';
UPDATE public.e_preference_descriptions SET description = 'Public store to authenticate licenses.' WHERE parameter = 'com.entelience.license.LicenseHelper.publicStore';
UPDATE public.e_preference_descriptions SET description = 'Strict RACI mode.' WHERE parameter = 'com.entelience.raci.strict_RACI';
UPDATE public.e_preference_descriptions SET description = 'CNIL level.' WHERE parameter = 'com.entelience.esis.cnilLevel';
UPDATE public.e_preference_descriptions SET description = 'Path of the directory containing log files.' WHERE parameter = 'com.entelience.esis.logDirectory';
UPDATE public.e_preference_descriptions SET description = 'Path of the probes XML file.' WHERE parameter = 'com.entelience.esis.probeXmlFile';
UPDATE public.e_preference_descriptions SET description = 'Set the default period to check for probes runs.' WHERE parameter = 'com.entelience.probes.showProbeSnailOnLastNDays';
UPDATE public.e_preference_descriptions SET description = 'Can users edit their own expertises.' WHERE parameter = 'com.entelience.module.Admin.can_edit_its_own_expertises';
UPDATE public.e_preference_descriptions SET description = 'Email notification activated.' WHERE parameter = 'com.entelience.esis.feature.notifyMail';
UPDATE public.e_preference_descriptions SET description = 'Email notification activated for user for its own email address.' WHERE parameter = 'com.entelience.esis.feature.notifySelfMail';
UPDATE public.e_preference_descriptions SET description = 'Use HTML emails.' WHERE parameter = 'com.entelience.esis.feature.attachHtmlMail';
UPDATE public.e_preference_descriptions SET description = 'Send email when an expertise changes.' WHERE parameter = 'com.entelience.esis.feature.sendEmailOnExpertiseChange';
UPDATE public.e_preference_descriptions SET description = 'Send email when a RACI changes.' WHERE parameter = 'com.entelience.esis.feature.sendEmailOnRACIChange';
UPDATE public.e_preference_descriptions SET description = 'Send email when an object changes.' WHERE parameter = 'com.entelience.esis.feature.sendEmailOnObjectModification';
UPDATE public.e_preference_descriptions SET description = 'Send email when an object is created.' WHERE parameter = 'com.entelience.esis.feature.sendEmailOnObjectCreation';
UPDATE public.e_preference_descriptions SET description = 'RACI levels necessary to receive emails.' WHERE parameter = 'com.entelience.mail.MailHelper.receiveEmailOnChange';
UPDATE public.e_preference_descriptions SET description = 'Modules RACI changes are delayed.' WHERE parameter = 'com.entelience.raci.delayRaciChangeOnModule';
UPDATE public.e_preference_descriptions SET description = 'Email of the support.' WHERE parameter = 'com.entelience.esis.SupportNotifier.supportEmail';
UPDATE public.e_preference_descriptions SET description = 'Is support email notification activated.' WHERE parameter = 'com.entelience.esis.feature.SupportNotifier';
UPDATE public.e_preference_descriptions SET description = 'Default FROM address.' WHERE parameter = 'com.entelience.mail.MailHelper.defaultFromAddress';
UPDATE public.e_preference_descriptions SET description = 'Minimum password length.' WHERE parameter = 'com.entelience.esis.security.minPasswordLength';
UPDATE public.e_preference_descriptions SET description = 'Use password complexity.' WHERE parameter = 'com.entelience.esis.security.passwordComplexity';
UPDATE public.e_preference_descriptions SET description = 'Maximum password age in days.' WHERE parameter = 'com.entelience.esis.security.passwordAge';
UPDATE public.e_preference_descriptions SET description = 'Number of password per users saved in history.' WHERE parameter = 'com.entelience.esis.security.passwordHistory';
UPDATE public.e_preference_descriptions SET description = 'Users login history age in days.' WHERE parameter = 'com.entelience.esis.security.loginHistoryAge';
UPDATE public.e_preference_descriptions SET description = 'Number of consecutive failed logins limit that block a user account.' WHERE parameter = 'com.entelience.esis.security.numberOfFailedLoginLimit';
UPDATE public.e_preference_descriptions SET description = 'Time limit (in min) for consecutive failed logins.' WHERE parameter = 'com.entelience.esis.security.failedLoginTimeLimit';
UPDATE public.e_preference_descriptions SET description = 'Activate the Lost Password button to send a new generated password by email or if email isn''t available a application incident.' WHERE parameter = 'com.entelience.esis.security.automatedLostPassword';
UPDATE public.e_preference_descriptions SET description = 'Use system 1st day of week or redefine it.' WHERE parameter = 'com.entelience.provider.calendar.DbCalendar.redefineFirstDayOfWeek';
UPDATE public.e_preference_descriptions SET description = '1st day of week (1=Sunday,7=Saturday).' WHERE parameter = 'com.entelience.provider.calendar.DbCalendar.firstDayOfWeek';
UPDATE public.e_preference_descriptions SET description = 'Application language.' WHERE parameter = 'com.entelience.module.Admin.language';
UPDATE public.e_preference_descriptions SET description = 'Users see elements only if they are in the RACI matrix.' WHERE parameter = 'com.entelience.module.Audit.user_see_my_only';
UPDATE public.e_preference_descriptions SET description = 'Number of delays necessary to mark an action as escaladated.' WHERE parameter = 'com.entelience.module.Audit.escaladeActionAfterNDelays';
UPDATE public.e_preference_descriptions SET description = 'Number of delays necessary to mark a recommendation as escaladated.' WHERE parameter = 'com.entelience.module.Audit.escaladeRecommendationAfterNDelays';
UPDATE public.e_preference_descriptions SET description = 'Hide new products imported by probes.' WHERE parameter = 'com.entelience.esis.feature.hideNewProduct';
UPDATE public.e_preference_descriptions SET description = 'Hide new vendors imported by probes.' WHERE parameter = 'com.entelience.esis.feature.hideNewVendor';
UPDATE public.e_preference_descriptions SET description = 'Report class that will be loaded to get the metrics.' WHERE parameter = 'com.entelience.soap.soapIdentityManagement.IMReportClassName';
UPDATE public.e_preference_descriptions SET description = 'Percentage (metric/target) under which the metric is considered as good.' WHERE parameter = 'com.entelience.esis.im.snail_colors.percent_low';
UPDATE public.e_preference_descriptions SET description = 'Percentage (metric/target) under which the metric is considered as quite good.' WHERE parameter = 'com.entelience.esis.im.snail_colors.percent_medium';
UPDATE public.e_preference_descriptions SET description = 'Percentage (metric/target) under which the metric is considered as meddle.' WHERE parameter = 'com.entelience.esis.im.snail_colors.percent_high';
UPDATE public.e_preference_descriptions SET description = 'Percentage (metric/target) under which the metric is considered as quite bad.' WHERE parameter = 'com.entelience.esis.im.snail_colors.percent_bad';
UPDATE public.e_preference_descriptions SET description = 'Average number of hits per page.' WHERE parameter = 'com.entelience.http.average_hits_per_page';
UPDATE public.e_preference_descriptions SET description = 'Average time spent on 1 web page (in s).' WHERE parameter = 'com.entelience.http.average_time_spent_per_page';
UPDATE public.e_preference_descriptions SET description = 'Number of horizontal grids in line graphs.' WHERE parameter = 'com.entelience.module.Portal.numberOfGridsInChart';
UPDATE public.e_preference_descriptions SET description = 'Is the 0 line displayed in line charts.' WHERE parameter = 'com.entelience.module.Portal.gridFrom0';
UPDATE public.e_preference_descriptions SET description = 'List of Web categories ignored in lists.' WHERE parameter = 'com.entelience.module.Portal.ignoredCategories';
UPDATE public.e_preference_descriptions SET description = 'Are piecharts displayed with a Other part.' WHERE parameter = 'com.entelience.module.Portal.show_others_in_pie';
UPDATE public.e_preference_descriptions SET description = 'Users see elements only if they are in the RACI matrix.' WHERE parameter = 'com.entelience.module.RiskAssessment.user_see_my_only';
UPDATE public.e_preference_descriptions SET description = 'Users see elements only if they are in the RACI matrix.' WHERE parameter = 'com.entelience.module.RiskModelisation.user_see_my_only';
UPDATE public.e_preference_descriptions SET description = 'A vulnerability can get fixed(or won''t fix) only if all its actions are fixed (or won''t fix).' WHERE parameter = 'com.entelience.esis.vrt.actions.actions_fixed_before_vuln_fixed';
UPDATE public.e_preference_descriptions SET description = 'Is it possible to change the decision of a vulnerability if its VRT is closed.' WHERE parameter = 'com.entelience.esis.vrt.closed_vrt_vuln_can_change_decision';
UPDATE public.e_preference_descriptions SET description = 'Users see elements only if they are in the RACI matrix.' WHERE parameter = 'com.entelience.esis.vrt.user_see_my_only';
UPDATE public.e_preference_descriptions SET description = 'Users see elements only if they are in the RACI matrix in the NEW screen.' WHERE parameter = 'com.entelience.esis.vrt.user_see_my_new_only';
UPDATE public.e_preference_descriptions SET description = 'Only used in vote mode where all experts must vote. To avoid vulnerabilities without decision taken due to the absence of an expert, this parameter reprensents the ceiling of votes to give a decision to a vulnerability.' WHERE parameter = 'com.entelience.esis.vrt.vote_ignore_decision_ceiling';
UPDATE public.e_preference_descriptions SET description = 'A voting mode is used to triage the vulnerabilities and ignore them or add them to the next VRT.' WHERE parameter = 'com.entelience.esis.vrt.vote_instead_of_decision';
UPDATE public.e_preference_descriptions SET description = 'In this simplified mode : any vote push the vulnerability in the VRT (so it is a Vote mode, with a ignore decision ceiling to 1), and an action is created for each vote. The vulnerability can be voted until it''s analyzed. In this mode, a vulnerability can be analyzed even if its VRT is not yet started. Triaged vulnerabilities are pushed in the Current VRT (there is no Next VRT). The decision is automatically set to Repair or Ignore, depending of the vote.' WHERE parameter = 'com.entelience.esis.vrt.simplifiedVRTProcess';
UPDATE public.e_preference_descriptions SET description = ' Decisions of voted vulnerabilities can be tuned.' WHERE parameter = 'com.entelience.esis.vrt.votesBasedDecision';
UPDATE public.e_preference_descriptions SET description = 'Decision to be taken for a vulnerability ignored by its votes (table vuln.e_vulnerability_status).' WHERE parameter = 'com.entelience.esis.vrt.votesBasedDecision.IgnoredDecision';
UPDATE public.e_preference_descriptions SET description = 'Decision to be taken for a vulnerability Add to VRT by its votes (table vuln.e_vulnerability_status).' WHERE parameter = 'com.entelience.esis.vrt.votesBasedDecision.AddDecision';
UPDATE public.e_preference_descriptions SET description = 'Only used in vote mode. Only the experts of a vulnerability can vote on a vulnerability.' WHERE parameter = 'com.entelience.esis.vrt.only_experts_can_vote';
UPDATE public.e_preference_descriptions SET description = 'Only used in vote mode. A vulnerability can receive votes until it''s analyzed for the 1st time.' WHERE parameter = 'com.entelience.esis.vrt.can_vote_until_analysis';
UPDATE public.e_preference_descriptions SET description = 'The member of an expert department that votes on a vulnerability prevent the other members of the group to vote for the vulnerability.' WHERE parameter = 'com.entelience.esis.vrt.oneVotePerExpertDepartment';
UPDATE public.e_preference_descriptions SET description = 'An action automatically created for each vote (or triage) on a vulnerability.' WHERE parameter = 'com.entelience.esis.vrt.createActionOnTriage';
UPDATE public.e_preference_descriptions SET description = 'When ignoring a vulnerability, the user has to comment his vote.' WHERE parameter = 'com.entelience.esis.vrt.commentRequiredOnIgnore';
UPDATE public.e_preference_descriptions SET description = 'Triage a a renewed vulnerability always changes the decision.' WHERE parameter = 'com.entelience.esis.vrt.triageOnRenewedVulnOutdoHigherDecision';
UPDATE public.e_preference_descriptions SET description = 'Pattern URL to view a web version of a SecurityFocus advisory.' WHERE parameter = 'com.entelience.provider.vrt.url.securityfocus';
UPDATE public.e_preference_descriptions SET description = 'Pattern URL to view a web version of a Microsoft advisory.' WHERE parameter = 'com.entelience.provider.vrt.url.microsoft';
UPDATE public.e_preference_descriptions SET description = 'Pattern URL to view a web version of a NVD advisory.' WHERE parameter = 'com.entelience.provider.vrt.url.nist';
UPDATE public.e_preference_descriptions SET description = 'Pattern URL to view a web version of a Cert-IST advisory.' WHERE parameter = 'com.entelience.provider.vrt.url.certist';
UPDATE public.e_preference_descriptions SET description = 'Emails are sent to experts of new vulnerabilities.' WHERE parameter = 'com.entelience.esis.feature.notifyNewVulnsForExperts';

UPDATE public.e_raci_object_type SET description = 'Vulnerability' WHERE e_raci_object_type_id = 1;
UPDATE public.e_raci_object_type SET description = 'Action for vulnerability' WHERE e_raci_object_type_id = 2;
UPDATE public.e_raci_object_type SET description = 'VRT meeting' WHERE e_raci_object_type_id = 3;
UPDATE public.e_raci_object_type SET description = 'Module' WHERE e_raci_object_type_id = 4;
UPDATE public.e_raci_object_type SET description = 'Audit' WHERE e_raci_object_type_id = 5;
UPDATE public.e_raci_object_type SET description = 'Audit interview' WHERE e_raci_object_type_id = 6;
UPDATE public.e_raci_object_type SET description = 'Audit document' WHERE e_raci_object_type_id = 7;
UPDATE public.e_raci_object_type SET description = 'Audit recommendation (auditor)' WHERE e_raci_object_type_id = 8;
UPDATE public.e_raci_object_type SET description = 'Audit recommendation (auditee)' WHERE e_raci_object_type_id = 9;
UPDATE public.e_raci_object_type SET description = 'Audit action' WHERE e_raci_object_type_id = 10;
UPDATE public.e_raci_object_type SET description = 'Audit report' WHERE e_raci_object_type_id = 11;
UPDATE public.e_raci_object_type SET description = 'Composite product' WHERE e_raci_object_type_id = 12;
UPDATE public.e_raci_object_type SET description = 'Risk' WHERE e_raci_object_type_id = 13;
UPDATE public.e_raci_object_type SET description = 'Risk review' WHERE e_raci_object_type_id = 14;
UPDATE public.e_raci_object_type SET description = 'Risk control' WHERE e_raci_object_type_id = 15;
UPDATE public.e_raci_object_type SET description = 'Risk action' WHERE e_raci_object_type_id = 16;

UPDATE risk.e_category SET category_name = 'Diseases' WHERE e_category_id = 1;
UPDATE risk.e_category SET category_name = 'Economic' WHERE e_category_id = 2;
UPDATE risk.e_category SET category_name = 'Environmental' WHERE e_category_id = 3;
UPDATE risk.e_category SET category_name = 'Financial' WHERE e_category_id = 4;
UPDATE risk.e_category SET category_name = 'Human' WHERE e_category_id = 5;
UPDATE risk.e_category SET category_name = 'Natural hazard' WHERE e_category_id = 6;
UPDATE risk.e_category SET category_name = 'Health & safety' WHERE e_category_id = 7;
UPDATE risk.e_category SET category_name = 'Product liability' WHERE e_category_id = 8;
UPDATE risk.e_category SET category_name = 'Professional liability' WHERE e_category_id = 9;
UPDATE risk.e_category SET category_name = 'Property damage' WHERE e_category_id = 10;
UPDATE risk.e_category SET category_name = 'Public liability' WHERE e_category_id = 11;
UPDATE risk.e_category SET category_name = 'Security' WHERE e_category_id = 12;
UPDATE risk.e_category SET category_name = 'Technological' WHERE e_category_id = 13;
UPDATE risk.e_risk_decision SET decision = 'Reduction' WHERE e_risk_decision_id = 1;
UPDATE risk.e_risk_decision SET decision = 'Mitigation' WHERE e_risk_decision_id = 2;
UPDATE risk.e_risk_decision SET decision = 'Avoidance' WHERE e_risk_decision_id = 3;
UPDATE risk.e_risk_decision SET decision = 'Transfer' WHERE e_risk_decision_id = 4;
UPDATE risk.e_risk_priority SET priority = 'Minor' WHERE e_risk_priority_id = 1;
UPDATE risk.e_risk_priority SET priority = 'Low' WHERE e_risk_priority_id = 2;
UPDATE risk.e_risk_priority SET priority = 'Normal' WHERE e_risk_priority_id = 3;
UPDATE risk.e_risk_priority SET priority = 'Important' WHERE e_risk_priority_id = 4;
UPDATE risk.e_risk_priority SET priority = 'Urgent' WHERE e_risk_priority_id = 5;
UPDATE risk.e_risk_priority SET priority = 'Critical' WHERE e_risk_priority_id = 6;
UPDATE risk.e_risk_level SET level = 'Low' WHERE e_risk_level_id = 1;
UPDATE risk.e_risk_level SET level = 'Medium' WHERE e_risk_level_id = 2;
UPDATE risk.e_risk_level SET level = 'Significant' WHERE e_risk_level_id = 3;
UPDATE risk.e_risk_level SET level = 'High' WHERE e_risk_level_id = 4;
UPDATE risk.e_action_status SET action_status = 'Planning' WHERE e_action_status_id = 1;
UPDATE risk.e_action_status SET action_status = 'In progress' WHERE e_action_status_id = 2;
UPDATE risk.e_action_status SET action_status = 'Completed' WHERE e_action_status_id = 3;
UPDATE risk.e_action_status SET action_status = 'Cancelled' WHERE e_action_status_id = 4;
UPDATE risk.e_action_status SET action_status = 'Halted' WHERE e_action_status_id = 5;

UPDATE risk.e_likelihood SET name = 'Rare' WHERE e_likelihood_id = 1;
UPDATE risk.e_likelihood SET name = 'Unlikely' WHERE e_likelihood_id = 2;
UPDATE risk.e_likelihood SET name = 'Moderate' WHERE e_likelihood_id = 3;
UPDATE risk.e_likelihood SET name = 'Likely' WHERE e_likelihood_id = 4;
UPDATE risk.e_likelihood SET name = 'Certain' WHERE e_likelihood_id = 5;
UPDATE risk.e_likelihood SET description = 'The event may only occur in exceptional circumstances' WHERE e_likelihood_id = 1;
UPDATE risk.e_likelihood SET description = 'The event could occur at some time' WHERE e_likelihood_id = 2;
UPDATE risk.e_likelihood SET description = 'the event will probably occur at some time' WHERE e_likelihood_id = 3;
UPDATE risk.e_likelihood SET description = 'The event will probably occur in most circumstances' WHERE e_likelihood_id = 4;
UPDATE risk.e_likelihood SET description = 'The event is expected to occur in most circumstances' WHERE e_likelihood_id = 5;
UPDATE risk.e_consequence_level SET label = 'Insignificant' WHERE e_consequence_level_id = 1;
UPDATE risk.e_consequence_level SET label = 'Minor' WHERE e_consequence_level_id = 2;
UPDATE risk.e_consequence_level SET label = 'Moderate' WHERE e_consequence_level_id = 3;
UPDATE risk.e_consequence_level SET label = 'Major' WHERE e_consequence_level_id = 4;
UPDATE risk.e_consequence_level SET label = 'Catastrophic' WHERE e_consequence_level_id = 5;
UPDATE risk.e_consequence_level SET label = 'Insignificant' WHERE e_consequence_level_id = 11;
UPDATE risk.e_consequence_level SET label = 'Minor' WHERE e_consequence_level_id = 12;
UPDATE risk.e_consequence_level SET label = 'Moderate' WHERE e_consequence_level_id = 13;
UPDATE risk.e_consequence_level SET label = 'Major' WHERE e_consequence_level_id = 14;
UPDATE risk.e_consequence_level SET label = 'Outstanding' WHERE e_consequence_level_id = 15;
UPDATE risk.e_consequence_level SET description = 'No injuries, low financial loss' WHERE e_consequence_level_id = 1;
UPDATE risk.e_consequence_level SET description = 'First aid treatment, medium financial loss' WHERE e_consequence_level_id = 2;
UPDATE risk.e_consequence_level SET description = 'Treatment required, high financial loss' WHERE e_consequence_level_id = 3;
UPDATE risk.e_consequence_level SET description = 'Extensive injuries, major financial loss' WHERE e_consequence_level_id = 4;
UPDATE risk.e_consequence_level SET description = 'Death, huge financial loss' WHERE e_consequence_level_id = 5;
UPDATE risk.e_consequence_level SET description = 'Small benefit, low financial gain' WHERE e_consequence_level_id = 11;
UPDATE risk.e_consequence_level SET description = 'Minor improvement, some financial gain' WHERE e_consequence_level_id = 12;
UPDATE risk.e_consequence_level SET description = 'Some enhancements, high financial gain' WHERE e_consequence_level_id = 13;
UPDATE risk.e_consequence_level SET description = 'Great enhancements, major financial gain' WHERE e_consequence_level_id = 14;
UPDATE risk.e_consequence_level SET description = 'Significantly enhanced reputation, huge financial gain' WHERE e_consequence_level_id = 15;

UPDATE sdw.e_operation_state SET state_descr = 'Ready' WHERE e_state_id = 0;
UPDATE sdw.e_operation_state SET state_descr = 'Started' WHERE e_state_id = 1;
UPDATE sdw.e_operation_state SET state_descr = 'Complete' WHERE e_state_id = 2;
UPDATE sdw.e_operation_state SET state_descr = 'Needs undo' WHERE e_state_id = 3;
UPDATE sdw.e_operation_state SET state_descr = 'Undo started' WHERE e_state_id = 4;
UPDATE sdw.e_operation_state SET state_descr = 'Undone' WHERE e_state_id = 5;

UPDATE virus.e_alert_level SET alert_name = 'Normal' WHERE e_alert_level_id = 1;
UPDATE virus.e_alert_level SET alert_name = 'High' WHERE e_alert_level_id = 2;
UPDATE virus.e_alert_level SET alert_name = 'Very high' WHERE e_alert_level_id = 3;
UPDATE virus.e_alert_level SET alert_name = 'Extreme' WHERE e_alert_level_id = 4;
UPDATE virus.t_virus_origin SET origin = 'File' WHERE t_virus_origin_id = 1;
UPDATE virus.t_virus_origin SET origin = 'Mail' WHERE t_virus_origin_id = 2;
UPDATE virus.t_virus_origin SET origin = 'Web' WHERE t_virus_origin_id = 3;
UPDATE virus.t_virus_origin_detail SET detail = 'Local device' WHERE t_virus_origin_detail_id = 1;
UPDATE virus.t_virus_origin_detail SET detail = 'Mobile device' WHERE t_virus_origin_detail_id = 2;
UPDATE virus.t_virus_origin_detail SET detail = 'Network device' WHERE t_virus_origin_detail_id = 3;
UPDATE virus.t_virus_origin_detail SET detail = 'Internal mail' WHERE t_virus_origin_detail_id = 4;
UPDATE virus.t_virus_origin_detail SET detail = 'Incoming mail' WHERE t_virus_origin_detail_id = 5;
UPDATE virus.t_virus_origin_detail SET detail = 'Outgoing mail' WHERE t_virus_origin_detail_id = 6;
UPDATE virus.t_virus_origin_detail SET detail = 'Web' WHERE t_virus_origin_detail_id = 7;

UPDATE vuln.e_vulnerability_severity SET severity_name = 'Unrated' WHERE e_severity_id = 0;
UPDATE vuln.e_vulnerability_severity SET severity_name = 'Low' WHERE e_severity_id = 1;
UPDATE vuln.e_vulnerability_severity SET severity_name = 'Medium' WHERE e_severity_id = 2;
UPDATE vuln.e_vulnerability_severity SET severity_name = 'High' WHERE e_severity_id = 3;
UPDATE vuln.e_vulnerability_severity SET severity_name = 'Critical' WHERE e_severity_id = 4;
UPDATE vuln.e_vulnerability_status SET status_name = 'New' WHERE e_status_id = 0;
UPDATE vuln.e_vulnerability_status SET status_name = 'Repair' WHERE e_status_id = 1;
UPDATE vuln.e_vulnerability_status SET status_name = 'Investigate' WHERE e_status_id = 2;
UPDATE vuln.e_vulnerability_status SET status_name = 'Accept Risk' WHERE e_status_id = 3;
UPDATE vuln.e_vulnerability_status SET status_name = 'Ignore' WHERE e_status_id = 4;
UPDATE vuln.e_vulnerability_priority SET priority_name = 'N/A' WHERE e_priority_id = 0;
UPDATE vuln.e_vulnerability_priority SET priority_name = 'Low' WHERE e_priority_id = 1;
UPDATE vuln.e_vulnerability_priority SET priority_name = 'Medium' WHERE e_priority_id = 2;
UPDATE vuln.e_vulnerability_priority SET priority_name = 'High' WHERE e_priority_id = 3;
UPDATE vuln.e_vulnerability_priority SET priority_name = 'Immediate' WHERE e_priority_id = 4;
UPDATE vuln.e_vulnerability_mav_status SET mav_status_name = 'N/A' WHERE e_mav_status_id = 0;
UPDATE vuln.e_vulnerability_mav_status SET mav_status_name = 'Fixed' WHERE e_mav_status_id = 1;
UPDATE vuln.e_vulnerability_mav_status SET mav_status_name = 'Planning' WHERE e_mav_status_id = 2;
UPDATE vuln.e_vulnerability_mav_status SET mav_status_name = 'In Progress' WHERE e_mav_status_id = 3;
UPDATE vuln.e_vulnerability_mav_status SET mav_status_name = 'Won''t fix' WHERE e_mav_status_id = 4;
UPDATE vuln.e_vulnerability_vote_decision SET vote_decision = 'Vote for Add' WHERE e_vulnerability_vote_decision_id = 0;
UPDATE vuln.e_vulnerability_vote_decision SET vote_decision = 'Vote for Ignore' WHERE e_vulnerability_vote_decision_id = 4;

