INSERT INTO asset.e_asset_type (id, name) VALUES (1, 'Cluster');
INSERT INTO asset.e_asset_type (id, name) VALUES (2, 'Serveur');
INSERT INTO asset.e_asset_type (id, name) VALUES (3, 'Serveur applicatif');
INSERT INTO asset.e_asset_type (id, name) VALUES (4, 'Routeur');
INSERT INTO asset.e_asset_type (id, name) VALUES (5, 'Machine réseau');
INSERT INTO asset.e_asset_type (id, name) VALUES (6, 'Machine sécurité');
INSERT INTO asset.e_asset_type (id, name) VALUES (7, 'Périphérique d''accès');
INSERT INTO asset.e_asset_type (id, name) VALUES (8, 'Périphérique d''accès mobile');
INSERT INTO asset.e_asset_type (id, name) VALUES (9, 'Imprimante');
INSERT INTO asset.e_sc (id, name) VALUES (1, 'Critique pour l''entreprise');
INSERT INTO asset.e_sc (id, name) VALUES (2, 'Nécessaire pour l''entreprise');
INSERT INTO asset.e_sc (id, name) VALUES (3, 'Pour l''entreprise');
INSERT INTO asset.e_sc (id, name) VALUES (4, 'Support pour l''entreprise');
INSERT INTO asset.e_sc (id, name) VALUES (5, 'Infrastructure');
INSERT INTO asset.e_sc (id, name) VALUES (6, 'Non critique pour l''entreprise');
INSERT INTO asset.e_sc (id, name) VALUES (7, 'Non lié à l''entreprise');
INSERT INTO asset.e_bl (id, name) VALUES (1, 'TI');
INSERT INTO asset.e_bl (id, name) VALUES (2, 'Corporate');
INSERT INTO asset.e_bl (id, name) VALUES (3, 'Ventes');
INSERT INTO asset.e_bl (id, name) VALUES (4, 'Marketing');
INSERT INTO asset.e_bl (id, name) VALUES (5, 'R&D');
INSERT INTO asset.e_bl (id, name) VALUES (6, 'Production');
INSERT INTO asset.e_bl (id, name) VALUES (7, 'Comptabilité');
INSERT INTO asset.e_bl (id, name) VALUES (8, 'Financement');
INSERT INTO asset.e_bl (id, name) VALUES (9, 'Domaines');
INSERT INTO asset.e_bl (id, name) VALUES (10, 'Partenaires de travail');
INSERT INTO asset.e_availability (id, name) VALUES (1, 'Ininterrompu');
INSERT INTO asset.e_availability (id, name) VALUES (2, 'Haute disponibilité');
INSERT INTO asset.e_availability (id, name) VALUES (3, '99%');
INSERT INTO asset.e_availability (id, name) VALUES (4, 'Horaires de travail');
INSERT INTO asset.e_availability (id, name) VALUES (5, 'Meilleur effort');

INSERT INTO audit.e_audit_rec_status (e_audit_rec_status_id, rec_status) VALUES (1, 'Ouvert');
INSERT INTO audit.e_audit_rec_status (e_audit_rec_status_id, rec_status) VALUES (2, 'Fermé');
INSERT INTO audit.e_audit_rec_status (e_audit_rec_status_id, rec_status) VALUES (3, 'Risque accepté');
INSERT INTO audit.e_audit_rec_status (e_audit_rec_status_id, rec_status) VALUES (4, 'Dupliqué');
INSERT INTO audit.e_audit_severity (e_audit_severity_id, severity) VALUES (1, 'Faible');
INSERT INTO audit.e_audit_severity (e_audit_severity_id, severity) VALUES (2, 'Moyenne');
INSERT INTO audit.e_audit_severity (e_audit_severity_id, severity) VALUES (3, 'Elevée');
INSERT INTO audit.e_audit_topic (e_audit_topic_id, topic) VALUES (1, 'Sécurité réseau');
INSERT INTO audit.e_audit_topic (e_audit_topic_id, topic) VALUES (2, 'Sûrété physique');
INSERT INTO audit.e_audit_topic (e_audit_topic_id, topic) VALUES (3, 'Sécurité système');
INSERT INTO audit.e_audit_topic (e_audit_topic_id, topic) VALUES (4, 'Accès');
INSERT INTO audit.e_audit_topic (e_audit_topic_id, topic) VALUES (5, 'Applications');
INSERT INTO audit.e_audit_topic (e_audit_topic_id, topic) VALUES (6, 'Business');
INSERT INTO audit.e_audit_topic (e_audit_topic_id, topic) VALUES (7, 'Autres');
INSERT INTO audit.e_audit_origin (e_audit_origin_id, origin) VALUES (1, 'Audit interne');
INSERT INTO audit.e_audit_origin (e_audit_origin_id, origin) VALUES (2, 'Audit externe');
INSERT INTO audit.e_audit_origin (e_audit_origin_id, origin) VALUES (3, 'Régulateurs');
INSERT INTO audit.e_audit_origin (e_audit_origin_id, origin) VALUES (4, 'Auto-audit');
INSERT INTO audit.e_audit_action_status (e_audit_action_status_id, action_status) VALUES (1, 'Planifié');
INSERT INTO audit.e_audit_action_status (e_audit_action_status_id, action_status) VALUES (2, 'En cours');
INSERT INTO audit.e_audit_action_status (e_audit_action_status_id, action_status) VALUES (3, 'Finalisé');
INSERT INTO audit.e_audit_action_status (e_audit_action_status_id, action_status) VALUES (4, 'Annulé');
INSERT INTO audit.e_audit_action_status (e_audit_action_status_id, action_status) VALUES (5, 'En pause');
INSERT INTO audit.e_audit_priority (e_audit_priority_id, priority) VALUES (1, 'Faible');
INSERT INTO audit.e_audit_priority (e_audit_priority_id, priority) VALUES (2, 'Moyenne');
INSERT INTO audit.e_audit_priority (e_audit_priority_id, priority) VALUES (3, 'Elevée');
INSERT INTO audit.e_audit_rec_topic (e_audit_rec_topic_id, topic) VALUES (1, 'Accès');
INSERT INTO audit.e_audit_rec_topic (e_audit_rec_topic_id, topic) VALUES (2, 'Réseau');
INSERT INTO audit.e_audit_rec_topic (e_audit_rec_topic_id, topic) VALUES (3, 'Locaux');
INSERT INTO audit.e_audit_rec_topic (e_audit_rec_topic_id, topic) VALUES (4, 'Gestion');
INSERT INTO audit.e_audit_rec_topic (e_audit_rec_topic_id, topic) VALUES (5, 'Globale');
INSERT INTO audit.e_audit_rec_topic (e_audit_rec_topic_id, topic) VALUES (6, 'Veille');
INSERT INTO audit.e_audit_rec_topic (e_audit_rec_topic_id, topic) VALUES (7, 'Connaissances');
INSERT INTO audit.e_audit_confidentiality (e_audit_confidentiality_id, confidentiality) VALUES (1, 'Interne');
INSERT INTO audit.e_audit_confidentiality (e_audit_confidentiality_id, confidentiality) VALUES (2, 'Confidentiel');
INSERT INTO audit.e_audit_confidentiality (e_audit_confidentiality_id, confidentiality) VALUES (3, 'Responsable seul');
INSERT INTO audit.e_audit_confidentiality (e_audit_confidentiality_id, confidentiality) VALUES (4, 'Secret d''entreprise');
INSERT INTO audit.e_audit_status (e_audit_status_id, status) VALUES (1, 'Planifié');
INSERT INTO audit.e_audit_status (e_audit_status_id, status) VALUES (2, 'Prestations');
INSERT INTO audit.e_audit_status (e_audit_status_id, status) VALUES (3, 'Entretiens');
INSERT INTO audit.e_audit_status (e_audit_status_id, status) VALUES (4, 'Réunion d''ouverture');
INSERT INTO audit.e_audit_status (e_audit_status_id, status) VALUES (5, 'Premier rapport');
INSERT INTO audit.e_audit_status (e_audit_status_id, status) VALUES (6, 'Rapport final');
INSERT INTO audit.e_audit_status (e_audit_status_id, status) VALUES (7, 'Réunion de clôture');
INSERT INTO audit.e_audit_status (e_audit_status_id, status) VALUES (8, 'Remédiation');
INSERT INTO audit.e_audit_status (e_audit_status_id, status) VALUES (9, 'Fermé');
INSERT INTO audit.e_audit_report_status (e_audit_report_status_id, report_status) VALUES (1, 'Ebauche');
INSERT INTO audit.e_audit_report_status (e_audit_report_status_id, report_status) VALUES (2, 'Finalisé');
INSERT INTO audit.e_audit_report_status (e_audit_report_status_id, report_status) VALUES (3, 'Approuvé');
INSERT INTO audit.e_audit_report_status (e_audit_report_status_id, report_status) VALUES (4, 'Publié');
INSERT INTO audit.e_audit_document_type (e_audit_document_type_id, document_type) VALUES (1, 'Preuve');
INSERT INTO audit.e_audit_document_type (e_audit_document_type_id, document_type) VALUES (2, 'Information');
INSERT INTO audit.e_audit_document_type (e_audit_document_type_id, document_type) VALUES (3, 'Email');
INSERT INTO audit.e_audit_document_type (e_audit_document_type_id, document_type) VALUES (4, 'Document');

INSERT INTO compliance.e_standard_category (e_standard_category_id, standard_category) VALUES (1, 'Technologies de l''information');
INSERT INTO compliance.e_standard_category (e_standard_category_id, standard_category) VALUES (2, 'Gestion globale');
INSERT INTO compliance.e_topic_category (e_topic_category_id, topic_category) VALUES (1, 'Gestion de la sécurité');
INSERT INTO compliance.e_topic_category (e_topic_category_id, topic_category) VALUES (2, 'Contrôle des accès');
INSERT INTO compliance.e_compliance_kind (e_compliance_kind_id, kind) VALUES (1, 'Remarque d''application');
INSERT INTO compliance.e_compliance_kind (e_compliance_kind_id, kind) VALUES (2, 'Remarque documentaire');
INSERT INTO compliance.e_compliance_type (e_compliance_type_id, compliance_type) VALUES (1, 'Non conformité mineure d''une application');
INSERT INTO compliance.e_compliance_type (e_compliance_type_id, compliance_type) VALUES (2, 'Non conformité mineure documentaire');
INSERT INTO compliance.e_compliance_type (e_compliance_type_id, compliance_type) VALUES (3, 'Non conformité majeure d''une application');
INSERT INTO compliance.e_compliance_type (e_compliance_type_id, compliance_type) VALUES (4, 'Non conformité majeure documentaire');

INSERT INTO mim.t_user_anomaly (t_user_anomaly_id, description) VALUES (1, 'None');
INSERT INTO mim.t_user_anomaly (t_user_anomaly_id, description) VALUES (2, 'Fudge : mainframe data missing');
INSERT INTO mim.t_user_anomaly (t_user_anomaly_id, description) VALUES (3, 'Fudge : mainframe date security admin missing');
INSERT INTO mim.t_user_anomaly (t_user_anomaly_id, description) VALUES (4, 'Fudge : mainframe datecontractvalidity abnormal');
INSERT INTO mim.t_user_anomaly (t_user_anomaly_id, description) VALUES (5, 'Fudge : mainframe date1sthire bad');
INSERT INTO mim.t_user_anomaly (t_user_anomaly_id, description) VALUES (6, 'Fudge : mainframe ou bad');
INSERT INTO mim.t_user_anomaly (t_user_anomaly_id, description) VALUES (7, 'Fudge : mainframe l bad');
INSERT INTO mim.t_user_anomaly (t_user_anomaly_id, description) VALUES (8, 'Fudge : ad data missing');
INSERT INTO mim.t_user_anomaly (t_user_anomaly_id, description) VALUES (9, 'Fudge : ad date is 0');
INSERT INTO mim.t_user_anomaly (t_user_anomaly_id, description) VALUES (10, 'Fudge : hr data missing');
INSERT INTO mim.t_user_anomaly (t_user_anomaly_id, description) VALUES (11, 'Fudge : hr logoncount missing');
INSERT INTO mim.t_user_anomaly (t_user_anomaly_id, description) VALUES (12, 'Fudge : hr still has 19000000 as dates');
INSERT INTO mim.t_user_anomaly (t_user_anomaly_id, description) VALUES (13, 'Fudge : hr still has 19800101 as dates');

INSERT INTO itops.t_alert_severity (t_alert_severity_id, severity_name) VALUES (1, 'Information');
INSERT INTO itops.t_alert_severity (t_alert_severity_id, severity_name) VALUES (2, 'Avertissement');
INSERT INTO itops.t_alert_severity (t_alert_severity_id, severity_name) VALUES (3, 'Critique');
INSERT INTO itops.t_alert_priority (t_alert_priority_id, priority_name) VALUES (1, 'Bas');
INSERT INTO itops.t_alert_priority (t_alert_priority_id, priority_name) VALUES (2, 'Moyen');
INSERT INTO itops.t_alert_priority (t_alert_priority_id, priority_name) VALUES (3, 'Haut');
INSERT INTO itops.t_event_level (t_event_level_id, event_level) VALUES (1, 'Succès');
INSERT INTO itops.t_event_level (t_event_level_id, event_level) VALUES (2, 'Erreur');
INSERT INTO itops.t_event_level (t_event_level_id, event_level) VALUES (3, 'Avertissement');
INSERT INTO itops.t_event_level (t_event_level_id, event_level) VALUES (4, 'Information');
INSERT INTO itops.t_event_level (t_event_level_id, event_level) VALUES (5, 'Succès de l''audit');
INSERT INTO itops.t_event_level (t_event_level_id, event_level) VALUES (6, 'Echec de l''audit');

INSERT INTO public.e_file_states (id, state_name) VALUES (-4, 'Abandon, données incohérentes');
INSERT INTO public.e_file_states (id, state_name) VALUES (-3, 'Abandon');
INSERT INTO public.e_file_states (id, state_name) VALUES (-2, 'Téléchargement');
INSERT INTO public.e_file_states (id, state_name) VALUES (-1, 'En cours');
INSERT INTO public.e_file_states (id, state_name) VALUES (0, 'Prêt');
INSERT INTO public.e_file_states (id, state_name) VALUES (1, 'Réussite');
INSERT INTO public.e_file_states (id, state_name) VALUES (2, 'Echec à reéssayer');
INSERT INTO public.e_file_states (id, state_name) VALUES (3, 'Echec permanent');
INSERT INTO public.e_file_states (id, state_name) VALUES (4, 'Ignoré');
INSERT INTO public.e_file_states (id, state_name) VALUES (5, 'Remplacé');
INSERT INTO public.e_file_states (id, state_name) VALUES (6, 'Dupliqué');
INSERT INTO public.e_file_states (id, state_name) VALUES (7, 'Réussite + Archivé');
INSERT INTO public.e_file_states (id, state_name) VALUES (8, 'Remplacé + Archivé');
INSERT INTO public.e_file_states (id, state_name) VALUES (9, 'Dupliqué + Archivé');
INSERT INTO public.e_file_states (id, state_name) VALUES (10, 'Echec permanent + Archivé');
INSERT INTO public.e_file_states (id, state_name) VALUES (11, 'Ignoré + Archivé');
INSERT INTO public.e_probe_parameter_origin (e_probe_parameter_origin_id, origin) VALUES (1, 'Valeur par défaut');
INSERT INTO public.e_probe_parameter_origin (e_probe_parameter_origin_id, origin) VALUES (2, 'Base de données');
INSERT INTO public.e_probe_parameter_origin (e_probe_parameter_origin_id, origin) VALUES (3, 'Fichier XML');
INSERT INTO public.e_probe_run_status (e_probe_run_status_id, status_name) VALUES (0, 'Jamais lancée');
INSERT INTO public.e_probe_run_status (e_probe_run_status_id, status_name) VALUES (1, 'Succes');
INSERT INTO public.e_probe_run_status (e_probe_run_status_id, status_name) VALUES (2, 'Pas de données importées');
INSERT INTO public.e_probe_run_status (e_probe_run_status_id, status_name) VALUES (3, 'Annulée');
INSERT INTO public.e_probe_run_status (e_probe_run_status_id, status_name) VALUES (4, 'Echouée');
INSERT INTO public.e_probe_run_status (e_probe_run_status_id, status_name) VALUES (5, 'Erreur');
INSERT INTO public.e_probe_run_status (e_probe_run_status_id, status_name) VALUES (6, 'En cours d''exécution');
INSERT INTO public.e_probe_run_status (e_probe_run_status_id, status_name) VALUES (7, 'Annulée avec erreur');

INSERT INTO asset.e_product_type (id, name) VALUES (1, 'Logiciel');
INSERT INTO asset.e_product_type (id, name) VALUES (2, 'Matériel');
INSERT INTO asset.e_product_type (id, name) VALUES (3, 'Appareil');
INSERT INTO asset.e_preferred_relationship (id, name) VALUES (1, 'Associé stratégique');
INSERT INTO asset.e_preferred_relationship (id, name) VALUES (2, 'Associé');
INSERT INTO asset.e_preferred_relationship (id, name) VALUES (3, 'Fournisseur');
INSERT INTO asset.e_preferred_relationship (id, name) VALUES (4, 'Pas de relation');

INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.rootDir', 'Répertoire principal.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.errorsDir', 'Répertoire des erreurs concernant les fichiers incorrects.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.errorsSize', 'Taille maximale du répertoire des erreurs.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.reportsDir', 'Répertoire de stockage des rapports.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.defaultCompany', 'Nom d''entreprise par défaut.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.poweredByLogo', 'Chemin vers le logo poweredBy.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.web.localServerPort', 'Port de Tomcat.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.web.localServerAddress', 'Adresse locale du serveur.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.web.remoteServerProtocol', 'Protocole.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.mail.MailHelper.hostName', 'Nom d''hôte du serveur SMTP.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.mail.MailHelper.hostPort', 'Port du serveur SMTP.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.mail.MailHelper.useTls', 'Usage d''une sécurisation (TLS, SSL) sur le serveur SMTP.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.mail.MailHelper.useAuth', 'Usage d''une authentification sur le serveur SMTP.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.mail.MailHelper.smtpUser', 'Utilisateur SMTP.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.feature.attachCalendarFile', 'Attacher un fichier iCal aux emails générés.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.mail.MailHelper.smtpPassword', 'Mot de passe SMTP.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.mail.MailHelper.maxTries', 'Nombre d''essais avant l''échec de l''envoi d''un email.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.mail.MailHelper.maxEmailSentAtOnce', 'Nombre d''emails maximum à envoyer par lot.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.mail.MailHelper.iconLocation', 'Chemin vers le logo de l''entreprise.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.soap.SessionHandler.timeoutMinutes', 'Durée de la session en minutes.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.soap.soapBase.authMethod', 'Méthode d''authentification.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.maxReturnedRows', 'Nombre maximum d''élements retournés par une grille de données par défaut.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.soap.auth.LDAP.base', 'Base pour l''authetification LDAP.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.soap.auth.LDAP.baseFilterString', 'Filtre de base pour l''authetification LDAP.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.soap.auth.LDAP.userNameField', 'Nom d''utilisateur pour l''authentification LDAP.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.soap.auth.LDAP.url', 'URL pour l''authentification LDAP.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.soap.auth.LDAP.searchUserName', 'Search user name pour l''authentification LDAP.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.soap.auth.LDAP.searchPassword', 'Mot de passe pour l''authentification LDAP.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpHelper.userAgent', 'Agent utilisateur pour le protocol HTTP.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpHelper.useProxy', 'Utilisation d''un proxy pour la connexion HTTP.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpHelper.proxyHost', 'Nom d''hôte du proxy HTTP.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpHelper.proxyPort', 'Port du proxy HTTP.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpHelper.useProxyAuth', 'Utilisation d''une authentification pour le proxy HTTP.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpHelper.proxyRealm', 'Realm authentification pour le proxy HTTP.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpHelper.proxyScheme', 'Scheme authentification pour le proxy HTTP.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpHelper.proxyUserName', 'Nom d''utilisateur pour le proxy HTTP.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpHelper.proxyPassword', 'Mot de passe pour le proxy HTTP.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpSslHelper.userAgent', 'Agent utilisateur pour le protocol HTTPS.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpSslHelper.useProxy', 'Utilisation d''un proxy pour la connexion HTTPS.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpSslHelper.proxyHost', 'Nom d''hôte du proxy HTTPS.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpSslHelper.proxyPort', 'Port du proxy HTTPS.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpSslHelper.useProxyAuth', 'Utilisation d''une authentification pour le proxy HTTPS.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpSslHelper.proxyRealm', 'Realm authentification pour le proxy HTTPS.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpSslHelper.proxyScheme', 'Scheme authentification pour le proxy HTTPS.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpSslHelper.proxyUserName', 'Nom d''utilisateur du proxy HTTPS.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpSslHelper.proxyPassword', 'Mot de passe du proxy HTTPS.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpSslHelper.keyStore', 'Fichier de certificats (keystore) pour HTTPS.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpSslHelper.keyStorePassword', 'Mot de passe pour le fichier de certificats (keystore) pour HTTPS.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.license.LicenseHelper.publicStore', 'Répertoire public pour l''authentification des licences.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.raci.strict_RACI', 'RACI mode strict.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.cnilLevel', 'Niveau CNIL.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.logDirectory', 'Chemin du répertoir contenant les fichiers log.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.probeXmlFile', 'Chemin vers le XML de définition des sondes.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.probes.showProbeSnailOnLastNDays', 'Période maximale par défaut pour vérifier l''exécution des sondes.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.module.Admin.can_edit_its_own_expertises', 'Les utilisateurs peuvent éditer leurs expertises propres.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.feature.notifyMail', 'Activation de la notification par email.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.feature.notifySelfMail', 'Activation de la notification par email pour sa propre adresse email.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.feature.attachHtmlMail', 'Générer des emails HTML.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.feature.sendEmailOnExpertiseChange', 'Envoyer un email lors du changement d''une expertise.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.feature.sendEmailOnRACIChange', 'Envoyer un email lors du changement d''une matrice RACI.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.feature.sendEmailOnObjectModification', 'Envoyer un email lorsque un objet, un élément est modifié.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.feature.sendEmailOnObjectCreation', 'Envoyer un email lors de la création d''un objet, d''un élément.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.mail.MailHelper.receiveEmailOnChange', 'Niveau de la matrice RACI nécessaire pour recevoir les emails.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.raci.delayRaciChangeOnModule', 'Retarder les changements de matrice RACI pour vérification.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.SupportNotifier.supportEmail', 'Email du support.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.feature.SupportNotifier', 'Activer la notification au support.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.mail.MailHelper.defaultFromAddress', 'Adresse DE par défaut dans les emails.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.security.minPasswordLength', 'Taille minimale du mot de passe.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.security.passwordComplexity', 'Utiliser les règles de complexité sur les mots de passe.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.security.passwordAge', 'Durée de vie maximum d''un mot de passe en jours.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.security.passwordHistory', 'Nombre de mot de passe stockés dans l''historique pour chaque utilisateur.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.security.loginHistoryAge', 'Durée maximale en jours de la dernière connexion utilisateur.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.security.numberOfFailedLoginLimit', 'Nombre d''échec de connexion utilisateur avant blocage du compte.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.security.failedLoginTimeLimit', 'Durée limite en minutes entre échecs de connexion utilisateur.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.security.automatedLostPassword', 'Active le bouton Mot de passe perdu qui permet de recevoir un nouveau mot de passe par email ou si l''utilisateur n''a pas d''email de générer un incident de l''application.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.provider.calendar.DbCalendar.redefineFirstDayOfWeek', 'Redefinir le premier jour de la semain (ou utiliser le jour par défaut du système).');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.provider.calendar.DbCalendar.firstDayOfWeek', 'Premier jour de la semaine (1=Dimanche,7=Samedi).');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.module.Admin.language', 'Langue de l''application.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.module.Audit.user_see_my_only', 'Les utilisateurs ne peuvent voir un élément que s''ils sont dans la matrice RACI liée.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.module.Audit.escaladeActionAfterNDelays', 'Nombre de reports avant de noter une action comme trop repoussée.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.module.Audit.escaladeRecommendationAfterNDelays', 'Nombre de reports avant de noter une recommandation comme trop repoussée.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.feature.hideNewProduct', 'Masquer les nouveaux produits importés par les sondes.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.feature.hideNewVendor', 'Masquer les nouveaux fournisseurs, vendeurs importés par les sondes.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.soap.soapIdentityManagement.IMReportClassName', 'Classe de rapport chargée pour obtenir les métriques.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.im.snail_colors.percent_low', 'Pourcentage entre métrique et cible sous lequel le métrique est considéré comme bon.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.im.snail_colors.percent_medium', 'Pourcentage entre métrique et cible sous lequel le métrique est considéré comme assez bon.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.im.snail_colors.percent_high', 'Pourcentage entre métrique et cible sous lequel le métrique est considéré comme moyen.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.im.snail_colors.percent_bad', 'Pourcentage entre métrique et cible sous lequel le métrique est considéré comme mauvais.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.http.average_hits_per_page', 'Nombre moyen de requêtes (hits) par page.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.http.average_time_spent_per_page', 'Temps moyen passé sur une page en secondes.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.module.Portal.numberOfGridsInChart', 'Nombre de données sur l''axe Y pour les graphiques en lignes.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.module.Portal.gridFrom0', 'Afficher les valeurs à partir de 0 dans les graphiques en lignes.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.module.Portal.ignoredCategories', 'Afficher les catégories Internet ignorées dans les listes.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.module.Portal.show_others_in_pie', 'Afficher la partie Autres données dans les graphiques camemberts.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.module.RiskAssessment.user_see_my_only', 'Les utilisateurs ne peuvent voir un élément que s''ils sont dans la matrice RACI liée.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.module.RiskModelisation.user_see_my_only', 'Les utilisateurs ne peuvent voir un élément que s''ils sont dans la matrice RACI liée.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.vrt.actions.actions_fixed_before_vuln_fixed', 'Une vulnérabilité peut être corrigée (ou non-corrigée) que si toutes ses actions sont dans un statut corrigé (ou non-corrigé).');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.vrt.closed_vrt_vuln_can_change_decision', 'La décision appliquée à une vulnérabilité peut être modifiée même dans un regroupement de vulnérabilité fermé.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.vrt.user_see_my_only', 'Les utilisateurs ne peuvent voir un élément que s''ils sont dans la matrice RACI liée.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.vrt.user_see_my_new_only', 'Spécifique à l''écran des nouvelles vulnérabilités: les utilisateurs ne peuvent voir un élément que s''ils sont dans la matrice RACI liée.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.vrt.vote_ignore_decision_ceiling', 'Seulement actif en mode Vote quand tous les experts doivent voter. C''est le nombre minimal de vote nécessaire pour activer la décision sur une vulnérabilité.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.vrt.vote_instead_of_decision', 'Activation du mode Vote pour trier les vulnérabilités et les regrouper.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.vrt.simplifiedVRTProcess', 'Activation du mode Vote Simplifié: dès le premier vote la vulnérabilité est placée dans un regroupement existant et peut recevoir des votes jusqu''à son analyse. Note: une action est générée pour chaque vote sur une vulnérabilité. La vulnérabilité peut être analysée même si son regroupement n''a pas été démarré. La décision appliquée à la vulnérabilité est automatiquement mise en réparation ou ignorée en fonction du type de vote.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.vrt.votesBasedDecision', 'La décision des vulnérabilités votées peut être modifiée.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.vrt.votesBasedDecision.IgnoredDecision', 'Décision par défaut utilisée pour une vulnérabilité recevant ignoré en vote (table vuln.e_vulnerability_status).');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.vrt.votesBasedDecision.AddDecision', 'Décision par défaut utilisée pour une vulnérabilité ajoutée à un regroupement suite à un vote (table vuln.e_vulnerability_status).');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.vrt.only_experts_can_vote', 'Seulement actif en mode Vote. Seuls les experts pour cette vulnérabilité peuvent voter.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.vrt.can_vote_until_analysis', 'Seulement actif en mode Vote. Une vulnérabilité peut recevoir des votes jusqu''à son analyse.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.vrt.oneVotePerExpertDepartment', 'Le membre d''un département de l''entreprise expert pour un type de vulnérabilité evite aux autres membres de voter.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.vrt.createActionOnTriage', 'Création d''une action lors d''un vote (ou d''un tri) sur une vulnérabilité.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.vrt.commentRequiredOnIgnore', 'Lorsqu''une vulnérabilité est ignorée, l''utilisateur doit commenter son action.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.vrt.triageOnRenewedVulnOutdoHigherDecision', 'Le tri d''une vulnerabilité réouverte change sa décision.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.provider.vrt.url.securityfocus', 'Modèle d''URL pour accéder à la version web des données de vulnérabilités SecurityFocus.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.provider.vrt.url.microsoft', 'Modèle d''URL pour accéder à la version web des données de vulnérabilités Microsoft.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.provider.vrt.url.nist', 'Modèle d''URL pour accéder à la version web des données de vulnérabilités NVD.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.provider.vrt.url.certist', 'Modèle d''URL pour accéder à la version web des données de vulnérabilités Cert-IST.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.feature.notifyNewVulnsForExperts', 'Emails envoyés aux experts concernés par des nouvelles vulnérabiltés.');

INSERT INTO risk.e_category (e_category_id, category_name) VALUES (1, 'Maladies');
INSERT INTO risk.e_category (e_category_id, category_name) VALUES (2, 'Economique');
INSERT INTO risk.e_category (e_category_id, category_name) VALUES (3, 'Environnemental');
INSERT INTO risk.e_category (e_category_id, category_name) VALUES (4, 'Financier');
INSERT INTO risk.e_category (e_category_id, category_name) VALUES (5, 'Humain');
INSERT INTO risk.e_category (e_category_id, category_name) VALUES (6, 'Naturel');
INSERT INTO risk.e_category (e_category_id, category_name) VALUES (7, 'Santé');
INSERT INTO risk.e_category (e_category_id, category_name) VALUES (8, 'Responsabilité produit');
INSERT INTO risk.e_category (e_category_id, category_name) VALUES (9, 'Responsabilité professionnelle');
INSERT INTO risk.e_category (e_category_id, category_name) VALUES (10, 'Dégâts matériels');
INSERT INTO risk.e_category (e_category_id, category_name) VALUES (11, 'Responsabilité publique');
INSERT INTO risk.e_category (e_category_id, category_name) VALUES (12, 'Sécurité');
INSERT INTO risk.e_category (e_category_id, category_name) VALUES (13, 'Technologique');
INSERT INTO risk.e_risk_decision (e_risk_decision_id, decision) VALUES (1, 'Réduction');
INSERT INTO risk.e_risk_decision (e_risk_decision_id, decision) VALUES (2, 'Atténuation');
INSERT INTO risk.e_risk_decision (e_risk_decision_id, decision) VALUES (3, 'Eviter');
INSERT INTO risk.e_risk_decision (e_risk_decision_id, decision) VALUES (4, 'Transfert');
INSERT INTO risk.e_risk_priority (e_risk_priority_id, priority) VALUES (1, 'Mineur');
INSERT INTO risk.e_risk_priority (e_risk_priority_id, priority) VALUES (2, 'Faible');
INSERT INTO risk.e_risk_priority (e_risk_priority_id, priority) VALUES (3, 'Normal');
INSERT INTO risk.e_risk_priority (e_risk_priority_id, priority) VALUES (4, 'Important');
INSERT INTO risk.e_risk_priority (e_risk_priority_id, priority) VALUES (5, 'Urgent');
INSERT INTO risk.e_risk_priority (e_risk_priority_id, priority) VALUES (6, 'Critique');
INSERT INTO risk.e_risk_level (e_risk_level_id, level) VALUES (1, 'Faible');
INSERT INTO risk.e_risk_level (e_risk_level_id, level) VALUES (2, 'Moyen');
INSERT INTO risk.e_risk_level (e_risk_level_id, level) VALUES (3, 'Significatif');
INSERT INTO risk.e_risk_level (e_risk_level_id, level) VALUES (4, 'Elevé');
INSERT INTO risk.e_action_status (e_action_status_id, action_status) VALUES (1, 'Planifié');
INSERT INTO risk.e_action_status (e_action_status_id, action_status) VALUES (2, 'En cours');
INSERT INTO risk.e_action_status (e_action_status_id, action_status) VALUES (3, 'Finalisé');
INSERT INTO risk.e_action_status (e_action_status_id, action_status) VALUES (4, 'Annulé');
INSERT INTO risk.e_action_status (e_action_status_id, action_status) VALUES (5, 'En pause');

INSERT INTO sdw.e_operation_state (e_state_id, state_descr) VALUES (0, 'Prêt');
INSERT INTO sdw.e_operation_state (e_state_id, state_descr) VALUES (1, 'Démarré');
INSERT INTO sdw.e_operation_state (e_state_id, state_descr) VALUES (2, 'Fini');
INSERT INTO sdw.e_operation_state (e_state_id, state_descr) VALUES (3, 'Besion d''annulation');
INSERT INTO sdw.e_operation_state (e_state_id, state_descr) VALUES (4, 'Annulation démarrée');
INSERT INTO sdw.e_operation_state (e_state_id, state_descr) VALUES (5, 'Annulé');

INSERT INTO vuln.e_vulnerability_severity (e_severity_id, severity_name) VALUES (0, 'Non évaluée');
INSERT INTO vuln.e_vulnerability_severity (e_severity_id, severity_name) VALUES (1, 'Faible');
INSERT INTO vuln.e_vulnerability_severity (e_severity_id, severity_name) VALUES (2, 'Moyenne');
INSERT INTO vuln.e_vulnerability_severity (e_severity_id, severity_name) VALUES (3, 'Elevée');
INSERT INTO vuln.e_vulnerability_severity (e_severity_id, severity_name) VALUES (4, 'Très élevée');
INSERT INTO vuln.e_vulnerability_status (e_status_id, status_name) VALUES (0, 'Nouveauté');
INSERT INTO vuln.e_vulnerability_status (e_status_id, status_name) VALUES (1, 'A corriger');
INSERT INTO vuln.e_vulnerability_status (e_status_id, status_name) VALUES (2, 'A étudier');
INSERT INTO vuln.e_vulnerability_status (e_status_id, status_name) VALUES (3, 'Risque accepté');
INSERT INTO vuln.e_vulnerability_status (e_status_id, status_name) VALUES (4, 'Non impacté');
INSERT INTO vuln.e_vulnerability_priority (e_priority_id, priority_name) VALUES (0, 'Non évaluée');
INSERT INTO vuln.e_vulnerability_priority (e_priority_id, priority_name) VALUES (1, 'Faible');
INSERT INTO vuln.e_vulnerability_priority (e_priority_id, priority_name) VALUES (2, 'Moyenne');
INSERT INTO vuln.e_vulnerability_priority (e_priority_id, priority_name) VALUES (3, 'Elevée');
INSERT INTO vuln.e_vulnerability_priority (e_priority_id, priority_name) VALUES (4, 'Très élevée');
INSERT INTO vuln.e_vulnerability_mav_status (e_mav_status_id, mav_status_name) VALUES (0, 'Non défini');
INSERT INTO vuln.e_vulnerability_mav_status (e_mav_status_id, mav_status_name) VALUES (1, 'Corrigé');
INSERT INTO vuln.e_vulnerability_mav_status (e_mav_status_id, mav_status_name) VALUES (2, 'Planifié');
INSERT INTO vuln.e_vulnerability_mav_status (e_mav_status_id, mav_status_name) VALUES (3, 'En cours d''intégration');
INSERT INTO vuln.e_vulnerability_mav_status (e_mav_status_id, mav_status_name) VALUES (4, 'Non corrigé');
INSERT INTO vuln.e_vulnerability_vote_decision (e_vulnerability_vote_decision_id, vote_decision) VALUES (0, 'Impacté');
INSERT INTO vuln.e_vulnerability_vote_decision (e_vulnerability_vote_decision_id, vote_decision) VALUES (4, 'Non impacté');

UPDATE public.e_raci_object_type SET description = 'Avis de vulnérabilité' WHERE e_raci_object_type_id = 1;
UPDATE public.e_raci_object_type SET description = 'Action pour avis de vulnérabilité' WHERE e_raci_object_type_id = 2;
UPDATE public.e_raci_object_type SET description = 'Réunion VRT' WHERE e_raci_object_type_id = 3;
UPDATE public.e_raci_object_type SET description = 'Module' WHERE e_raci_object_type_id = 4;
UPDATE public.e_raci_object_type SET description = 'Audit' WHERE e_raci_object_type_id = 5;
UPDATE public.e_raci_object_type SET description = 'Interview d''audit' WHERE e_raci_object_type_id = 6;
UPDATE public.e_raci_object_type SET description = 'Document d''audit' WHERE e_raci_object_type_id = 7;
UPDATE public.e_raci_object_type SET description = 'Recommandation d''audit (auditeur)' WHERE e_raci_object_type_id = 8;
UPDATE public.e_raci_object_type SET description = 'Recommandation d''audit (audité)' WHERE e_raci_object_type_id = 9;
UPDATE public.e_raci_object_type SET description = 'Action d''audit' WHERE e_raci_object_type_id = 10;
UPDATE public.e_raci_object_type SET description = 'Rapport d''audit' WHERE e_raci_object_type_id = 11;
UPDATE public.e_raci_object_type SET description = 'Produit composé' WHERE e_raci_object_type_id = 12;
UPDATE public.e_raci_object_type SET description = 'Risque' WHERE e_raci_object_type_id = 13;
UPDATE public.e_raci_object_type SET description = 'Revue de risque' WHERE e_raci_object_type_id = 14;
UPDATE public.e_raci_object_type SET description = 'Contrôle sur un risque' WHERE e_raci_object_type_id = 15;
UPDATE public.e_raci_object_type SET description = 'Action sur un risque' WHERE e_raci_object_type_id = 16;

UPDATE risk.e_likelihood SET name = 'Rare' WHERE e_likelihood_id = 1;
UPDATE risk.e_likelihood SET name = 'Improbable' WHERE e_likelihood_id = 2;
UPDATE risk.e_likelihood SET name = 'Modéré' WHERE e_likelihood_id = 3;
UPDATE risk.e_likelihood SET name = 'Probable' WHERE e_likelihood_id = 4;
UPDATE risk.e_likelihood SET name = 'Certain' WHERE e_likelihood_id = 5;
UPDATE risk.e_likelihood SET description = 'L''évènement ne peut se produire qu''en des cisconstances exceptionnelles' WHERE e_likelihood_id = 1;
UPDATE risk.e_likelihood SET description = 'L''évènement peut se produire à l''occasion' WHERE e_likelihood_id = 2;
UPDATE risk.e_likelihood SET description = 'L''évènement se produira probablement de temps en temps' WHERE e_likelihood_id = 3;
UPDATE risk.e_likelihood SET description = 'L''évènement se produira probablement la plupart du temps' WHERE e_likelihood_id = 4;
UPDATE risk.e_likelihood SET description = 'L''évènement se produira probablement lors de la majorité des cas' WHERE e_likelihood_id = 5;
UPDATE risk.e_consequence_level SET label = 'Négligeable' WHERE e_consequence_level_id = 1;
UPDATE risk.e_consequence_level SET label = 'Mineur' WHERE e_consequence_level_id = 2;
UPDATE risk.e_consequence_level SET label = 'Modéré' WHERE e_consequence_level_id = 3;
UPDATE risk.e_consequence_level SET label = 'Majeur' WHERE e_consequence_level_id = 4;
UPDATE risk.e_consequence_level SET label = 'Catastrophique' WHERE e_consequence_level_id = 5;
UPDATE risk.e_consequence_level SET label = 'Négligeable' WHERE e_consequence_level_id = 11;
UPDATE risk.e_consequence_level SET label = 'Mineur' WHERE e_consequence_level_id = 12;
UPDATE risk.e_consequence_level SET label = 'Modéré' WHERE e_consequence_level_id = 13;
UPDATE risk.e_consequence_level SET label = 'Majeur' WHERE e_consequence_level_id = 14;
UPDATE risk.e_consequence_level SET label = 'Exceptionnnel' WHERE e_consequence_level_id = 15;
UPDATE risk.e_consequence_level SET description = 'Pas de dommages, déficit faible' WHERE e_consequence_level_id = 1;
UPDATE risk.e_consequence_level SET description = 'Premiers secours, déficit moyen' WHERE e_consequence_level_id = 2;
UPDATE risk.e_consequence_level SET description = 'Traitement requis, déficit élevé' WHERE e_consequence_level_id = 3;
UPDATE risk.e_consequence_level SET description = 'Dommages étendus, déficit majeur' WHERE e_consequence_level_id = 4;
UPDATE risk.e_consequence_level SET description = 'Mort, déficit immense' WHERE e_consequence_level_id = 5;
UPDATE risk.e_consequence_level SET description = 'Peu de bénéfices, profits faibles' WHERE e_consequence_level_id = 11;
UPDATE risk.e_consequence_level SET description = 'Améliorations mineures, quelques profits' WHERE e_consequence_level_id = 12;
UPDATE risk.e_consequence_level SET description = 'Quelques améliorations, profits importants' WHERE e_consequence_level_id = 13;
UPDATE risk.e_consequence_level SET description = 'Nombreuses améliorations, profit majeur' WHERE e_consequence_level_id = 14;
UPDATE risk.e_consequence_level SET description = 'Réputation significativement améliorée, très grands profits' WHERE e_consequence_level_id = 15;

UPDATE itsm.t_status SET status_name = 'Nouveau' WHERE t_status_id = 1;
UPDATE itsm.t_status SET status_name = 'En cours' WHERE t_status_id = 2;
UPDATE itsm.t_status SET status_name = 'Annulé' WHERE t_status_id = 3;
UPDATE itsm.t_status SET status_name = 'Corrigé' WHERE t_status_id = 4;
UPDATE itsm.t_status SET status_name = 'Non corrigé' WHERE t_status_id = 5;
UPDATE itsm.t_status SET status_name = 'Clos' WHERE t_status_id = 6;
UPDATE itsm.t_ipsu SET ipsu_name = 'Non bloquant' WHERE t_ipsu_id = 1;
UPDATE itsm.t_ipsu SET ipsu_name = 'Individuel' WHERE t_ipsu_id = 2;
UPDATE itsm.t_ipsu SET ipsu_name = 'Groupe' WHERE t_ipsu_id = 3;
UPDATE itsm.t_ipsu SET ipsu_name = 'Basse' WHERE t_ipsu_id = 11;
UPDATE itsm.t_ipsu SET ipsu_name = 'Moyenne' WHERE t_ipsu_id = 12;
UPDATE itsm.t_ipsu SET ipsu_name = 'Haute' WHERE t_ipsu_id = 13;
UPDATE itsm.t_ipsu SET ipsu_name = 'Basse' WHERE t_ipsu_id = 21;
UPDATE itsm.t_ipsu SET ipsu_name = 'Moyenne' WHERE t_ipsu_id = 22;
UPDATE itsm.t_ipsu SET ipsu_name = 'Haute' WHERE t_ipsu_id = 23;
UPDATE itsm.t_ipsu SET ipsu_name = 'Normal' WHERE t_ipsu_id = 31;
UPDATE itsm.t_ipsu SET ipsu_name = 'Urgent' WHERE t_ipsu_id = 32;
UPDATE itsm.t_ipsu SET ipsu_name = 'Immédiat' WHERE t_ipsu_id = 33;
UPDATE itsm.t_satisfaction_level SET satisfaction_level = 'Très élevé' WHERE t_satisfaction_level_id = 1;
UPDATE itsm.t_satisfaction_level SET satisfaction_level = 'Elevé' WHERE t_satisfaction_level_id = 2;
UPDATE itsm.t_satisfaction_level SET satisfaction_level = 'Moyen' WHERE t_satisfaction_level_id = 3;
UPDATE itsm.t_satisfaction_level SET satisfaction_level = 'Bas' WHERE t_satisfaction_level_id = 4;

UPDATE public.e_probe_category SET name = 'Applications' WHERE e_probe_category_id = 1;
UPDATE public.e_probe_category SET name = 'Assets' WHERE e_probe_category_id = 2;
UPDATE public.e_probe_category SET name = 'Audit' WHERE e_probe_category_id = 3;
UPDATE public.e_probe_category SET name = 'Compliance' WHERE e_probe_category_id = 4;
UPDATE public.e_probe_category SET name = 'Web' WHERE e_probe_category_id = 5;
UPDATE public.e_probe_category SET name = 'IT Operations' WHERE e_probe_category_id = 6;
UPDATE public.e_probe_category SET name = 'IT System management' WHERE e_probe_category_id = 7;
UPDATE public.e_probe_category SET name = 'Spam and mail' WHERE e_probe_category_id = 8;
UPDATE public.e_probe_category SET name = 'Identity management' WHERE e_probe_category_id = 9;
UPDATE public.e_probe_category SET name = 'Network events' WHERE e_probe_category_id = 10;
UPDATE public.e_probe_category SET name = 'Vulnerabilities' WHERE e_probe_category_id = 11;
UPDATE public.e_probe_category SET name = 'User tools' WHERE e_probe_category_id = 12;
UPDATE public.e_probe_category SET name = 'Malwares' WHERE e_probe_category_id = 13;
UPDATE public.e_probe_category SET name = 'Instant messaging' WHERE e_probe_category_id = 14;

