INSERT INTO asset.e_asset_type (id, name) VALUES (1, 'Cluster');
INSERT INTO asset.e_asset_type (id, name) VALUES (2, 'Server');
INSERT INTO asset.e_asset_type (id, name) VALUES (3, 'Server Appliance');
INSERT INTO asset.e_asset_type (id, name) VALUES (4, 'Router');
INSERT INTO asset.e_asset_type (id, name) VALUES (5, 'Network Appliance');
INSERT INTO asset.e_asset_type (id, name) VALUES (6, 'Security Appliance');
INSERT INTO asset.e_asset_type (id, name) VALUES (7, 'Access Device');
INSERT INTO asset.e_asset_type (id, name) VALUES (8, 'Mobile Access Device');
INSERT INTO asset.e_asset_type (id, name) VALUES (9, 'Printing Device');
INSERT INTO asset.e_sc (id, name) VALUES (1, 'Business Critical');
INSERT INTO asset.e_sc (id, name) VALUES (2, 'Business Needed');
INSERT INTO asset.e_sc (id, name) VALUES (3, 'Business');
INSERT INTO asset.e_sc (id, name) VALUES (4, 'Business Support');
INSERT INTO asset.e_sc (id, name) VALUES (5, 'Infrastructure');
INSERT INTO asset.e_sc (id, name) VALUES (6, 'Non-Business Critical');
INSERT INTO asset.e_sc (id, name) VALUES (7, 'Non-Business');
INSERT INTO asset.e_bl (id, name) VALUES (1, 'IT');
INSERT INTO asset.e_bl (id, name) VALUES (2, 'Corporate');
INSERT INTO asset.e_bl (id, name) VALUES (3, 'Sales');
INSERT INTO asset.e_bl (id, name) VALUES (4, 'Marketing');
INSERT INTO asset.e_bl (id, name) VALUES (5, 'R&D');
INSERT INTO asset.e_bl (id, name) VALUES (6, 'Production');
INSERT INTO asset.e_bl (id, name) VALUES (7, 'Accounting');
INSERT INTO asset.e_bl (id, name) VALUES (8, 'Finance');
INSERT INTO asset.e_bl (id, name) VALUES (9, 'Fields');
INSERT INTO asset.e_bl (id, name) VALUES (10, 'Business Partners');
INSERT INTO asset.e_availability (id, name) VALUES (1, 'Non-Stop');
INSERT INTO asset.e_availability (id, name) VALUES (2, 'High Availability');
INSERT INTO asset.e_availability (id, name) VALUES (3, '99%');
INSERT INTO asset.e_availability (id, name) VALUES (4, 'Business Hours');
INSERT INTO asset.e_availability (id, name) VALUES (5, 'Best effort');

INSERT INTO audit.e_audit_rec_status (e_audit_rec_status_id, rec_status) VALUES (1, 'Open');
INSERT INTO audit.e_audit_rec_status (e_audit_rec_status_id, rec_status) VALUES (2, 'Closed');
INSERT INTO audit.e_audit_rec_status (e_audit_rec_status_id, rec_status) VALUES (3, 'Risk Accepted');
INSERT INTO audit.e_audit_rec_status (e_audit_rec_status_id, rec_status) VALUES (4, 'Closed Duplicate');
INSERT INTO audit.e_audit_severity (e_audit_severity_id, severity) VALUES (1, 'Low');
INSERT INTO audit.e_audit_severity (e_audit_severity_id, severity) VALUES (2, 'Medium');
INSERT INTO audit.e_audit_severity (e_audit_severity_id, severity) VALUES (3, 'High');
INSERT INTO audit.e_audit_topic (e_audit_topic_id, topic) VALUES (1, 'Network Security');
INSERT INTO audit.e_audit_topic (e_audit_topic_id, topic) VALUES (2, 'Physical Security');
INSERT INTO audit.e_audit_topic (e_audit_topic_id, topic) VALUES (3, 'System Security');
INSERT INTO audit.e_audit_topic (e_audit_topic_id, topic) VALUES (4, 'Access');
INSERT INTO audit.e_audit_topic (e_audit_topic_id, topic) VALUES (5, 'Applications');
INSERT INTO audit.e_audit_topic (e_audit_topic_id, topic) VALUES (6, 'Business');
INSERT INTO audit.e_audit_topic (e_audit_topic_id, topic) VALUES (7, 'Other');
INSERT INTO audit.e_audit_origin (e_audit_origin_id, origin) VALUES (1, 'Internal audit');
INSERT INTO audit.e_audit_origin (e_audit_origin_id, origin) VALUES (2, 'External audit');
INSERT INTO audit.e_audit_origin (e_audit_origin_id, origin) VALUES (3, 'Regulators');
INSERT INTO audit.e_audit_origin (e_audit_origin_id, origin) VALUES (4, 'Self audit');
INSERT INTO audit.e_audit_action_status (e_audit_action_status_id, action_status) VALUES (1, 'Planning');
INSERT INTO audit.e_audit_action_status (e_audit_action_status_id, action_status) VALUES (2, 'In Progress');
INSERT INTO audit.e_audit_action_status (e_audit_action_status_id, action_status) VALUES (3, 'Completed');
INSERT INTO audit.e_audit_action_status (e_audit_action_status_id, action_status) VALUES (4, 'Cancelled');
INSERT INTO audit.e_audit_action_status (e_audit_action_status_id, action_status) VALUES (5, 'Halted');
INSERT INTO audit.e_audit_priority (e_audit_priority_id, priority) VALUES (1, 'Low');
INSERT INTO audit.e_audit_priority (e_audit_priority_id, priority) VALUES (2, 'Medium');
INSERT INTO audit.e_audit_priority (e_audit_priority_id, priority) VALUES (3, 'High');
INSERT INTO audit.e_audit_rec_topic (e_audit_rec_topic_id, topic) VALUES (1, 'Access');
INSERT INTO audit.e_audit_rec_topic (e_audit_rec_topic_id, topic) VALUES (2, 'Network');
INSERT INTO audit.e_audit_rec_topic (e_audit_rec_topic_id, topic) VALUES (3, 'Premises');
INSERT INTO audit.e_audit_rec_topic (e_audit_rec_topic_id, topic) VALUES (4, 'Management');
INSERT INTO audit.e_audit_rec_topic (e_audit_rec_topic_id, topic) VALUES (5, 'Global');
INSERT INTO audit.e_audit_rec_topic (e_audit_rec_topic_id, topic) VALUES (6, 'Monitoring');
INSERT INTO audit.e_audit_rec_topic (e_audit_rec_topic_id, topic) VALUES (7, 'Awareness');
INSERT INTO audit.e_audit_confidentiality (e_audit_confidentiality_id, confidentiality) VALUES (1, 'Internal');
INSERT INTO audit.e_audit_confidentiality (e_audit_confidentiality_id, confidentiality) VALUES (2, 'Confidential');
INSERT INTO audit.e_audit_confidentiality (e_audit_confidentiality_id, confidentiality) VALUES (3, 'Sponsor Only');
INSERT INTO audit.e_audit_confidentiality (e_audit_confidentiality_id, confidentiality) VALUES (4, 'Company Private');
INSERT INTO audit.e_audit_status (e_audit_status_id, status) VALUES (1, 'Planning');
INSERT INTO audit.e_audit_status (e_audit_status_id, status) VALUES (2, 'Contracting');
INSERT INTO audit.e_audit_status (e_audit_status_id, status) VALUES (3, 'Interviews');
INSERT INTO audit.e_audit_status (e_audit_status_id, status) VALUES (4, 'Opening meeting');
INSERT INTO audit.e_audit_status (e_audit_status_id, status) VALUES (5, 'Draft Report');
INSERT INTO audit.e_audit_status (e_audit_status_id, status) VALUES (6, 'Final Report');
INSERT INTO audit.e_audit_status (e_audit_status_id, status) VALUES (7, 'Closing meeting');
INSERT INTO audit.e_audit_status (e_audit_status_id, status) VALUES (8, 'Remediating');
INSERT INTO audit.e_audit_status (e_audit_status_id, status) VALUES (9, 'Closed');
INSERT INTO audit.e_audit_report_status (e_audit_report_status_id, report_status) VALUES (1, 'Draft');
INSERT INTO audit.e_audit_report_status (e_audit_report_status_id, report_status) VALUES (2, 'Final');
INSERT INTO audit.e_audit_report_status (e_audit_report_status_id, report_status) VALUES (3, 'Approved');
INSERT INTO audit.e_audit_report_status (e_audit_report_status_id, report_status) VALUES (4, 'Published');
INSERT INTO audit.e_audit_document_type (e_audit_document_type_id, document_type) VALUES (1, 'Evidence');
INSERT INTO audit.e_audit_document_type (e_audit_document_type_id, document_type) VALUES (2, 'Information');
INSERT INTO audit.e_audit_document_type (e_audit_document_type_id, document_type) VALUES (3, 'Email');
INSERT INTO audit.e_audit_document_type (e_audit_document_type_id, document_type) VALUES (4, 'Document');

INSERT INTO compliance.e_standard_category (e_standard_category_id, standard_category) VALUES (1, 'Information Technology');
INSERT INTO compliance.e_standard_category (e_standard_category_id, standard_category) VALUES (2, 'General Management');
INSERT INTO compliance.e_topic_category (e_topic_category_id, topic_category) VALUES (1, 'Security Management');
INSERT INTO compliance.e_topic_category (e_topic_category_id, topic_category) VALUES (2, 'Access Control');
INSERT INTO compliance.e_compliance_kind (e_compliance_kind_id, kind) VALUES (1, 'Application comment');
INSERT INTO compliance.e_compliance_kind (e_compliance_kind_id, kind) VALUES (2, 'Documentation comment');
INSERT INTO compliance.e_compliance_type (e_compliance_type_id, compliance_type) VALUES (1, 'Non compliance of minor application');
INSERT INTO compliance.e_compliance_type (e_compliance_type_id, compliance_type) VALUES (2, 'Non compliance of minor documentation');
INSERT INTO compliance.e_compliance_type (e_compliance_type_id, compliance_type) VALUES (3, 'Non compliance of major application');
INSERT INTO compliance.e_compliance_type (e_compliance_type_id, compliance_type) VALUES (4, 'Non compliance of major documentation');

INSERT INTO mim.t_user_anomaly (t_user_anomaly_id, description) VALUES (1, 'None');
INSERT INTO mim.t_user_anomaly (t_user_anomaly_id, description) VALUES (2, 'Fudge : mainframe data missing');
INSERT INTO mim.t_user_anomaly (t_user_anomaly_id, description) VALUES (3, 'Fudge : mainframe date security admin missing');
INSERT INTO mim.t_user_anomaly (t_user_anomaly_id, description) VALUES (4, 'Fudge : mainframe datecontractvalidity abnormal');
INSERT INTO mim.t_user_anomaly (t_user_anomaly_id, description) VALUES (5, 'Fudge : mainframe date1sthire bad');
INSERT INTO mim.t_user_anomaly (t_user_anomaly_id, description) VALUES (6, 'Fudge : mainframe ou bad');
INSERT INTO mim.t_user_anomaly (t_user_anomaly_id, description) VALUES (7, 'Fudge : mainframe l bad');
INSERT INTO mim.t_user_anomaly (t_user_anomaly_id, description) VALUES (8, 'Fudge : ad data missing');
INSERT INTO mim.t_user_anomaly (t_user_anomaly_id, description) VALUES (9, 'Fudge : ad date is 0');
INSERT INTO mim.t_user_anomaly (t_user_anomaly_id, description) VALUES (10, 'Fudge : hr data missing');
INSERT INTO mim.t_user_anomaly (t_user_anomaly_id, description) VALUES (11, 'Fudge : hr logoncount missing');
INSERT INTO mim.t_user_anomaly (t_user_anomaly_id, description) VALUES (12, 'Fudge : hr still has 19000000 as dates');
INSERT INTO mim.t_user_anomaly (t_user_anomaly_id, description) VALUES (13, 'Fudge : hr still has 19800101 as dates');

INSERT INTO itops.t_alert_severity (t_alert_severity_id, severity_name) VALUES (1, 'Information');
INSERT INTO itops.t_alert_severity (t_alert_severity_id, severity_name) VALUES (2, 'Warning');
INSERT INTO itops.t_alert_severity (t_alert_severity_id, severity_name) VALUES (3, 'Critical');
INSERT INTO itops.t_alert_priority (t_alert_priority_id, priority_name) VALUES (1, 'Low');
INSERT INTO itops.t_alert_priority (t_alert_priority_id, priority_name) VALUES (2, 'Medium');
INSERT INTO itops.t_alert_priority (t_alert_priority_id, priority_name) VALUES (3, 'High');
INSERT INTO itops.t_event_level (t_event_level_id, event_level) VALUES (1, 'Success');
INSERT INTO itops.t_event_level (t_event_level_id, event_level) VALUES (2, 'Error');
INSERT INTO itops.t_event_level (t_event_level_id, event_level) VALUES (3, 'Warning');
INSERT INTO itops.t_event_level (t_event_level_id, event_level) VALUES (4, 'Information');
INSERT INTO itops.t_event_level (t_event_level_id, event_level) VALUES (5, 'Audit Success');
INSERT INTO itops.t_event_level (t_event_level_id, event_level) VALUES (6, 'Audit Failure');

INSERT INTO public.e_file_states (id, state_name) VALUES (-4, 'Aborted, inconsistent data');
INSERT INTO public.e_file_states (id, state_name) VALUES (-3, 'Aborted');
INSERT INTO public.e_file_states (id, state_name) VALUES (-2, 'Downloading');
INSERT INTO public.e_file_states (id, state_name) VALUES (-1, 'Running');
INSERT INTO public.e_file_states (id, state_name) VALUES (0, 'Ready');
INSERT INTO public.e_file_states (id, state_name) VALUES (1, 'Success');
INSERT INTO public.e_file_states (id, state_name) VALUES (2, 'Error - retry');
INSERT INTO public.e_file_states (id, state_name) VALUES (3, 'Failure');
INSERT INTO public.e_file_states (id, state_name) VALUES (4, 'Ignored');
INSERT INTO public.e_file_states (id, state_name) VALUES (5, 'Superceded');
INSERT INTO public.e_file_states (id, state_name) VALUES (6, 'Duplicate');
INSERT INTO public.e_file_states (id, state_name) VALUES (7, 'Success + Archived');
INSERT INTO public.e_file_states (id, state_name) VALUES (8, 'Superceded + Archived');
INSERT INTO public.e_file_states (id, state_name) VALUES (9, 'Duplicate + Archived');
INSERT INTO public.e_file_states (id, state_name) VALUES (10, 'Failure + Archived');
INSERT INTO public.e_file_states (id, state_name) VALUES (11, 'Ignore + Archived');
INSERT INTO public.e_probe_parameter_origin (e_probe_parameter_origin_id, origin) VALUES (1, 'Default value');
INSERT INTO public.e_probe_parameter_origin (e_probe_parameter_origin_id, origin) VALUES (2, 'Database value');
INSERT INTO public.e_probe_parameter_origin (e_probe_parameter_origin_id, origin) VALUES (3, 'XML file');
INSERT INTO public.e_probe_run_status (e_probe_run_status_id, status_name) VALUES (0, 'Never run');
INSERT INTO public.e_probe_run_status (e_probe_run_status_id, status_name) VALUES (1, 'Success');
INSERT INTO public.e_probe_run_status (e_probe_run_status_id, status_name) VALUES (2, 'No data');
INSERT INTO public.e_probe_run_status (e_probe_run_status_id, status_name) VALUES (3, 'Aborted');
INSERT INTO public.e_probe_run_status (e_probe_run_status_id, status_name) VALUES (4, 'Failure');
INSERT INTO public.e_probe_run_status (e_probe_run_status_id, status_name) VALUES (5, 'Error');
INSERT INTO public.e_probe_run_status (e_probe_run_status_id, status_name) VALUES (6, 'Still running');
INSERT INTO public.e_probe_run_status (e_probe_run_status_id, status_name) VALUES (7, 'Aborted with error');

INSERT INTO asset.e_product_type (id, name) VALUES (1, 'Software');
INSERT INTO asset.e_product_type (id, name) VALUES (2, 'Hardware');
INSERT INTO asset.e_product_type (id, name) VALUES (3, 'Appliance');
INSERT INTO asset.e_preferred_relationship (id, name) VALUES (1, 'Strategic partner');
INSERT INTO asset.e_preferred_relationship (id, name) VALUES (2, 'Partner');
INSERT INTO asset.e_preferred_relationship (id, name) VALUES (3, 'Supplier');
INSERT INTO asset.e_preferred_relationship (id, name) VALUES (4, 'No relationship');

INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.rootDir', 'Root directory.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.errorsDir', 'Error directory for incorrect files.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.errorsSize', 'Max size for the error directory.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.reportsDir', 'Directory where generated reports are put.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.defaultCompany', 'Default company name.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.poweredByLogo', 'poweredBy logo file path.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.web.localServerPort', 'Tomcat port.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.web.localServerAddress', 'Local server address.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.web.remoteServerProtocol', 'Protocol.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.mail.MailHelper.hostName', 'SMTP server host name.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.mail.MailHelper.hostPort', 'SMTP server port.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.mail.MailHelper.useTls', 'SMTP server useTls.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.mail.MailHelper.useAuth', 'SMTP server useAuth.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.mail.MailHelper.smtpUser', 'SMTP user.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.feature.attachCalendarFile', 'Attach a ical file for generated emails.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.mail.MailHelper.smtpPassword', 'SMTP password.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.mail.MailHelper.maxTries', 'Number of tries to send an email before failure.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.mail.MailHelper.maxEmailSentAtOnce', 'Max number of emails sent at once.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.mail.MailHelper.iconLocation', 'Logo file path.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.soap.SessionHandler.timeoutMinutes', 'Timeout in minutes.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.soap.soapBase.authMethod', 'Authentication method.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.maxReturnedRows', 'Maximum number of returned rows in datagrid.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.soap.auth.LDAP.base', 'Base for LDAP authentication.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.soap.auth.LDAP.baseFilterString', 'Base filter for LDAP authentication.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.soap.auth.LDAP.userNameField', 'Username field for LDAP authentication.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.soap.auth.LDAP.url', 'URL for LDAP authentication.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.soap.auth.LDAP.searchUserName', 'Search user name for LDAP authentication.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.soap.auth.LDAP.searchPassword', 'Password for LDAP authentication.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpHelper.userAgent', 'User agent for HTTP.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpHelper.useProxy', 'HTTP connexion use proxy.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpHelper.proxyHost', 'HTTP proxy host name.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpHelper.proxyPort', 'HTTP proxy port name.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpHelper.useProxyAuth', 'HTTP proxy use authentication.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpHelper.proxyRealm', 'HTTP proxy realm.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpHelper.proxyScheme', 'HTTP proxy scheme.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpHelper.proxyUserName', 'HTTP proxy user name.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpHelper.proxyPassword', 'HTTP proxy password.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpSslHelper.userAgent', 'User agent for HTTPS.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpSslHelper.useProxy', 'HTTPS connexion use proxy.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpSslHelper.proxyHost', 'HTTPS proxy host name.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpSslHelper.proxyPort', 'HTTPS proxy port name.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpSslHelper.useProxyAuth', 'HTTPS proxy use authentication.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpSslHelper.proxyRealm', 'HTTPS proxy realm.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpSslHelper.proxyScheme', 'HTTPS proxy scheme.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpSslHelper.proxyUserName', 'HTTPS proxy user name.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpSslHelper.proxyPassword', 'HTTPS proxy password.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpSslHelper.keyStore', 'Keystore for HTTPS.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpSslHelper.keyStorePassword', 'Keystore password for HTTPS.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.license.LicenseHelper.publicStore', 'Public store to authenticate licenses.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.raci.strict_RACI', 'Strict RACI mode.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.cnilLevel', 'CNIL level.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.logDirectory', 'Path of the directory containing log files.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.probeXmlFile', 'Path of the probes XML file.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.probes.showProbeSnailOnLastNDays', 'Set the default period to check for probes runs.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.module.Admin.can_edit_its_own_expertises', 'Can users edit their own expertises.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.feature.notifyMail', 'Email notification activated.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.feature.notifySelfMail', 'Email notification activated for user for its own email address.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.feature.attachHtmlMail', 'Use HTML emails.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.feature.sendEmailOnExpertiseChange', 'Send email when an expertise changes.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.feature.sendEmailOnRACIChange', 'Send email when a RACI changes.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.feature.sendEmailOnObjectModification', 'Send email when an object changes.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.feature.sendEmailOnObjectCreation', 'Send email when an object is created.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.mail.MailHelper.receiveEmailOnChange', 'RACI levels necessary to receive emails.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.raci.delayRaciChangeOnModule', 'Modules RACI changes are delayed.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.SupportNotifier.supportEmail', 'Email of the support.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.feature.SupportNotifier', 'Is support email notification activated.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.mail.MailHelper.defaultFromAddress', 'Default FROM address.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.security.minPasswordLength', 'Minimum password length.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.security.passwordComplexity', 'Use password complexity.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.security.passwordAge', 'Maximum password age in days.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.security.passwordHistory', 'Number of password per users saved in history.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.security.loginHistoryAge', 'Users login history age in days.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.security.numberOfFailedLoginLimit', 'Number of consecutive failed logins limit that block a user account.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.security.failedLoginTimeLimit', 'Time limit (in min) for consecutive failed logins.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.security.automatedLostPassword', 'Activate the Lost Password button to send a new generated password by email or if email isn''t available a application incident.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.provider.calendar.DbCalendar.redefineFirstDayOfWeek', 'Use system 1st day of week or redefine it.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.provider.calendar.DbCalendar.firstDayOfWeek', '1st day of week (1=Sunday,7=Saturday).');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.module.Admin.language', 'Application language.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.module.Audit.user_see_my_only', 'Users see elements only if they are in the RACI matrix.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.module.Audit.escaladeActionAfterNDelays', 'Number of delays necessary to mark an action as escaladated.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.module.Audit.escaladeRecommendationAfterNDelays', 'Number of delays necessary to mark a recommendation as escaladated.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.feature.hideNewProduct', 'Hide new products imported by probes.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.feature.hideNewVendor', 'Hide new vendors imported by probes.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.soap.soapIdentityManagement.IMReportClassName', 'Report class that will be loaded to get the metrics.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.im.snail_colors.percent_low', 'Percentage (metric/target) under which the metric is considered as good.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.im.snail_colors.percent_medium', 'Percentage (metric/target) under which the metric is considered as quite good.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.im.snail_colors.percent_high', 'Percentage (metric/target) under which the metric is considered as meddle.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.im.snail_colors.percent_bad', 'Percentage (metric/target) under which the metric is considered as quite bad.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.http.average_hits_per_page', 'Average number of hits per page.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.http.average_time_spent_per_page', 'Average time spent on 1 web page (in s).');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.module.Portal.numberOfGridsInChart', 'Number of horizontal grids in line graphs.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.module.Portal.gridFrom0', 'Is the 0 line displayed in line charts.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.module.Portal.ignoredCategories', 'List of Web categories ignored in lists.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.module.Portal.show_others_in_pie', 'Are piecharts displayed with a Other part.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.module.RiskAssessment.user_see_my_only', 'Users see elements only if they are in the RACI matrix.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.module.RiskModelisation.user_see_my_only', 'Users see elements only if they are in the RACI matrix.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.vrt.actions.actions_fixed_before_vuln_fixed', 'A vulnerability can get fixed(or won''t fix) only if all its actions are fixed (or won''t fix).');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.vrt.closed_vrt_vuln_can_change_decision', 'Is it possible to change the decision of a vulnerability if its VRT is closed.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.vrt.user_see_my_only', 'Users see elements only if they are in the RACI matrix.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.vrt.user_see_my_new_only', 'Users see elements only if they are in the RACI matrix in the NEW screen.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.vrt.vote_ignore_decision_ceiling', 'Only used in vote mode where all experts must vote. To avoid vulnerabilities without decision taken due to the absence of an expert, this parameter reprensents the ceiling of votes to give a decision to a vulnerability.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.vrt.vote_instead_of_decision', 'A voting mode is used to triage the vulnerabilities and ignore them or add them to the next VRT.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.vrt.simplifiedVRTProcess', 'In this simplified mode : any vote push the vulnerability in the VRT (so it is a Vote mode, with a ignore decision ceiling to 1), and an action is created for each vote. The vulnerability can be voted until it''s analyzed. In this mode, a vulnerability can be analyzed even if its VRT is not yet started. Triaged vulnerabilities are pushed in the Current VRT (there is no Next VRT). The decision is automatically set to Repair or Ignore, depending of the vote.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.vrt.votesBasedDecision', ' Decisions of voted vulnerabilities can be tuned.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.vrt.votesBasedDecision.IgnoredDecision', 'Decision to be taken for a vulnerability ignored by its votes (table vuln.e_vulnerability_status).');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.vrt.votesBasedDecision.AddDecision', 'Decision to be taken for a vulnerability Add to VRT by its votes (table vuln.e_vulnerability_status).');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.vrt.only_experts_can_vote', 'Only used in vote mode. Only the experts of a vulnerability can vote on a vulnerability.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.vrt.can_vote_until_analysis', 'Only used in vote mode. A vulnerability can receive votes until it''s analyzed for the 1st time.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.vrt.oneVotePerExpertDepartment', 'The member of an expert department that votes on a vulnerability prevent the other members of the group to vote for the vulnerability.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.vrt.createActionOnTriage', 'An action automatically created for each vote (or triage) on a vulnerability.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.vrt.commentRequiredOnIgnore', 'When ignoring a vulnerability, the user has to comment his vote.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.vrt.triageOnRenewedVulnOutdoHigherDecision', 'Triage a a renewed vulnerability always changes the decision.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.provider.vrt.url.securityfocus', 'Pattern URL to view a web version of a SecurityFocus advisory.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.provider.vrt.url.microsoft', 'Pattern URL to view a web version of a Microsoft advisory.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.provider.vrt.url.nist', 'Pattern URL to view a web version of a NVD advisory.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.provider.vrt.url.certist', 'Pattern URL to view a web version of a Cert-IST advisory.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.feature.notifyNewVulnsForExperts', 'Emails are sent to experts of new vulnerabilities.');

INSERT INTO risk.e_category (e_category_id, category_name) VALUES (1, 'Diseases');
INSERT INTO risk.e_category (e_category_id, category_name) VALUES (2, 'Economic');
INSERT INTO risk.e_category (e_category_id, category_name) VALUES (3, 'Environmental');
INSERT INTO risk.e_category (e_category_id, category_name) VALUES (4, 'Financial');
INSERT INTO risk.e_category (e_category_id, category_name) VALUES (5, 'Human');
INSERT INTO risk.e_category (e_category_id, category_name) VALUES (6, 'Natural hazard');
INSERT INTO risk.e_category (e_category_id, category_name) VALUES (7, 'Health & safety');
INSERT INTO risk.e_category (e_category_id, category_name) VALUES (8, 'Product liability');
INSERT INTO risk.e_category (e_category_id, category_name) VALUES (9, 'Professional liability');
INSERT INTO risk.e_category (e_category_id, category_name) VALUES (10, 'Property damage');
INSERT INTO risk.e_category (e_category_id, category_name) VALUES (11, 'Public liability');
INSERT INTO risk.e_category (e_category_id, category_name) VALUES (12, 'Security');
INSERT INTO risk.e_category (e_category_id, category_name) VALUES (13, 'Technological');
INSERT INTO risk.e_risk_decision (e_risk_decision_id, decision) VALUES (1, 'Reduction');
INSERT INTO risk.e_risk_decision (e_risk_decision_id, decision) VALUES (2, 'Mitigation');
INSERT INTO risk.e_risk_decision (e_risk_decision_id, decision) VALUES (3, 'Avoidance');
INSERT INTO risk.e_risk_decision (e_risk_decision_id, decision) VALUES (4, 'Transfer');
INSERT INTO risk.e_risk_priority (e_risk_priority_id, priority) VALUES (1, 'Minor');
INSERT INTO risk.e_risk_priority (e_risk_priority_id, priority) VALUES (2, 'Low');
INSERT INTO risk.e_risk_priority (e_risk_priority_id, priority) VALUES (3, 'Normal');
INSERT INTO risk.e_risk_priority (e_risk_priority_id, priority) VALUES (4, 'Important');
INSERT INTO risk.e_risk_priority (e_risk_priority_id, priority) VALUES (5, 'Urgent');
INSERT INTO risk.e_risk_priority (e_risk_priority_id, priority) VALUES (6, 'Critical');
INSERT INTO risk.e_risk_level (e_risk_level_id, level) VALUES (1, 'Low');
INSERT INTO risk.e_risk_level (e_risk_level_id, level) VALUES (2, 'Medium');
INSERT INTO risk.e_risk_level (e_risk_level_id, level) VALUES (3, 'Significant');
INSERT INTO risk.e_risk_level (e_risk_level_id, level) VALUES (4, 'High');
INSERT INTO risk.e_action_status (e_action_status_id, action_status) VALUES (1, 'Planning');
INSERT INTO risk.e_action_status (e_action_status_id, action_status) VALUES (2, 'In progress');
INSERT INTO risk.e_action_status (e_action_status_id, action_status) VALUES (3, 'Completed');
INSERT INTO risk.e_action_status (e_action_status_id, action_status) VALUES (4, 'Cancelled');
INSERT INTO risk.e_action_status (e_action_status_id, action_status) VALUES (5, 'Halted');

INSERT INTO sdw.e_operation_state (e_state_id, state_descr) VALUES (0, 'Ready');
INSERT INTO sdw.e_operation_state (e_state_id, state_descr) VALUES (1, 'Started');
INSERT INTO sdw.e_operation_state (e_state_id, state_descr) VALUES (2, 'Complete');
INSERT INTO sdw.e_operation_state (e_state_id, state_descr) VALUES (3, 'Needs undo');
INSERT INTO sdw.e_operation_state (e_state_id, state_descr) VALUES (4, 'Undo started');
INSERT INTO sdw.e_operation_state (e_state_id, state_descr) VALUES (5, 'Undone');

INSERT INTO vuln.e_vulnerability_severity (e_severity_id, severity_name) VALUES (0, 'Unrated');
INSERT INTO vuln.e_vulnerability_severity (e_severity_id, severity_name) VALUES (1, 'Low');
INSERT INTO vuln.e_vulnerability_severity (e_severity_id, severity_name) VALUES (2, 'Medium');
INSERT INTO vuln.e_vulnerability_severity (e_severity_id, severity_name) VALUES (3, 'High');
INSERT INTO vuln.e_vulnerability_severity (e_severity_id, severity_name) VALUES (4, 'Critical');
INSERT INTO vuln.e_vulnerability_status (e_status_id, status_name) VALUES (0, 'New');
INSERT INTO vuln.e_vulnerability_status (e_status_id, status_name) VALUES (1, 'Repair');
INSERT INTO vuln.e_vulnerability_status (e_status_id, status_name) VALUES (2, 'Investigate');
INSERT INTO vuln.e_vulnerability_status (e_status_id, status_name) VALUES (3, 'Accept Risk');
INSERT INTO vuln.e_vulnerability_status (e_status_id, status_name) VALUES (4, 'Ignore');
INSERT INTO vuln.e_vulnerability_priority (e_priority_id, priority_name) VALUES (0, 'N/A');
INSERT INTO vuln.e_vulnerability_priority (e_priority_id, priority_name) VALUES (1, 'Low');
INSERT INTO vuln.e_vulnerability_priority (e_priority_id, priority_name) VALUES (2, 'Medium');
INSERT INTO vuln.e_vulnerability_priority (e_priority_id, priority_name) VALUES (3, 'High');
INSERT INTO vuln.e_vulnerability_priority (e_priority_id, priority_name) VALUES (4, 'Immediate');
INSERT INTO vuln.e_vulnerability_mav_status (e_mav_status_id, mav_status_name) VALUES (0, 'N/A');
INSERT INTO vuln.e_vulnerability_mav_status (e_mav_status_id, mav_status_name) VALUES (1, 'Fixed');
INSERT INTO vuln.e_vulnerability_mav_status (e_mav_status_id, mav_status_name) VALUES (2, 'Planning');
INSERT INTO vuln.e_vulnerability_mav_status (e_mav_status_id, mav_status_name) VALUES (3, 'In Progress');
INSERT INTO vuln.e_vulnerability_mav_status (e_mav_status_id, mav_status_name) VALUES (4, 'Won''t fix');
INSERT INTO vuln.e_vulnerability_vote_decision (e_vulnerability_vote_decision_id, vote_decision) VALUES (0, 'Vote for Add');
INSERT INTO vuln.e_vulnerability_vote_decision (e_vulnerability_vote_decision_id, vote_decision) VALUES (4, 'Vote for Ignore');

UPDATE public.e_raci_object_type SET description = 'Vulnerability' WHERE e_raci_object_type_id = 1;
UPDATE public.e_raci_object_type SET description = 'Action for vulnerability' WHERE e_raci_object_type_id = 2;
UPDATE public.e_raci_object_type SET description = 'VRT meeting' WHERE e_raci_object_type_id = 3;
UPDATE public.e_raci_object_type SET description = 'Module' WHERE e_raci_object_type_id = 4;
UPDATE public.e_raci_object_type SET description = 'Audit' WHERE e_raci_object_type_id = 5;
UPDATE public.e_raci_object_type SET description = 'Audit interview' WHERE e_raci_object_type_id = 6;
UPDATE public.e_raci_object_type SET description = 'Audit document' WHERE e_raci_object_type_id = 7;
UPDATE public.e_raci_object_type SET description = 'Audit recommendation (auditor)' WHERE e_raci_object_type_id = 8;
UPDATE public.e_raci_object_type SET description = 'Audit recommendation (auditee)' WHERE e_raci_object_type_id = 9;
UPDATE public.e_raci_object_type SET description = 'Audit action' WHERE e_raci_object_type_id = 10;
UPDATE public.e_raci_object_type SET description = 'Audit report' WHERE e_raci_object_type_id = 11;
UPDATE public.e_raci_object_type SET description = 'Composite product' WHERE e_raci_object_type_id = 12;
UPDATE public.e_raci_object_type SET description = 'Risk' WHERE e_raci_object_type_id = 13;
UPDATE public.e_raci_object_type SET description = 'Risk review' WHERE e_raci_object_type_id = 14;
UPDATE public.e_raci_object_type SET description = 'Risk control' WHERE e_raci_object_type_id = 15;
UPDATE public.e_raci_object_type SET description = 'Risk action' WHERE e_raci_object_type_id = 16;

UPDATE risk.e_likelihood SET name = 'Rare' WHERE e_likelihood_id = 1;
UPDATE risk.e_likelihood SET name = 'Unlikely' WHERE e_likelihood_id = 2;
UPDATE risk.e_likelihood SET name = 'Moderate' WHERE e_likelihood_id = 3;
UPDATE risk.e_likelihood SET name = 'Likely' WHERE e_likelihood_id = 4;
UPDATE risk.e_likelihood SET name = 'Certain' WHERE e_likelihood_id = 5;
UPDATE risk.e_likelihood SET description = 'The event may only occur in exceptional circumstances' WHERE e_likelihood_id = 1;
UPDATE risk.e_likelihood SET description = 'The event could occur at some time' WHERE e_likelihood_id = 2;
UPDATE risk.e_likelihood SET description = 'the event will probably occur at some time' WHERE e_likelihood_id = 3;
UPDATE risk.e_likelihood SET description = 'The event will probably occur in most circumstances' WHERE e_likelihood_id = 4;
UPDATE risk.e_likelihood SET description = 'The event is expected to occur in most circumstances' WHERE e_likelihood_id = 5;
UPDATE risk.e_consequence_level SET label = 'Insignificant' WHERE e_consequence_level_id = 1;
UPDATE risk.e_consequence_level SET label = 'Minor' WHERE e_consequence_level_id = 2;
UPDATE risk.e_consequence_level SET label = 'Moderate' WHERE e_consequence_level_id = 3;
UPDATE risk.e_consequence_level SET label = 'Major' WHERE e_consequence_level_id = 4;
UPDATE risk.e_consequence_level SET label = 'Catastrophic' WHERE e_consequence_level_id = 5;
UPDATE risk.e_consequence_level SET label = 'Insignificant' WHERE e_consequence_level_id = 11;
UPDATE risk.e_consequence_level SET label = 'Minor' WHERE e_consequence_level_id = 12;
UPDATE risk.e_consequence_level SET label = 'Moderate' WHERE e_consequence_level_id = 13;
UPDATE risk.e_consequence_level SET label = 'Major' WHERE e_consequence_level_id = 14;
UPDATE risk.e_consequence_level SET label = 'Outstanding' WHERE e_consequence_level_id = 15;
UPDATE risk.e_consequence_level SET description = 'No injuries, low financial loss' WHERE e_consequence_level_id = 1;
UPDATE risk.e_consequence_level SET description = 'First aid treatment, medium financial loss' WHERE e_consequence_level_id = 2;
UPDATE risk.e_consequence_level SET description = 'Treatment required, high financial loss' WHERE e_consequence_level_id = 3;
UPDATE risk.e_consequence_level SET description = 'Extensive injuries, major financial loss' WHERE e_consequence_level_id = 4;
UPDATE risk.e_consequence_level SET description = 'Death, huge financial loss' WHERE e_consequence_level_id = 5;
UPDATE risk.e_consequence_level SET description = 'Small benefit, low financial gain' WHERE e_consequence_level_id = 11;
UPDATE risk.e_consequence_level SET description = 'Minor improvement, some financial gain' WHERE e_consequence_level_id = 12;
UPDATE risk.e_consequence_level SET description = 'Some enhancements, high financial gain' WHERE e_consequence_level_id = 13;
UPDATE risk.e_consequence_level SET description = 'Great enhancements, major financial gain' WHERE e_consequence_level_id = 14;
UPDATE risk.e_consequence_level SET description = 'Significantly enhanced reputation, huge financial gain' WHERE e_consequence_level_id = 15;

UPDATE itsm.t_status SET status_name = 'New' WHERE t_status_id = 1;
UPDATE itsm.t_status SET status_name = 'Pending' WHERE t_status_id = 2;
UPDATE itsm.t_status SET status_name = 'Cancelled' WHERE t_status_id = 3;
UPDATE itsm.t_status SET status_name = 'Fixed' WHERE t_status_id = 4;
UPDATE itsm.t_status SET status_name = 'Won''t fix' WHERE t_status_id = 5;
UPDATE itsm.t_status SET status_name = 'Closed' WHERE t_status_id = 6;
UPDATE itsm.t_ipsu SET ipsu_name = 'Non blocking' WHERE t_ipsu_id = 1;
UPDATE itsm.t_ipsu SET ipsu_name = 'Individual' WHERE t_ipsu_id = 2;
UPDATE itsm.t_ipsu SET ipsu_name = 'Group' WHERE t_ipsu_id = 3;
UPDATE itsm.t_ipsu SET ipsu_name = 'Low' WHERE t_ipsu_id = 11;
UPDATE itsm.t_ipsu SET ipsu_name = 'Medium' WHERE t_ipsu_id = 12;
UPDATE itsm.t_ipsu SET ipsu_name = 'High' WHERE t_ipsu_id = 13;
UPDATE itsm.t_ipsu SET ipsu_name = 'Low' WHERE t_ipsu_id = 21;
UPDATE itsm.t_ipsu SET ipsu_name = 'Medium' WHERE t_ipsu_id = 22;
UPDATE itsm.t_ipsu SET ipsu_name = 'High' WHERE t_ipsu_id = 23;
UPDATE itsm.t_ipsu SET ipsu_name = 'Normal' WHERE t_ipsu_id = 31;
UPDATE itsm.t_ipsu SET ipsu_name = 'Urgent' WHERE t_ipsu_id = 32;
UPDATE itsm.t_ipsu SET ipsu_name = 'Immediate' WHERE t_ipsu_id = 33;
UPDATE itsm.t_satisfaction_level SET satisfaction_level = 'Very high' WHERE t_satisfaction_level_id = 1;
UPDATE itsm.t_satisfaction_level SET satisfaction_level = 'High' WHERE t_satisfaction_level_id = 2;
UPDATE itsm.t_satisfaction_level SET satisfaction_level = 'Medium' WHERE t_satisfaction_level_id = 3;
UPDATE itsm.t_satisfaction_level SET satisfaction_level = 'Low' WHERE t_satisfaction_level_id = 4;

UPDATE public.e_probe_category SET name = 'Applications' WHERE e_probe_category_id = 1;
UPDATE public.e_probe_category SET name = 'Assets' WHERE e_probe_category_id = 2;
UPDATE public.e_probe_category SET name = 'Audit' WHERE e_probe_category_id = 3;
UPDATE public.e_probe_category SET name = 'Compliance' WHERE e_probe_category_id = 4;
UPDATE public.e_probe_category SET name = 'Web' WHERE e_probe_category_id = 5;
UPDATE public.e_probe_category SET name = 'IT Operations' WHERE e_probe_category_id = 6;
UPDATE public.e_probe_category SET name = 'IT System management' WHERE e_probe_category_id = 7;
UPDATE public.e_probe_category SET name = 'Spam and mail' WHERE e_probe_category_id = 8;
UPDATE public.e_probe_category SET name = 'Identity management' WHERE e_probe_category_id = 9;
UPDATE public.e_probe_category SET name = 'Network events' WHERE e_probe_category_id = 10;
UPDATE public.e_probe_category SET name = 'Vulnerabilities' WHERE e_probe_category_id = 11;
UPDATE public.e_probe_category SET name = 'User tools' WHERE e_probe_category_id = 12;
UPDATE public.e_probe_category SET name = 'Malwares' WHERE e_probe_category_id = 13;
UPDATE public.e_probe_category SET name = 'Instant messaging' WHERE e_probe_category_id = 14;

