INSERT INTO risk.e_category (e_category_id, category_name) VALUES (1, 'Diseases');
INSERT INTO risk.e_category (e_category_id, category_name) VALUES (2, 'Economic');
INSERT INTO risk.e_category (e_category_id, category_name) VALUES (3, 'Environmental');
INSERT INTO risk.e_category (e_category_id, category_name) VALUES (4, 'Financial');
INSERT INTO risk.e_category (e_category_id, category_name) VALUES (5, 'Human');
INSERT INTO risk.e_category (e_category_id, category_name) VALUES (6, 'Natural hazard');
INSERT INTO risk.e_category (e_category_id, category_name) VALUES (7, 'Health & safety');
INSERT INTO risk.e_category (e_category_id, category_name) VALUES (8, 'Product liability');
INSERT INTO risk.e_category (e_category_id, category_name) VALUES (9, 'Professional liability');
INSERT INTO risk.e_category (e_category_id, category_name) VALUES (10, 'Property damage');
INSERT INTO risk.e_category (e_category_id, category_name) VALUES (11, 'Public liability');
INSERT INTO risk.e_category (e_category_id, category_name) VALUES (12, 'Security');
INSERT INTO risk.e_category (e_category_id, category_name) VALUES (13, 'Technological');
INSERT INTO risk.e_risk_decision (e_risk_decision_id, decision) VALUES (1, 'Reduction');
INSERT INTO risk.e_risk_decision (e_risk_decision_id, decision) VALUES (2, 'Mitigation');
INSERT INTO risk.e_risk_decision (e_risk_decision_id, decision) VALUES (3, 'Avoidance');
INSERT INTO risk.e_risk_decision (e_risk_decision_id, decision) VALUES (4, 'Transfer');
INSERT INTO risk.e_risk_priority (e_risk_priority_id, priority) VALUES (1, 'Minor');
INSERT INTO risk.e_risk_priority (e_risk_priority_id, priority) VALUES (2, 'Low');
INSERT INTO risk.e_risk_priority (e_risk_priority_id, priority) VALUES (3, 'Normal');
INSERT INTO risk.e_risk_priority (e_risk_priority_id, priority) VALUES (4, 'Important');
INSERT INTO risk.e_risk_priority (e_risk_priority_id, priority) VALUES (5, 'Urgent');
INSERT INTO risk.e_risk_priority (e_risk_priority_id, priority) VALUES (6, 'Critical');
INSERT INTO risk.e_risk_level (e_risk_level_id, level) VALUES (1, 'Low');
INSERT INTO risk.e_risk_level (e_risk_level_id, level) VALUES (2, 'Medium');
INSERT INTO risk.e_risk_level (e_risk_level_id, level) VALUES (3, 'Significant');
INSERT INTO risk.e_risk_level (e_risk_level_id, level) VALUES (4, 'High');
INSERT INTO risk.e_action_status (e_action_status_id, action_status) VALUES (1, 'Planning');
INSERT INTO risk.e_action_status (e_action_status_id, action_status) VALUES (2, 'In progress');
INSERT INTO risk.e_action_status (e_action_status_id, action_status) VALUES (3, 'Completed');
INSERT INTO risk.e_action_status (e_action_status_id, action_status) VALUES (4, 'Cancelled');
INSERT INTO risk.e_action_status (e_action_status_id, action_status) VALUES (5, 'Halted');
