INSERT INTO asset.e_asset_type (id, name) VALUES (1, 'Cluster');
INSERT INTO asset.e_asset_type (id, name) VALUES (2, 'Server');
INSERT INTO asset.e_asset_type (id, name) VALUES (3, 'Server Appliance');
INSERT INTO asset.e_asset_type (id, name) VALUES (4, 'Router');
INSERT INTO asset.e_asset_type (id, name) VALUES (5, 'Network Appliance');
INSERT INTO asset.e_asset_type (id, name) VALUES (6, 'Security Appliance');
INSERT INTO asset.e_asset_type (id, name) VALUES (7, 'Access Device');
INSERT INTO asset.e_asset_type (id, name) VALUES (8, 'Mobile Access Device');
INSERT INTO asset.e_asset_type (id, name) VALUES (9, 'Printing Device');
INSERT INTO asset.e_sc (id, name) VALUES (1, 'Business Critical');
INSERT INTO asset.e_sc (id, name) VALUES (2, 'Business Needed');
INSERT INTO asset.e_sc (id, name) VALUES (3, 'Business');
INSERT INTO asset.e_sc (id, name) VALUES (4, 'Business Support');
INSERT INTO asset.e_sc (id, name) VALUES (5, 'Infrastructure');
INSERT INTO asset.e_sc (id, name) VALUES (6, 'Non-Business Critical');
INSERT INTO asset.e_sc (id, name) VALUES (7, 'Non-Business');
INSERT INTO asset.e_bl (id, name) VALUES (1, 'IT');
INSERT INTO asset.e_bl (id, name) VALUES (2, 'Corporate');
INSERT INTO asset.e_bl (id, name) VALUES (3, 'Sales');
INSERT INTO asset.e_bl (id, name) VALUES (4, 'Marketing');
INSERT INTO asset.e_bl (id, name) VALUES (5, 'R&D');
INSERT INTO asset.e_bl (id, name) VALUES (6, 'Production');
INSERT INTO asset.e_bl (id, name) VALUES (7, 'Accounting');
INSERT INTO asset.e_bl (id, name) VALUES (8, 'Finance');
INSERT INTO asset.e_bl (id, name) VALUES (9, 'Fields');
INSERT INTO asset.e_bl (id, name) VALUES (10, 'Business Partners');
INSERT INTO asset.e_availability (id, name) VALUES (1, 'Non-Stop');
INSERT INTO asset.e_availability (id, name) VALUES (2, 'High Availability');
INSERT INTO asset.e_availability (id, name) VALUES (3, '99%');
INSERT INTO asset.e_availability (id, name) VALUES (4, 'Business Hours');
INSERT INTO asset.e_availability (id, name) VALUES (5, 'Best effort');
