INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.rootDir', 'Root directory.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.errorsDir', 'Error directory for incorrect files.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.errorsSize', 'Max size for the error directory.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.reportsDir', 'Directory where generated reports are put.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.defaultCompany', 'Default company name.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.poweredByLogo', 'poweredBy logo file path.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.web.localServerPort', 'Tomcat port.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.web.localServerAddress', 'Local server address.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.web.remoteServerProtocol', 'Protocol.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.mail.MailHelper.hostName', 'SMTP server host name.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.mail.MailHelper.hostPort', 'SMTP server port.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.mail.MailHelper.useTls', 'SMTP server useTls.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.mail.MailHelper.useAuth', 'SMTP server useAuth.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.mail.MailHelper.smtpUser', 'SMTP user.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.feature.attachCalendarFile', 'Attach a ical file for generated emails.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.mail.MailHelper.smtpPassword', 'SMTP password.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.mail.MailHelper.maxTries', 'Number of tries to send an email before failure.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.mail.MailHelper.maxEmailSentAtOnce', 'Max number of emails sent at once.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.mail.MailHelper.iconLocation', 'Logo file path.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.soap.SessionHandler.timeoutMinutes', 'Timeout in minutes.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.soap.soapBase.authMethod', 'Authentication method.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.maxReturnedRows', 'Maximum number of returned rows in datagrid.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.soap.auth.LDAP.base', 'Base for LDAP authentication.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.soap.auth.LDAP.baseFilterString', 'Base filter for LDAP authentication.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.soap.auth.LDAP.userNameField', 'Username field for LDAP authentication.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.soap.auth.LDAP.url', 'URL for LDAP authentication.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.soap.auth.LDAP.searchUserName', 'Search user name for LDAP authentication.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.soap.auth.LDAP.searchPassword', 'Password for LDAP authentication.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpHelper.userAgent', 'User agent for HTTP.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpHelper.useProxy', 'HTTP connexion use proxy.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpHelper.proxyHost', 'HTTP proxy host name.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpHelper.proxyPort', 'HTTP proxy port name.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpHelper.useProxyAuth', 'HTTP proxy use authentication.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpHelper.proxyRealm', 'HTTP proxy realm.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpHelper.proxyScheme', 'HTTP proxy scheme.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpHelper.proxyUserName', 'HTTP proxy user name.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpHelper.proxyPassword', 'HTTP proxy password.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpSslHelper.userAgent', 'User agent for HTTPS.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpSslHelper.useProxy', 'HTTPS connexion use proxy.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpSslHelper.proxyHost', 'HTTPS proxy host name.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpSslHelper.proxyPort', 'HTTPS proxy port name.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpSslHelper.useProxyAuth', 'HTTPS proxy use authentication.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpSslHelper.proxyRealm', 'HTTPS proxy realm.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpSslHelper.proxyScheme', 'HTTPS proxy scheme.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpSslHelper.proxyUserName', 'HTTPS proxy user name.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpSslHelper.proxyPassword', 'HTTPS proxy password.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpSslHelper.keyStore', 'Keystore for HTTPS.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.util.HttpSslHelper.keyStorePassword', 'Keystore password for HTTPS.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.license.LicenseHelper.publicStore', 'Public store to authenticate licenses.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.raci.strict_RACI', 'Strict RACI mode.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.cnilLevel', 'CNIL level.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.logDirectory', 'Path of the directory containing log files.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.probeXmlFile', 'Path of the probes XML file.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.probes.showProbeSnailOnLastNDays', 'Set the default period to check for probes runs.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.module.Admin.can_edit_its_own_expertises', 'Can users edit their own expertises.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.feature.notifyMail', 'Email notification activated.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.feature.notifySelfMail', 'Email notification activated for user for its own email address.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.feature.attachHtmlMail', 'Use HTML emails.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.feature.sendEmailOnExpertiseChange', 'Send email when an expertise changes.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.feature.sendEmailOnRACIChange', 'Send email when a RACI changes.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.feature.sendEmailOnObjectModification', 'Send email when an object changes.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.feature.sendEmailOnObjectCreation', 'Send email when an object is created.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.mail.MailHelper.receiveEmailOnChange', 'RACI levels necessary to receive emails.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.raci.delayRaciChangeOnModule', 'Modules RACI changes are delayed.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.SupportNotifier.supportEmail', 'Email of the support.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.feature.SupportNotifier', 'Is support email notification activated.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.mail.MailHelper.defaultFromAddress', 'Default FROM address.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.security.minPasswordLength', 'Minimum password length.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.security.passwordComplexity', 'Use password complexity.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.security.passwordAge', 'Maximum password age in days.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.security.passwordHistory', 'Number of password per users saved in history.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.security.loginHistoryAge', 'Users login history age in days.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.security.numberOfFailedLoginLimit', 'Number of consecutive failed logins limit that block a user account.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.security.failedLoginTimeLimit', 'Time limit (in min) for consecutive failed logins.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.security.automatedLostPassword', 'Activate the Lost Password button to send a new generated password by email or if email isn''t available a application incident.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.provider.calendar.DbCalendar.redefineFirstDayOfWeek', 'Use system 1st day of week or redefine it.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.provider.calendar.DbCalendar.firstDayOfWeek', '1st day of week (1=Sunday,7=Saturday).');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.module.Admin.language', 'Application language.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.module.Audit.user_see_my_only', 'Users see elements only if they are in the RACI matrix.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.module.Audit.escaladeActionAfterNDelays', 'Number of delays necessary to mark an action as escaladated.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.module.Audit.escaladeRecommendationAfterNDelays', 'Number of delays necessary to mark a recommendation as escaladated.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.feature.hideNewProduct', 'Hide new products imported by probes.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.feature.hideNewVendor', 'Hide new vendors imported by probes.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.soap.soapIdentityManagement.IMReportClassName', 'Report class that will be loaded to get the metrics.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.im.snail_colors.percent_low', 'Percentage (metric/target) under which the metric is considered as good.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.im.snail_colors.percent_medium', 'Percentage (metric/target) under which the metric is considered as quite good.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.im.snail_colors.percent_high', 'Percentage (metric/target) under which the metric is considered as meddle.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.im.snail_colors.percent_bad', 'Percentage (metric/target) under which the metric is considered as quite bad.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.http.average_hits_per_page', 'Average number of hits per page.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.http.average_time_spent_per_page', 'Average time spent on 1 web page (in s).');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.module.Portal.numberOfGridsInChart', 'Number of horizontal grids in line graphs.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.module.Portal.gridFrom0', 'Is the 0 line displayed in line charts.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.module.Portal.ignoredCategories', 'List of Web categories ignored in lists.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.module.Portal.show_others_in_pie', 'Are piecharts displayed with a Other part.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.module.RiskAssessment.user_see_my_only', 'Users see elements only if they are in the RACI matrix.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.module.RiskModelisation.user_see_my_only', 'Users see elements only if they are in the RACI matrix.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.vrt.actions.actions_fixed_before_vuln_fixed', 'A vulnerability can get fixed(or won''t fix) only if all its actions are fixed (or won''t fix).');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.vrt.closed_vrt_vuln_can_change_decision', 'Is it possible to change the decision of a vulnerability if its VRT is closed.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.vrt.user_see_my_only', 'Users see elements only if they are in the RACI matrix.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.vrt.user_see_my_new_only', 'Users see elements only if they are in the RACI matrix in the NEW screen.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.vrt.vote_ignore_decision_ceiling', 'Only used in vote mode where all experts must vote. To avoid vulnerabilities without decision taken due to the absence of an expert, this parameter reprensents the ceiling of votes to give a decision to a vulnerability.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.vrt.vote_instead_of_decision', 'A voting mode is used to triage the vulnerabilities and ignore them or add them to the next VRT.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.vrt.simplifiedVRTProcess', 'In this simplified mode : any vote push the vulnerability in the VRT (so it is a Vote mode, with a ignore decision ceiling to 1), and an action is created for each vote. The vulnerability can be voted until it''s analyzed. In this mode, a vulnerability can be analyzed even if its VRT is not yet started. Triaged vulnerabilities are pushed in the Current VRT (there is no Next VRT). The decision is automatically set to Repair or Ignore, depending of the vote.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.vrt.votesBasedDecision', ' Decisions of voted vulnerabilities can be tuned.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.vrt.votesBasedDecision.IgnoredDecision', 'Decision to be taken for a vulnerability ignored by its votes (table vuln.e_vulnerability_status).');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.vrt.votesBasedDecision.AddDecision', 'Decision to be taken for a vulnerability Add to VRT by its votes (table vuln.e_vulnerability_status).');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.vrt.only_experts_can_vote', 'Only used in vote mode. Only the experts of a vulnerability can vote on a vulnerability.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.vrt.can_vote_until_analysis', 'Only used in vote mode. A vulnerability can receive votes until it''s analyzed for the 1st time.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.vrt.oneVotePerExpertDepartment', 'The member of an expert department that votes on a vulnerability prevent the other members of the group to vote for the vulnerability.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.vrt.createActionOnTriage', 'An action automatically created for each vote (or triage) on a vulnerability.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.vrt.commentRequiredOnIgnore', 'When ignoring a vulnerability, the user has to comment his vote.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.vrt.triageOnRenewedVulnOutdoHigherDecision', 'Triage a a renewed vulnerability always changes the decision.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.provider.vrt.url.securityfocus', 'Pattern URL to view a web version of a SecurityFocus advisory.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.provider.vrt.url.microsoft', 'Pattern URL to view a web version of a Microsoft advisory.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.provider.vrt.url.nist', 'Pattern URL to view a web version of a NVD advisory.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.provider.vrt.url.certist', 'Pattern URL to view a web version of a Cert-IST advisory.');
INSERT INTO public.e_preference_descriptions (parameter, description) VALUES ('com.entelience.esis.feature.notifyNewVulnsForExperts', 'Emails are sent to experts of new vulnerabilities.');
