INSERT INTO audit.e_audit_rec_status (e_audit_rec_status_id, rec_status) VALUES (1, 'Open');
INSERT INTO audit.e_audit_rec_status (e_audit_rec_status_id, rec_status) VALUES (2, 'Closed');
INSERT INTO audit.e_audit_rec_status (e_audit_rec_status_id, rec_status) VALUES (3, 'Risk Accepted');
INSERT INTO audit.e_audit_rec_status (e_audit_rec_status_id, rec_status) VALUES (4, 'Closed Duplicate');
INSERT INTO audit.e_audit_severity (e_audit_severity_id, severity) VALUES (1, 'Low');
INSERT INTO audit.e_audit_severity (e_audit_severity_id, severity) VALUES (2, 'Medium');
INSERT INTO audit.e_audit_severity (e_audit_severity_id, severity) VALUES (3, 'High');
INSERT INTO audit.e_audit_topic (e_audit_topic_id, topic) VALUES (1, 'Network Security');
INSERT INTO audit.e_audit_topic (e_audit_topic_id, topic) VALUES (2, 'Physical Security');
INSERT INTO audit.e_audit_topic (e_audit_topic_id, topic) VALUES (3, 'System Security');
INSERT INTO audit.e_audit_topic (e_audit_topic_id, topic) VALUES (4, 'Access');
INSERT INTO audit.e_audit_topic (e_audit_topic_id, topic) VALUES (5, 'Applications');
INSERT INTO audit.e_audit_topic (e_audit_topic_id, topic) VALUES (6, 'Business');
INSERT INTO audit.e_audit_topic (e_audit_topic_id, topic) VALUES (7, 'Other');
INSERT INTO audit.e_audit_origin (e_audit_origin_id, origin) VALUES (1, 'Internal audit');
INSERT INTO audit.e_audit_origin (e_audit_origin_id, origin) VALUES (2, 'External audit');
INSERT INTO audit.e_audit_origin (e_audit_origin_id, origin) VALUES (3, 'Regulators');
INSERT INTO audit.e_audit_origin (e_audit_origin_id, origin) VALUES (4, 'Self audit');
INSERT INTO audit.e_audit_action_status (e_audit_action_status_id, action_status) VALUES (1, 'Planning');
INSERT INTO audit.e_audit_action_status (e_audit_action_status_id, action_status) VALUES (2, 'In Progress');
INSERT INTO audit.e_audit_action_status (e_audit_action_status_id, action_status) VALUES (3, 'Completed');
INSERT INTO audit.e_audit_action_status (e_audit_action_status_id, action_status) VALUES (4, 'Cancelled');
INSERT INTO audit.e_audit_action_status (e_audit_action_status_id, action_status) VALUES (5, 'Halted');
INSERT INTO audit.e_audit_priority (e_audit_priority_id, priority) VALUES (1, 'Low');
INSERT INTO audit.e_audit_priority (e_audit_priority_id, priority) VALUES (2, 'Medium');
INSERT INTO audit.e_audit_priority (e_audit_priority_id, priority) VALUES (3, 'High');
INSERT INTO audit.e_audit_rec_topic (e_audit_rec_topic_id, topic) VALUES (1, 'Access');
INSERT INTO audit.e_audit_rec_topic (e_audit_rec_topic_id, topic) VALUES (2, 'Network');
INSERT INTO audit.e_audit_rec_topic (e_audit_rec_topic_id, topic) VALUES (3, 'Premises');
INSERT INTO audit.e_audit_rec_topic (e_audit_rec_topic_id, topic) VALUES (4, 'Management');
INSERT INTO audit.e_audit_rec_topic (e_audit_rec_topic_id, topic) VALUES (5, 'Global');
INSERT INTO audit.e_audit_rec_topic (e_audit_rec_topic_id, topic) VALUES (6, 'Monitoring');
INSERT INTO audit.e_audit_rec_topic (e_audit_rec_topic_id, topic) VALUES (7, 'Awareness');
INSERT INTO audit.e_audit_confidentiality (e_audit_confidentiality_id, confidentiality) VALUES (1, 'Internal');
INSERT INTO audit.e_audit_confidentiality (e_audit_confidentiality_id, confidentiality) VALUES (2, 'Confidential');
INSERT INTO audit.e_audit_confidentiality (e_audit_confidentiality_id, confidentiality) VALUES (3, 'Sponsor Only');
INSERT INTO audit.e_audit_confidentiality (e_audit_confidentiality_id, confidentiality) VALUES (4, 'Company Private');
INSERT INTO audit.e_audit_status (e_audit_status_id, status) VALUES (1, 'Planning');
INSERT INTO audit.e_audit_status (e_audit_status_id, status) VALUES (2, 'Contracting');
INSERT INTO audit.e_audit_status (e_audit_status_id, status) VALUES (3, 'Interviews');
INSERT INTO audit.e_audit_status (e_audit_status_id, status) VALUES (4, 'Opening meeting');
INSERT INTO audit.e_audit_status (e_audit_status_id, status) VALUES (5, 'Draft Report');
INSERT INTO audit.e_audit_status (e_audit_status_id, status) VALUES (6, 'Final Report');
INSERT INTO audit.e_audit_status (e_audit_status_id, status) VALUES (7, 'Closing meeting');
INSERT INTO audit.e_audit_status (e_audit_status_id, status) VALUES (8, 'Remediating');
INSERT INTO audit.e_audit_status (e_audit_status_id, status) VALUES (9, 'Closed');
INSERT INTO audit.e_audit_report_status (e_audit_report_status_id, report_status) VALUES (1, 'Draft');
INSERT INTO audit.e_audit_report_status (e_audit_report_status_id, report_status) VALUES (2, 'Final');
INSERT INTO audit.e_audit_report_status (e_audit_report_status_id, report_status) VALUES (3, 'Approved');
INSERT INTO audit.e_audit_report_status (e_audit_report_status_id, report_status) VALUES (4, 'Published');
INSERT INTO audit.e_audit_document_type (e_audit_document_type_id, document_type) VALUES (1, 'Evidence');
INSERT INTO audit.e_audit_document_type (e_audit_document_type_id, document_type) VALUES (2, 'Information');
INSERT INTO audit.e_audit_document_type (e_audit_document_type_id, document_type) VALUES (3, 'Email');
INSERT INTO audit.e_audit_document_type (e_audit_document_type_id, document_type) VALUES (4, 'Document');
