INSERT INTO compliance.e_standard_category (e_standard_category_id, standard_category) VALUES (1, 'Information Technology');
INSERT INTO compliance.e_standard_category (e_standard_category_id, standard_category) VALUES (2, 'General Management');
INSERT INTO compliance.e_topic_category (e_topic_category_id, topic_category) VALUES (1, 'Security Management');
INSERT INTO compliance.e_topic_category (e_topic_category_id, topic_category) VALUES (2, 'Access Control');
INSERT INTO compliance.e_compliance_kind (e_compliance_kind_id, kind) VALUES (1, 'Application comment');
INSERT INTO compliance.e_compliance_kind (e_compliance_kind_id, kind) VALUES (2, 'Documentation comment');
INSERT INTO compliance.e_compliance_type (e_compliance_type_id, compliance_type) VALUES (1, 'Non compliance of minor application');
INSERT INTO compliance.e_compliance_type (e_compliance_type_id, compliance_type) VALUES (2, 'Non compliance of minor documentation');
INSERT INTO compliance.e_compliance_type (e_compliance_type_id, compliance_type) VALUES (3, 'Non compliance of major application');
INSERT INTO compliance.e_compliance_type (e_compliance_type_id, compliance_type) VALUES (4, 'Non compliance of major documentation');
