INSERT INTO mim.t_user_anomaly (t_user_anomaly_id, description) VALUES (1, 'None');
INSERT INTO mim.t_user_anomaly (t_user_anomaly_id, description) VALUES (2, 'Fudge : mainframe data missing');
INSERT INTO mim.t_user_anomaly (t_user_anomaly_id, description) VALUES (3, 'Fudge : mainframe date security admin missing');
INSERT INTO mim.t_user_anomaly (t_user_anomaly_id, description) VALUES (4, 'Fudge : mainframe datecontractvalidity abnormal');
INSERT INTO mim.t_user_anomaly (t_user_anomaly_id, description) VALUES (5, 'Fudge : mainframe date1sthire bad');
INSERT INTO mim.t_user_anomaly (t_user_anomaly_id, description) VALUES (6, 'Fudge : mainframe ou bad');
INSERT INTO mim.t_user_anomaly (t_user_anomaly_id, description) VALUES (7, 'Fudge : mainframe l bad');
INSERT INTO mim.t_user_anomaly (t_user_anomaly_id, description) VALUES (8, 'Fudge : ad data missing');
INSERT INTO mim.t_user_anomaly (t_user_anomaly_id, description) VALUES (9, 'Fudge : ad date is 0');
INSERT INTO mim.t_user_anomaly (t_user_anomaly_id, description) VALUES (10, 'Fudge : hr data missing');
INSERT INTO mim.t_user_anomaly (t_user_anomaly_id, description) VALUES (11, 'Fudge : hr logoncount missing');
INSERT INTO mim.t_user_anomaly (t_user_anomaly_id, description) VALUES (12, 'Fudge : hr still has 19000000 as dates');
INSERT INTO mim.t_user_anomaly (t_user_anomaly_id, description) VALUES (13, 'Fudge : hr still has 19800101 as dates');
