INSERT INTO public.e_file_states (id, state_name) VALUES (-4, 'Aborted, inconsistent data');
INSERT INTO public.e_file_states (id, state_name) VALUES (-3, 'Aborted');
INSERT INTO public.e_file_states (id, state_name) VALUES (-2, 'Downloading');
INSERT INTO public.e_file_states (id, state_name) VALUES (-1, 'Running');
INSERT INTO public.e_file_states (id, state_name) VALUES (0, 'Ready');
INSERT INTO public.e_file_states (id, state_name) VALUES (1, 'Success');
INSERT INTO public.e_file_states (id, state_name) VALUES (2, 'Error - retry');
INSERT INTO public.e_file_states (id, state_name) VALUES (3, 'Failure');
INSERT INTO public.e_file_states (id, state_name) VALUES (4, 'Ignored');
INSERT INTO public.e_file_states (id, state_name) VALUES (5, 'Superceded');
INSERT INTO public.e_file_states (id, state_name) VALUES (6, 'Duplicate');
INSERT INTO public.e_file_states (id, state_name) VALUES (7, 'Success + Archived');
INSERT INTO public.e_file_states (id, state_name) VALUES (8, 'Superceded + Archived');
INSERT INTO public.e_file_states (id, state_name) VALUES (9, 'Duplicate + Archived');
INSERT INTO public.e_file_states (id, state_name) VALUES (10, 'Failure + Archived');
INSERT INTO public.e_file_states (id, state_name) VALUES (11, 'Ignore + Archived');
INSERT INTO public.e_probe_parameter_origin (e_probe_parameter_origin_id, origin) VALUES (1, 'Default value');
INSERT INTO public.e_probe_parameter_origin (e_probe_parameter_origin_id, origin) VALUES (2, 'Database value');
INSERT INTO public.e_probe_parameter_origin (e_probe_parameter_origin_id, origin) VALUES (3, 'XML file');
INSERT INTO public.e_probe_run_status (e_probe_run_status_id, status_name) VALUES (0, 'Never run');
INSERT INTO public.e_probe_run_status (e_probe_run_status_id, status_name) VALUES (1, 'Success');
INSERT INTO public.e_probe_run_status (e_probe_run_status_id, status_name) VALUES (2, 'No data');
INSERT INTO public.e_probe_run_status (e_probe_run_status_id, status_name) VALUES (3, 'Aborted');
INSERT INTO public.e_probe_run_status (e_probe_run_status_id, status_name) VALUES (4, 'Failure');
INSERT INTO public.e_probe_run_status (e_probe_run_status_id, status_name) VALUES (5, 'Error');
INSERT INTO public.e_probe_run_status (e_probe_run_status_id, status_name) VALUES (6, 'Still running');
INSERT INTO public.e_probe_run_status (e_probe_run_status_id, status_name) VALUES (7, 'Aborted with error');
