UPDATE audit.e_audit_rec_status SET rec_status = 'Open' WHERE e_audit_rec_status_id = 1;
UPDATE audit.e_audit_rec_status SET rec_status = 'Closed' WHERE e_audit_rec_status_id = 2;
UPDATE audit.e_audit_rec_status SET rec_status = 'Risk Accepted' WHERE e_audit_rec_status_id = 3;
UPDATE audit.e_audit_rec_status SET rec_status = 'Closed Duplicate' WHERE e_audit_rec_status_id = 4;
UPDATE audit.e_audit_severity SET severity = 'Low' WHERE e_audit_severity_id = 1;
UPDATE audit.e_audit_severity SET severity = 'Medium' WHERE e_audit_severity_id = 2;
UPDATE audit.e_audit_severity SET severity = 'High' WHERE e_audit_severity_id = 3;
UPDATE audit.e_audit_topic SET topic = 'Network Security' WHERE e_audit_topic_id = 1;
UPDATE audit.e_audit_topic SET topic = 'Physical Security' WHERE e_audit_topic_id = 2;
UPDATE audit.e_audit_topic SET topic = 'System Security' WHERE e_audit_topic_id = 3;
UPDATE audit.e_audit_topic SET topic = 'Access' WHERE e_audit_topic_id = 4;
UPDATE audit.e_audit_topic SET topic = 'Applications' WHERE e_audit_topic_id = 5;
UPDATE audit.e_audit_topic SET topic = 'Business' WHERE e_audit_topic_id = 6;
UPDATE audit.e_audit_topic SET topic = 'Other' WHERE e_audit_topic_id = 7;
UPDATE audit.e_audit_origin SET origin = 'Internal audit' WHERE e_audit_origin_id = 1;
UPDATE audit.e_audit_origin SET origin = 'External audit' WHERE e_audit_origin_id = 2;
UPDATE audit.e_audit_origin SET origin = 'Regulators' WHERE e_audit_origin_id = 3;
UPDATE audit.e_audit_origin SET origin = 'Self audit' WHERE e_audit_origin_id = 4;
UPDATE audit.e_audit_action_status SET action_status = 'Planning' WHERE e_audit_action_status_id = 1;
UPDATE audit.e_audit_action_status SET action_status = 'In Progress' WHERE e_audit_action_status_id = 2;
UPDATE audit.e_audit_action_status SET action_status = 'Completed' WHERE e_audit_action_status_id = 3;
UPDATE audit.e_audit_action_status SET action_status = 'Cancelled' WHERE e_audit_action_status_id = 4;
UPDATE audit.e_audit_action_status SET action_status = 'Halted' WHERE e_audit_action_status_id = 5;
UPDATE audit.e_audit_priority SET priority = 'Low' WHERE e_audit_priority_id = 1;
UPDATE audit.e_audit_priority SET priority = 'Medium' WHERE e_audit_priority_id = 2;
UPDATE audit.e_audit_priority SET priority = 'High' WHERE e_audit_priority_id = 3;
UPDATE audit.e_audit_rec_topic SET topic = 'Access' WHERE e_audit_rec_topic_id = 1;
UPDATE audit.e_audit_rec_topic SET topic = 'Network' WHERE e_audit_rec_topic_id = 2;
UPDATE audit.e_audit_rec_topic SET topic = 'Premises' WHERE e_audit_rec_topic_id = 3;
UPDATE audit.e_audit_rec_topic SET topic = 'Management' WHERE e_audit_rec_topic_id = 4;
UPDATE audit.e_audit_rec_topic SET topic = 'Global' WHERE e_audit_rec_topic_id = 5;
UPDATE audit.e_audit_rec_topic SET topic = 'Monitoring' WHERE e_audit_rec_topic_id = 6;
UPDATE audit.e_audit_rec_topic SET topic = 'Awareness' WHERE e_audit_rec_topic_id = 7;
UPDATE audit.e_audit_confidentiality SET confidentiality = 'Internal' WHERE e_audit_confidentiality_id = 1;
UPDATE audit.e_audit_confidentiality SET confidentiality = 'Confidential' WHERE e_audit_confidentiality_id = 2;
UPDATE audit.e_audit_confidentiality SET confidentiality = 'Sponsor Only' WHERE e_audit_confidentiality_id = 3;
UPDATE audit.e_audit_confidentiality SET confidentiality = 'Company Private' WHERE e_audit_confidentiality_id = 4;
UPDATE audit.e_audit_status SET status = 'Planning' WHERE e_audit_status_id = 1;
UPDATE audit.e_audit_status SET status = 'Contracting' WHERE e_audit_status_id = 2;
UPDATE audit.e_audit_status SET status = 'Interviews' WHERE e_audit_status_id = 3;
UPDATE audit.e_audit_status SET status = 'Opening meeting' WHERE e_audit_status_id = 4;
UPDATE audit.e_audit_status SET status = 'Draft Report' WHERE e_audit_status_id = 5;
UPDATE audit.e_audit_status SET status = 'Final Report' WHERE e_audit_status_id = 6;
UPDATE audit.e_audit_status SET status = 'Closing meeting' WHERE e_audit_status_id = 7;
UPDATE audit.e_audit_status SET status = 'Remediating' WHERE e_audit_status_id = 8;
UPDATE audit.e_audit_status SET status = 'Closed' WHERE e_audit_status_id = 9;
UPDATE audit.e_audit_report_status SET report_status = 'Draft' WHERE e_audit_report_status_id = 1;
UPDATE audit.e_audit_report_status SET report_status = 'Final' WHERE e_audit_report_status_id = 2;
UPDATE audit.e_audit_report_status SET report_status = 'Approved' WHERE e_audit_report_status_id = 3;
UPDATE audit.e_audit_report_status SET report_status = 'Published' WHERE e_audit_report_status_id = 4;
UPDATE audit.e_audit_document_type SET document_type = 'Evidence' WHERE e_audit_document_type_id = 1;
UPDATE audit.e_audit_document_type SET document_type = 'Information' WHERE e_audit_document_type_id = 2;
UPDATE audit.e_audit_document_type SET document_type = 'Email' WHERE e_audit_document_type_id = 3;
UPDATE audit.e_audit_document_type SET document_type = 'Document' WHERE e_audit_document_type_id = 4;
