UPDATE risk.e_category SET category_name = 'Diseases' WHERE e_category_id = 1;
UPDATE risk.e_category SET category_name = 'Economic' WHERE e_category_id = 2;
UPDATE risk.e_category SET category_name = 'Environmental' WHERE e_category_id = 3;
UPDATE risk.e_category SET category_name = 'Financial' WHERE e_category_id = 4;
UPDATE risk.e_category SET category_name = 'Human' WHERE e_category_id = 5;
UPDATE risk.e_category SET category_name = 'Natural hazard' WHERE e_category_id = 6;
UPDATE risk.e_category SET category_name = 'Health & safety' WHERE e_category_id = 7;
UPDATE risk.e_category SET category_name = 'Product liability' WHERE e_category_id = 8;
UPDATE risk.e_category SET category_name = 'Professional liability' WHERE e_category_id = 9;
UPDATE risk.e_category SET category_name = 'Property damage' WHERE e_category_id = 10;
UPDATE risk.e_category SET category_name = 'Public liability' WHERE e_category_id = 11;
UPDATE risk.e_category SET category_name = 'Security' WHERE e_category_id = 12;
UPDATE risk.e_category SET category_name = 'Technological' WHERE e_category_id = 13;
UPDATE risk.e_risk_decision SET decision = 'Reduction' WHERE e_risk_decision_id = 1;
UPDATE risk.e_risk_decision SET decision = 'Mitigation' WHERE e_risk_decision_id = 2;
UPDATE risk.e_risk_decision SET decision = 'Avoidance' WHERE e_risk_decision_id = 3;
UPDATE risk.e_risk_decision SET decision = 'Transfer' WHERE e_risk_decision_id = 4;
UPDATE risk.e_risk_priority SET priority = 'Minor' WHERE e_risk_priority_id = 1;
UPDATE risk.e_risk_priority SET priority = 'Low' WHERE e_risk_priority_id = 2;
UPDATE risk.e_risk_priority SET priority = 'Normal' WHERE e_risk_priority_id = 3;
UPDATE risk.e_risk_priority SET priority = 'Important' WHERE e_risk_priority_id = 4;
UPDATE risk.e_risk_priority SET priority = 'Urgent' WHERE e_risk_priority_id = 5;
UPDATE risk.e_risk_priority SET priority = 'Critical' WHERE e_risk_priority_id = 6;
UPDATE risk.e_risk_level SET level = 'Low' WHERE e_risk_level_id = 1;
UPDATE risk.e_risk_level SET level = 'Medium' WHERE e_risk_level_id = 2;
UPDATE risk.e_risk_level SET level = 'Significant' WHERE e_risk_level_id = 3;
UPDATE risk.e_risk_level SET level = 'High' WHERE e_risk_level_id = 4;
UPDATE risk.e_action_status SET action_status = 'Planning' WHERE e_action_status_id = 1;
UPDATE risk.e_action_status SET action_status = 'In progress' WHERE e_action_status_id = 2;
UPDATE risk.e_action_status SET action_status = 'Completed' WHERE e_action_status_id = 3;
UPDATE risk.e_action_status SET action_status = 'Cancelled' WHERE e_action_status_id = 4;
UPDATE risk.e_action_status SET action_status = 'Halted' WHERE e_action_status_id = 5;
