UPDATE public.e_preference_descriptions SET description = 'Root directory.' WHERE parameter = 'com.entelience.esis.rootDir';
UPDATE public.e_preference_descriptions SET description = 'Error directory for incorrect files.' WHERE parameter = 'com.entelience.esis.errorsDir';
UPDATE public.e_preference_descriptions SET description = 'Max size for the error directory.' WHERE parameter = 'com.entelience.esis.errorsSize';
UPDATE public.e_preference_descriptions SET description = 'Directory where generated reports are put.' WHERE parameter = 'com.entelience.esis.reportsDir';
UPDATE public.e_preference_descriptions SET description = 'Default company name.' WHERE parameter = 'com.entelience.esis.defaultCompany';
UPDATE public.e_preference_descriptions SET description = 'poweredBy logo file path.' WHERE parameter = 'com.entelience.esis.poweredByLogo';
UPDATE public.e_preference_descriptions SET description = 'Tomcat port.' WHERE parameter = 'com.entelience.esis.web.localServerPort';
UPDATE public.e_preference_descriptions SET description = 'Local server address.' WHERE parameter = 'com.entelience.esis.web.localServerAddress';
UPDATE public.e_preference_descriptions SET description = 'Protocol.' WHERE parameter = 'com.entelience.esis.web.remoteServerProtocol';
UPDATE public.e_preference_descriptions SET description = 'SMTP server host name.' WHERE parameter = 'com.entelience.mail.MailHelper.hostName';
UPDATE public.e_preference_descriptions SET description = 'SMTP server port.' WHERE parameter = 'com.entelience.mail.MailHelper.hostPort';
UPDATE public.e_preference_descriptions SET description = 'SMTP server useTls.' WHERE parameter = 'com.entelience.mail.MailHelper.useTls';
UPDATE public.e_preference_descriptions SET description = 'SMTP server useAuth.' WHERE parameter = 'com.entelience.mail.MailHelper.useAuth';
UPDATE public.e_preference_descriptions SET description = 'SMTP user.' WHERE parameter = 'com.entelience.mail.MailHelper.smtpUser';
UPDATE public.e_preference_descriptions SET description = 'Attach a ical file for generated emails.' WHERE parameter = 'com.entelience.esis.feature.attachCalendarFile';
UPDATE public.e_preference_descriptions SET description = 'SMTP password.' WHERE parameter = 'com.entelience.mail.MailHelper.smtpPassword';
UPDATE public.e_preference_descriptions SET description = 'Number of tries to send an email before failure.' WHERE parameter = 'com.entelience.mail.MailHelper.maxTries';
UPDATE public.e_preference_descriptions SET description = 'Max number of emails sent at once.' WHERE parameter = 'com.entelience.mail.MailHelper.maxEmailSentAtOnce';
UPDATE public.e_preference_descriptions SET description = 'Logo file path.' WHERE parameter = 'com.entelience.mail.MailHelper.iconLocation';
UPDATE public.e_preference_descriptions SET description = 'Timeout in minutes.' WHERE parameter = 'com.entelience.soap.SessionHandler.timeoutMinutes';
UPDATE public.e_preference_descriptions SET description = 'Authentication method.' WHERE parameter = 'com.entelience.soap.soapBase.authMethod';
UPDATE public.e_preference_descriptions SET description = 'Maximum number of returned rows in datagrid.' WHERE parameter = 'com.entelience.esis.maxReturnedRows';
UPDATE public.e_preference_descriptions SET description = 'Base for LDAP authentication.' WHERE parameter = 'com.entelience.soap.auth.LDAP.base';
UPDATE public.e_preference_descriptions SET description = 'Base filter for LDAP authentication.' WHERE parameter = 'com.entelience.soap.auth.LDAP.baseFilterString';
UPDATE public.e_preference_descriptions SET description = 'Username field for LDAP authentication.' WHERE parameter = 'com.entelience.soap.auth.LDAP.userNameField';
UPDATE public.e_preference_descriptions SET description = 'URL for LDAP authentication.' WHERE parameter = 'com.entelience.soap.auth.LDAP.url';
UPDATE public.e_preference_descriptions SET description = 'Search user name for LDAP authentication.' WHERE parameter = 'com.entelience.soap.auth.LDAP.searchUserName';
UPDATE public.e_preference_descriptions SET description = 'Password for LDAP authentication.' WHERE parameter = 'com.entelience.soap.auth.LDAP.searchPassword';
UPDATE public.e_preference_descriptions SET description = 'User agent for HTTP.' WHERE parameter = 'com.entelience.util.HttpHelper.userAgent';
UPDATE public.e_preference_descriptions SET description = 'HTTP connexion use proxy.' WHERE parameter = 'com.entelience.util.HttpHelper.useProxy';
UPDATE public.e_preference_descriptions SET description = 'HTTP proxy host name.' WHERE parameter = 'com.entelience.util.HttpHelper.proxyHost';
UPDATE public.e_preference_descriptions SET description = 'HTTP proxy port name.' WHERE parameter = 'com.entelience.util.HttpHelper.proxyPort';
UPDATE public.e_preference_descriptions SET description = 'HTTP proxy use authentication.' WHERE parameter = 'com.entelience.util.HttpHelper.useProxyAuth';
UPDATE public.e_preference_descriptions SET description = 'HTTP proxy realm.' WHERE parameter = 'com.entelience.util.HttpHelper.proxyRealm';
UPDATE public.e_preference_descriptions SET description = 'HTTP proxy scheme.' WHERE parameter = 'com.entelience.util.HttpHelper.proxyScheme';
UPDATE public.e_preference_descriptions SET description = 'HTTP proxy user name.' WHERE parameter = 'com.entelience.util.HttpHelper.proxyUserName';
UPDATE public.e_preference_descriptions SET description = 'HTTP proxy password.' WHERE parameter = 'com.entelience.util.HttpHelper.proxyPassword';
UPDATE public.e_preference_descriptions SET description = 'User agent for HTTPS.' WHERE parameter = 'com.entelience.util.HttpSslHelper.userAgent';
UPDATE public.e_preference_descriptions SET description = 'HTTPS connexion use proxy.' WHERE parameter = 'com.entelience.util.HttpSslHelper.useProxy';
UPDATE public.e_preference_descriptions SET description = 'HTTPS proxy host name.' WHERE parameter = 'com.entelience.util.HttpSslHelper.proxyHost';
UPDATE public.e_preference_descriptions SET description = 'HTTPS proxy port name.' WHERE parameter = 'com.entelience.util.HttpSslHelper.proxyPort';
UPDATE public.e_preference_descriptions SET description = 'HTTPS proxy use authentication.' WHERE parameter = 'com.entelience.util.HttpSslHelper.useProxyAuth';
UPDATE public.e_preference_descriptions SET description = 'HTTPS proxy realm.' WHERE parameter = 'com.entelience.util.HttpSslHelper.proxyRealm';
UPDATE public.e_preference_descriptions SET description = 'HTTPS proxy scheme.' WHERE parameter = 'com.entelience.util.HttpSslHelper.proxyScheme';
UPDATE public.e_preference_descriptions SET description = 'HTTPS proxy user name.' WHERE parameter = 'com.entelience.util.HttpSslHelper.proxyUserName';
UPDATE public.e_preference_descriptions SET description = 'HTTPS proxy password.' WHERE parameter = 'com.entelience.util.HttpSslHelper.proxyPassword';
UPDATE public.e_preference_descriptions SET description = 'Keystore for HTTPS.' WHERE parameter = 'com.entelience.util.HttpSslHelper.keyStore';
UPDATE public.e_preference_descriptions SET description = 'Keystore password for HTTPS.' WHERE parameter = 'com.entelience.util.HttpSslHelper.keyStorePassword';
UPDATE public.e_preference_descriptions SET description = 'Public store to authenticate licenses.' WHERE parameter = 'com.entelience.license.LicenseHelper.publicStore';
UPDATE public.e_preference_descriptions SET description = 'Strict RACI mode.' WHERE parameter = 'com.entelience.raci.strict_RACI';
UPDATE public.e_preference_descriptions SET description = 'CNIL level.' WHERE parameter = 'com.entelience.esis.cnilLevel';
UPDATE public.e_preference_descriptions SET description = 'Path of the directory containing log files.' WHERE parameter = 'com.entelience.esis.logDirectory';
UPDATE public.e_preference_descriptions SET description = 'Path of the probes XML file.' WHERE parameter = 'com.entelience.esis.probeXmlFile';
UPDATE public.e_preference_descriptions SET description = 'Set the default period to check for probes runs.' WHERE parameter = 'com.entelience.probes.showProbeSnailOnLastNDays';
UPDATE public.e_preference_descriptions SET description = 'Can users edit their own expertises.' WHERE parameter = 'com.entelience.module.Admin.can_edit_its_own_expertises';
UPDATE public.e_preference_descriptions SET description = 'Email notification activated.' WHERE parameter = 'com.entelience.esis.feature.notifyMail';
UPDATE public.e_preference_descriptions SET description = 'Email notification activated for user for its own email address.' WHERE parameter = 'com.entelience.esis.feature.notifySelfMail';
UPDATE public.e_preference_descriptions SET description = 'Use HTML emails.' WHERE parameter = 'com.entelience.esis.feature.attachHtmlMail';
UPDATE public.e_preference_descriptions SET description = 'Send email when an expertise changes.' WHERE parameter = 'com.entelience.esis.feature.sendEmailOnExpertiseChange';
UPDATE public.e_preference_descriptions SET description = 'Send email when a RACI changes.' WHERE parameter = 'com.entelience.esis.feature.sendEmailOnRACIChange';
UPDATE public.e_preference_descriptions SET description = 'Send email when an object changes.' WHERE parameter = 'com.entelience.esis.feature.sendEmailOnObjectModification';
UPDATE public.e_preference_descriptions SET description = 'Send email when an object is created.' WHERE parameter = 'com.entelience.esis.feature.sendEmailOnObjectCreation';
UPDATE public.e_preference_descriptions SET description = 'RACI levels necessary to receive emails.' WHERE parameter = 'com.entelience.mail.MailHelper.receiveEmailOnChange';
UPDATE public.e_preference_descriptions SET description = 'Modules RACI changes are delayed.' WHERE parameter = 'com.entelience.raci.delayRaciChangeOnModule';
UPDATE public.e_preference_descriptions SET description = 'Email of the support.' WHERE parameter = 'com.entelience.esis.SupportNotifier.supportEmail';
UPDATE public.e_preference_descriptions SET description = 'Is support email notification activated.' WHERE parameter = 'com.entelience.esis.feature.SupportNotifier';
UPDATE public.e_preference_descriptions SET description = 'Default FROM address.' WHERE parameter = 'com.entelience.mail.MailHelper.defaultFromAddress';
UPDATE public.e_preference_descriptions SET description = 'Minimum password length.' WHERE parameter = 'com.entelience.esis.security.minPasswordLength';
UPDATE public.e_preference_descriptions SET description = 'Use password complexity.' WHERE parameter = 'com.entelience.esis.security.passwordComplexity';
UPDATE public.e_preference_descriptions SET description = 'Maximum password age in days.' WHERE parameter = 'com.entelience.esis.security.passwordAge';
UPDATE public.e_preference_descriptions SET description = 'Number of password per users saved in history.' WHERE parameter = 'com.entelience.esis.security.passwordHistory';
UPDATE public.e_preference_descriptions SET description = 'Users login history age in days.' WHERE parameter = 'com.entelience.esis.security.loginHistoryAge';
UPDATE public.e_preference_descriptions SET description = 'Number of consecutive failed logins limit that block a user account.' WHERE parameter = 'com.entelience.esis.security.numberOfFailedLoginLimit';
UPDATE public.e_preference_descriptions SET description = 'Time limit (in min) for consecutive failed logins.' WHERE parameter = 'com.entelience.esis.security.failedLoginTimeLimit';
UPDATE public.e_preference_descriptions SET description = 'Activate the Lost Password button to send a new generated password by email or if email isn''t available a application incident.' WHERE parameter = 'com.entelience.esis.security.automatedLostPassword';
UPDATE public.e_preference_descriptions SET description = 'Use system 1st day of week or redefine it.' WHERE parameter = 'com.entelience.provider.calendar.DbCalendar.redefineFirstDayOfWeek';
UPDATE public.e_preference_descriptions SET description = '1st day of week (1=Sunday,7=Saturday).' WHERE parameter = 'com.entelience.provider.calendar.DbCalendar.firstDayOfWeek';
UPDATE public.e_preference_descriptions SET description = 'Application language.' WHERE parameter = 'com.entelience.module.Admin.language';
UPDATE public.e_preference_descriptions SET description = 'Users see elements only if they are in the RACI matrix.' WHERE parameter = 'com.entelience.module.Audit.user_see_my_only';
UPDATE public.e_preference_descriptions SET description = 'Number of delays necessary to mark an action as escaladated.' WHERE parameter = 'com.entelience.module.Audit.escaladeActionAfterNDelays';
UPDATE public.e_preference_descriptions SET description = 'Number of delays necessary to mark a recommendation as escaladated.' WHERE parameter = 'com.entelience.module.Audit.escaladeRecommendationAfterNDelays';
UPDATE public.e_preference_descriptions SET description = 'Hide new products imported by probes.' WHERE parameter = 'com.entelience.esis.feature.hideNewProduct';
UPDATE public.e_preference_descriptions SET description = 'Hide new vendors imported by probes.' WHERE parameter = 'com.entelience.esis.feature.hideNewVendor';
UPDATE public.e_preference_descriptions SET description = 'Report class that will be loaded to get the metrics.' WHERE parameter = 'com.entelience.soap.soapIdentityManagement.IMReportClassName';
UPDATE public.e_preference_descriptions SET description = 'Percentage (metric/target) under which the metric is considered as good.' WHERE parameter = 'com.entelience.esis.im.snail_colors.percent_low';
UPDATE public.e_preference_descriptions SET description = 'Percentage (metric/target) under which the metric is considered as quite good.' WHERE parameter = 'com.entelience.esis.im.snail_colors.percent_medium';
UPDATE public.e_preference_descriptions SET description = 'Percentage (metric/target) under which the metric is considered as meddle.' WHERE parameter = 'com.entelience.esis.im.snail_colors.percent_high';
UPDATE public.e_preference_descriptions SET description = 'Percentage (metric/target) under which the metric is considered as quite bad.' WHERE parameter = 'com.entelience.esis.im.snail_colors.percent_bad';
UPDATE public.e_preference_descriptions SET description = 'Average number of hits per page.' WHERE parameter = 'com.entelience.http.average_hits_per_page';
UPDATE public.e_preference_descriptions SET description = 'Average time spent on 1 web page (in s).' WHERE parameter = 'com.entelience.http.average_time_spent_per_page';
UPDATE public.e_preference_descriptions SET description = 'Number of horizontal grids in line graphs.' WHERE parameter = 'com.entelience.module.Portal.numberOfGridsInChart';
UPDATE public.e_preference_descriptions SET description = 'Is the 0 line displayed in line charts.' WHERE parameter = 'com.entelience.module.Portal.gridFrom0';
UPDATE public.e_preference_descriptions SET description = 'List of Web categories ignored in lists.' WHERE parameter = 'com.entelience.module.Portal.ignoredCategories';
UPDATE public.e_preference_descriptions SET description = 'Are piecharts displayed with a Other part.' WHERE parameter = 'com.entelience.module.Portal.show_others_in_pie';
UPDATE public.e_preference_descriptions SET description = 'Users see elements only if they are in the RACI matrix.' WHERE parameter = 'com.entelience.module.RiskAssessment.user_see_my_only';
UPDATE public.e_preference_descriptions SET description = 'Users see elements only if they are in the RACI matrix.' WHERE parameter = 'com.entelience.module.RiskModelisation.user_see_my_only';
UPDATE public.e_preference_descriptions SET description = 'A vulnerability can get fixed(or won''t fix) only if all its actions are fixed (or won''t fix).' WHERE parameter = 'com.entelience.esis.vrt.actions.actions_fixed_before_vuln_fixed';
UPDATE public.e_preference_descriptions SET description = 'Is it possible to change the decision of a vulnerability if its VRT is closed.' WHERE parameter = 'com.entelience.esis.vrt.closed_vrt_vuln_can_change_decision';
UPDATE public.e_preference_descriptions SET description = 'Users see elements only if they are in the RACI matrix.' WHERE parameter = 'com.entelience.esis.vrt.user_see_my_only';
UPDATE public.e_preference_descriptions SET description = 'Users see elements only if they are in the RACI matrix in the NEW screen.' WHERE parameter = 'com.entelience.esis.vrt.user_see_my_new_only';
UPDATE public.e_preference_descriptions SET description = 'Only used in vote mode where all experts must vote. To avoid vulnerabilities without decision taken due to the absence of an expert, this parameter reprensents the ceiling of votes to give a decision to a vulnerability.' WHERE parameter = 'com.entelience.esis.vrt.vote_ignore_decision_ceiling';
UPDATE public.e_preference_descriptions SET description = 'A voting mode is used to triage the vulnerabilities and ignore them or add them to the next VRT.' WHERE parameter = 'com.entelience.esis.vrt.vote_instead_of_decision';
UPDATE public.e_preference_descriptions SET description = 'In this simplified mode : any vote push the vulnerability in the VRT (so it is a Vote mode, with a ignore decision ceiling to 1), and an action is created for each vote. The vulnerability can be voted until it''s analyzed. In this mode, a vulnerability can be analyzed even if its VRT is not yet started. Triaged vulnerabilities are pushed in the Current VRT (there is no Next VRT). The decision is automatically set to Repair or Ignore, depending of the vote.' WHERE parameter = 'com.entelience.esis.vrt.simplifiedVRTProcess';
UPDATE public.e_preference_descriptions SET description = ' Decisions of voted vulnerabilities can be tuned.' WHERE parameter = 'com.entelience.esis.vrt.votesBasedDecision';
UPDATE public.e_preference_descriptions SET description = 'Decision to be taken for a vulnerability ignored by its votes (table vuln.e_vulnerability_status).' WHERE parameter = 'com.entelience.esis.vrt.votesBasedDecision.IgnoredDecision';
UPDATE public.e_preference_descriptions SET description = 'Decision to be taken for a vulnerability Add to VRT by its votes (table vuln.e_vulnerability_status).' WHERE parameter = 'com.entelience.esis.vrt.votesBasedDecision.AddDecision';
UPDATE public.e_preference_descriptions SET description = 'Only used in vote mode. Only the experts of a vulnerability can vote on a vulnerability.' WHERE parameter = 'com.entelience.esis.vrt.only_experts_can_vote';
UPDATE public.e_preference_descriptions SET description = 'Only used in vote mode. A vulnerability can receive votes until it''s analyzed for the 1st time.' WHERE parameter = 'com.entelience.esis.vrt.can_vote_until_analysis';
UPDATE public.e_preference_descriptions SET description = 'The member of an expert department that votes on a vulnerability prevent the other members of the group to vote for the vulnerability.' WHERE parameter = 'com.entelience.esis.vrt.oneVotePerExpertDepartment';
UPDATE public.e_preference_descriptions SET description = 'An action automatically created for each vote (or triage) on a vulnerability.' WHERE parameter = 'com.entelience.esis.vrt.createActionOnTriage';
UPDATE public.e_preference_descriptions SET description = 'When ignoring a vulnerability, the user has to comment his vote.' WHERE parameter = 'com.entelience.esis.vrt.commentRequiredOnIgnore';
UPDATE public.e_preference_descriptions SET description = 'Triage a a renewed vulnerability always changes the decision.' WHERE parameter = 'com.entelience.esis.vrt.triageOnRenewedVulnOutdoHigherDecision';
UPDATE public.e_preference_descriptions SET description = 'Pattern URL to view a web version of a SecurityFocus advisory.' WHERE parameter = 'com.entelience.provider.vrt.url.securityfocus';
UPDATE public.e_preference_descriptions SET description = 'Pattern URL to view a web version of a Microsoft advisory.' WHERE parameter = 'com.entelience.provider.vrt.url.microsoft';
UPDATE public.e_preference_descriptions SET description = 'Pattern URL to view a web version of a NVD advisory.' WHERE parameter = 'com.entelience.provider.vrt.url.nist';
UPDATE public.e_preference_descriptions SET description = 'Pattern URL to view a web version of a Cert-IST advisory.' WHERE parameter = 'com.entelience.provider.vrt.url.certist';
UPDATE public.e_preference_descriptions SET description = 'Emails are sent to experts of new vulnerabilities.' WHERE parameter = 'com.entelience.esis.feature.notifyNewVulnsForExperts';
