UPDATE public.e_file_states SET state_name = 'Aborted, inconsistent data' WHERE id = -4;
UPDATE public.e_file_states SET state_name = 'Aborted' WHERE id = -3;
UPDATE public.e_file_states SET state_name = 'Downloading' WHERE id = -2;
UPDATE public.e_file_states SET state_name = 'Running' WHERE id = -1;
UPDATE public.e_file_states SET state_name = 'Ready' WHERE id = 0;
UPDATE public.e_file_states SET state_name = 'Success' WHERE id = 1;
UPDATE public.e_file_states SET state_name = 'Error - retry' WHERE id = 2;
UPDATE public.e_file_states SET state_name = 'Failure' WHERE id = 3;
UPDATE public.e_file_states SET state_name = 'Ignored' WHERE id = 4;
UPDATE public.e_file_states SET state_name = 'Superceded' WHERE id = 5;
UPDATE public.e_file_states SET state_name = 'Duplicate' WHERE id = 6;
UPDATE public.e_file_states SET state_name = 'Success + Archived' WHERE id = 7;
UPDATE public.e_file_states SET state_name = 'Superceded + Archived' WHERE id = 8;
UPDATE public.e_file_states SET state_name = 'Duplicate + Archived' WHERE id = 9;
UPDATE public.e_file_states SET state_name = 'Failure + Archived' WHERE id = 10;
UPDATE public.e_file_states SET state_name = 'Ignore + Archived' WHERE id = 11;
UPDATE public.e_probe_parameter_origin SET origin = 'Default value' WHERE e_probe_parameter_origin_id = 1;
UPDATE public.e_probe_parameter_origin SET origin = 'Database value' WHERE e_probe_parameter_origin_id = 2;
UPDATE public.e_probe_parameter_origin SET origin = 'XML file' WHERE e_probe_parameter_origin_id = 3;
UPDATE public.e_probe_run_status SET status_name = 'Never run' WHERE e_probe_run_status_id = 0;
UPDATE public.e_probe_run_status SET status_name = 'Success' WHERE e_probe_run_status_id = 1;
UPDATE public.e_probe_run_status SET status_name = 'No data' WHERE e_probe_run_status_id = 2;
UPDATE public.e_probe_run_status SET status_name = 'Aborted' WHERE e_probe_run_status_id = 3;
UPDATE public.e_probe_run_status SET status_name = 'Failure' WHERE e_probe_run_status_id = 4;
UPDATE public.e_probe_run_status SET status_name = 'Error' WHERE e_probe_run_status_id = 5;
UPDATE public.e_probe_run_status SET status_name = 'Still running' WHERE e_probe_run_status_id = 6;
UPDATE public.e_probe_run_status SET status_name = 'Aborted with error' WHERE e_probe_run_status_id = 7;
