UPDATE itops.t_alert_severity SET severity_name = 'Information' WHERE t_alert_severity_id = 1;
UPDATE itops.t_alert_severity SET severity_name = 'Warning' WHERE t_alert_severity_id = 2;
UPDATE itops.t_alert_severity SET severity_name = 'Critical' WHERE t_alert_severity_id = 3;
UPDATE itops.t_alert_priority SET priority_name = 'Low' WHERE t_alert_priority_id = 1;
UPDATE itops.t_alert_priority SET priority_name = 'Medium' WHERE t_alert_priority_id = 2;
UPDATE itops.t_alert_priority SET priority_name = 'High' WHERE t_alert_priority_id = 3;
UPDATE itops.t_event_level SET event_level = 'Success' WHERE t_event_level_id = 1;
UPDATE itops.t_event_level SET event_level = 'Error' WHERE t_event_level_id = 2;
UPDATE itops.t_event_level SET event_level = 'Warning' WHERE t_event_level_id = 3;
UPDATE itops.t_event_level SET event_level = 'Information' WHERE t_event_level_id = 4;
UPDATE itops.t_event_level SET event_level = 'Audit Success' WHERE t_event_level_id = 5;
UPDATE itops.t_event_level SET event_level = 'Audit Failure' WHERE t_event_level_id = 6;
