UPDATE asset.e_asset_type SET name = 'Cluster' WHERE id = 1;
UPDATE asset.e_asset_type SET name = 'Server' WHERE id = 2;
UPDATE asset.e_asset_type SET name = 'Server Appliance' WHERE id = 3;
UPDATE asset.e_asset_type SET name = 'Router' WHERE id = 4;
UPDATE asset.e_asset_type SET name = 'Network Appliance' WHERE id = 5;
UPDATE asset.e_asset_type SET name = 'Security Appliance' WHERE id = 6;
UPDATE asset.e_asset_type SET name = 'Access Device' WHERE id = 7;
UPDATE asset.e_asset_type SET name = 'Mobile Access Device' WHERE id = 8;
UPDATE asset.e_asset_type SET name = 'Printing Device' WHERE id = 9;
UPDATE asset.e_sc SET name = 'Business Critical' WHERE id = 1;
UPDATE asset.e_sc SET name = 'Business Needed' WHERE id = 2;
UPDATE asset.e_sc SET name = 'Business' WHERE id = 3;
UPDATE asset.e_sc SET name = 'Business Support' WHERE id = 4;
UPDATE asset.e_sc SET name = 'Infrastructure' WHERE id = 5;
UPDATE asset.e_sc SET name = 'Non-Business Critical' WHERE id = 6;
UPDATE asset.e_sc SET name = 'Non-Business' WHERE id = 7;
UPDATE asset.e_bl SET name = 'IT' WHERE id = 1;
UPDATE asset.e_bl SET name = 'Corporate' WHERE id = 2;
UPDATE asset.e_bl SET name = 'Sales' WHERE id = 3;
UPDATE asset.e_bl SET name = 'Marketing' WHERE id = 4;
UPDATE asset.e_bl SET name = 'R&D' WHERE id = 5;
UPDATE asset.e_bl SET name = 'Production' WHERE id = 6;
UPDATE asset.e_bl SET name = 'Accounting' WHERE id = 7;
UPDATE asset.e_bl SET name = 'Finance' WHERE id = 8;
UPDATE asset.e_bl SET name = 'Fields' WHERE id = 9;
UPDATE asset.e_bl SET name = 'Business Partners' WHERE id = 10;
UPDATE asset.e_availability SET name = 'Non-Stop' WHERE id = 1;
UPDATE asset.e_availability SET name = 'High Availability' WHERE id = 2;
UPDATE asset.e_availability SET name = '99%' WHERE id = 3;
UPDATE asset.e_availability SET name = 'Business Hours' WHERE id = 4;
UPDATE asset.e_availability SET name = 'Best effort' WHERE id = 5;
