UPDATE itsm.t_status SET status_name = 'New' WHERE t_status_id = 1;
UPDATE itsm.t_status SET status_name = 'Pending' WHERE t_status_id = 2;
UPDATE itsm.t_status SET status_name = 'Cancelled' WHERE t_status_id = 3;
UPDATE itsm.t_status SET status_name = 'Fixed' WHERE t_status_id = 4;
UPDATE itsm.t_status SET status_name = 'Won''t fix' WHERE t_status_id = 5;
UPDATE itsm.t_status SET status_name = 'Closed' WHERE t_status_id = 6;
UPDATE itsm.t_ipsu SET ipsu_name = 'Non blocking' WHERE t_ipsu_id = 1;
UPDATE itsm.t_ipsu SET ipsu_name = 'Individual' WHERE t_ipsu_id = 2;
UPDATE itsm.t_ipsu SET ipsu_name = 'Group' WHERE t_ipsu_id = 3;
UPDATE itsm.t_ipsu SET ipsu_name = 'Low' WHERE t_ipsu_id = 11;
UPDATE itsm.t_ipsu SET ipsu_name = 'Medium' WHERE t_ipsu_id = 12;
UPDATE itsm.t_ipsu SET ipsu_name = 'High' WHERE t_ipsu_id = 13;
UPDATE itsm.t_ipsu SET ipsu_name = 'Low' WHERE t_ipsu_id = 21;
UPDATE itsm.t_ipsu SET ipsu_name = 'Medium' WHERE t_ipsu_id = 22;
UPDATE itsm.t_ipsu SET ipsu_name = 'High' WHERE t_ipsu_id = 23;
UPDATE itsm.t_ipsu SET ipsu_name = 'Normal' WHERE t_ipsu_id = 31;
UPDATE itsm.t_ipsu SET ipsu_name = 'Urgent' WHERE t_ipsu_id = 32;
UPDATE itsm.t_ipsu SET ipsu_name = 'Immediate' WHERE t_ipsu_id = 33;
UPDATE itsm.t_satisfaction_level SET satisfaction_level = 'Very high' WHERE t_satisfaction_level_id = 1;
UPDATE itsm.t_satisfaction_level SET satisfaction_level = 'High' WHERE t_satisfaction_level_id = 2;
UPDATE itsm.t_satisfaction_level SET satisfaction_level = 'Medium' WHERE t_satisfaction_level_id = 3;
UPDATE itsm.t_satisfaction_level SET satisfaction_level = 'Low' WHERE t_satisfaction_level_id = 4;
